/* AUTO-GENERATED by scripts/update-news.mjs — do not edit by hand.
   Refreshed weekly by the update-news GitHub Action.
   Last update: 2026-08-24 */
var AI_NEWS_LIVE = [
  {
    "headline": "Debates over AI consciousness are a trap",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/08/20/1142571/ai-consciousness-debate-trap/"
  },
  {
    "headline": "Unlocking hidden revenue streams with market models",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "tools",
    "url": "https://www.technologyreview.com/2026/08/20/1142070/unlocking-hidden-revenue-streams-with-market-models/"
  },
  {
    "headline": "Introducing AI Futures",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://openai.com/index/introducing-ai-futures"
  },
  {
    "headline": "Stampli cuts launch hours by 68% using ChatGPT Work",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "tools",
    "url": "https://openai.com/index/stampli"
  },
  {
    "headline": "Offering Zero Data Retention for frontier models",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "tools",
    "url": "https://openai.com/index/offering-zero-data-retention-for-frontier-models"
  },
  {
    "headline": "5 new ways to level up your learning with Search",
    "source": "Google",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://blog.google/products-and-platforms/products/search/back-to-school-study-tools/"
  },
  {
    "headline": "OpenAI slows down training after its AI carried out hack",
    "source": "BBC News",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.bbc.co.uk/news/articles/c235dmndylzo?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "Replit expands access to software creation with GPT-5.6 Luna",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://openai.com/index/replit"
  },
  {
    "headline": "OpenAI makes ChatGPT less 'human' for teens in new safety update",
    "source": "BBC News",
    "date": "Aug 2026",
    "tag": "ethics",
    "url": "https://www.bbc.co.uk/news/articles/czxqz91n5n8o?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "We still don’t know how people are really using AI",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/08/18/1142226/how-people-use-ai/"
  },
  {
    "headline": "AI to help planes avoid climate-warming 'sky graffiti'",
    "source": "BBC News",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.bbc.co.uk/news/articles/c62em5lpvnjo?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "AI’s recursive self-improvement might not come so quickly after all",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/08/18/1142188/ai-recursive-self-improvement/"
  }
];
