/* AUTO-GENERATED by scripts/update-news.mjs — do not edit by hand.
   Refreshed weekly by the update-news GitHub Action.
   Last update: 2026-08-31 */
var AI_NEWS_LIVE = [
  {
    "headline": "Our decision on Cursor following its acquisition by SpaceX",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://openai.com/index/our-decision-on-cursor-following-its-acquisition-by-spacex"
  },
  {
    "headline": "Matt Lucas and Hugh Bonneville among actors calling for law on AI voice cloning",
    "source": "BBC News",
    "date": "Aug 2026",
    "tag": "policy",
    "url": "https://www.bbc.co.uk/news/articles/c4gv5gepxnyo?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "Supporting Thailand’s next generation of AI startups",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://openai.com/index/supporting-next-generation-ai-startups-thailand"
  },
  {
    "headline": "3 new ways to plan and book travel in Search",
    "source": "Google",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://blog.google/products-and-platforms/products/search/book-travel-ai-mode/"
  },
  {
    "headline": "Better answers, broader thinking: What students gain from ChatGPT and critical-thinking training",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://openai.com/index/what-students-gain-from-chatgpt-critical-thinking-training"
  },
  {
    "headline": "Expanding OpenAI’s presence in Brazil",
    "source": "OpenAI",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://openai.com/index/expanding-our-presence-in-brazil"
  },
  {
    "headline": "Unexpected chat between OpenAI agents led to Hugging Face hack",
    "source": "BBC News",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.bbc.co.uk/news/articles/cj9xj89dk40o?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "Nvidia revenue doubles on continued AI demand",
    "source": "BBC News",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.bbc.co.uk/news/articles/ce871n7lyvlo?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "The inside story on why OpenAI agents hacked Hugging Face",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/08/26/1143013/the-inside-story-on-why-openai-agents-hacked-hugging-face/"
  },
  {
    "headline": "Raised on AI",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/08/26/1141949/editors-letter-september-2026/"
  },
  {
    "headline": "AI models flub these intelligence tests. Can you fare any better?",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "tools",
    "url": "https://www.technologyreview.com/2026/08/26/1141952/puzzles-ai-models-flub-these-tests/"
  },
  {
    "headline": "Bill Gates says we’ve passed AI’s danger thresholds. Now what?",
    "source": "MIT Technology Review",
    "date": "Aug 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/08/26/1142946/bill-gates-ai-danger-threshold/"
  }
];
