/* AUTO-GENERATED by scripts/update-news.mjs — do not edit by hand.
   Refreshed weekly by the update-news GitHub Action.
   Last update: 2026-07-13 */
var AI_NEWS_LIVE = [
  {
    "headline": "Meta pulls new AI image feature after days of backlash",
    "source": "BBC News",
    "date": "Jul 2026",
    "tag": "tools",
    "url": "https://www.bbc.co.uk/news/articles/c2dy6e8klw0o?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "Apple sues OpenAI, its employees claiming theft of trade secrets",
    "source": "BBC News",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://www.bbc.co.uk/news/articles/cy8w379e091o?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "How Deutsche Telekom is rewiring telecommunications with AI",
    "source": "OpenAI",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://openai.com/index/deutsche-telekom"
  },
  {
    "headline": "Anthropic found a hidden space where Claude puzzles over concepts",
    "source": "MIT Technology Review",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/07/09/1140293/anthropic-found-a-hidden-space-where-claude-puzzles-over-concepts/"
  },
  {
    "headline": "GPT-5.6 is now the preferred model in Microsoft 365 Copilot",
    "source": "OpenAI",
    "date": "Jul 2026",
    "tag": "tools",
    "url": "https://openai.com/index/gpt-5-6-preferred-model-microsoft-365-copilot"
  },
  {
    "headline": "GPT-5.6: Frontier intelligence that scales with your ambition",
    "source": "OpenAI",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://openai.com/index/gpt-5-6"
  },
  {
    "headline": "ChatGPT is now a partner for your most ambitious work",
    "source": "OpenAI",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://openai.com/index/chatgpt-for-your-most-ambitious-work"
  },
  {
    "headline": "Outcry as Meta lets users make AI images from public Instagram profile pics",
    "source": "BBC News",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://www.bbc.co.uk/news/articles/cp9lee19y1yo?at_medium=RSS&at_campaign=rss"
  },
  {
    "headline": "The foundational elements of AI architecture that IT leaders need to scale",
    "source": "MIT Technology Review",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/07/07/1139413/the-foundational-elements-of-ai-architecture-that-it-leaders-need-to-scale/"
  },
  {
    "headline": "Expanding Managed Agents in Gemini API: background tasks, remote MCP and more",
    "source": "Google",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://blog.google/innovation-and-ai/technology/developers-tools/expanding-managed-agents-gemini-api/"
  },
  {
    "headline": "Your family’s $300 stake in OpenAI",
    "source": "MIT Technology Review",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://www.technologyreview.com/2026/07/06/1140176/your-familys-300-stake-in-openai/"
  },
  {
    "headline": "Parents warned not to publicly share children’s images amid AI abuse risks",
    "source": "BBC News",
    "date": "Jul 2026",
    "tag": "industry",
    "url": "https://www.bbc.co.uk/news/articles/cd7wj7d0jzzo?at_medium=RSS&at_campaign=rss"
  }
];
