/* ── Quiz Bank: additional questions per lesson ── */
var QUIZ_BANK = {

  1: [
    { question: 'Which type of AI system powers most music and video recommendation features on streaming platforms?', options: ['Rule-based expert systems', 'Collaborative filtering / ML recommendation engines', 'Symbolic AI planners', 'Computer vision models'], correct: 1, explanation: 'Streaming platforms use machine learning recommendation engines that analyse listening/viewing patterns to suggest content.' },
    { question: 'What term describes AI that is designed and trained to perform one specific task, such as playing chess?', options: ['Artificial General Intelligence (AGI)', 'Narrow AI (Weak AI)', 'Superintelligence', 'Embodied AI'], correct: 1, explanation: 'Narrow AI (also called Weak AI) is optimised for a single domain and cannot transfer skills to other tasks.' },
    { question: 'When a search engine ranks results partly based on your previous searches, which AI concept is it applying?', options: ['Reinforcement learning from human feedback', 'Personalisation through user profiling', 'Natural language generation', 'Unsupervised clustering'], correct: 1, explanation: 'Search engines build user profiles from browsing history to personalise results — a form of applied machine learning.' },
    { question: 'Which statement best describes the difference between AI and automation?', options: ['They are the same thing — all automation is AI', 'Automation follows fixed rules; AI can adapt based on data patterns', 'AI only works with images; automation handles text', 'Automation requires internet access; AI does not'], correct: 1, explanation: 'Traditional automation executes fixed, pre-programmed rules, whereas AI systems learn from data and can adapt their behaviour.' }
  ],

  2: [
    { question: 'The "stochastic parrot" metaphor, coined by Bender et al. (2021), argues that large language models are best understood as:', options: ['Truly intelligent reasoners that understand meaning', 'Statistical pattern-matchers that recombine language without understanding', 'Systems that store and retrieve exact training sentences', 'Creative writers superior to human authors'], correct: 1, explanation: 'Bender et al. argue LLMs are "stochastic parrots" — they produce fluent text by predicting statistically likely word sequences, not by understanding meaning.' },
    { question: 'John Searle\'s Chinese Room thought experiment was designed to challenge which claim?', options: ['That computers can ever process language at all', 'That syntactic manipulation of symbols is sufficient for semantic understanding', 'That AI will inevitably become conscious', 'That translation software is more accurate than humans'], correct: 1, explanation: 'Searle argues a system can manipulate symbols according to rules (syntax) without ever understanding what they mean (semantics).' },
    { question: 'What is an "emergent capability" in the context of large language models?', options: ['A feature deliberately programmed by engineers', 'An ability that appears unexpectedly at scale without being explicitly trained', 'A bug caused by insufficient training data', 'A capability shared by all language models regardless of size'], correct: 1, explanation: 'Emergent capabilities are abilities (e.g. multi-step reasoning) that appear in larger models but were not present in smaller versions and were not explicitly trained.' },
    { question: 'An LLM confidently states a false fact with no indication of uncertainty. This is known as:', options: ['Bias amplification', 'Hallucination', 'Overfitting', 'Mode collapse'], correct: 1, explanation: 'Hallucination refers to when an AI generates plausible-sounding but factually incorrect content, often with false confidence.' }
  ],

  3: [
    { question: 'In supervised learning, what is the purpose of the validation set?', options: ['To provide the final, unbiased measure of model performance', 'To tune hyperparameters and catch overfitting during training', 'To generate synthetic extra training data', 'To label unlabelled examples automatically'], correct: 1, explanation: 'The validation set is used during training to tune the model and detect overfitting; the test set is kept separate for final evaluation.' },
    { question: 'Overfitting occurs when a model:', options: ['Has too few parameters to capture any patterns', 'Learns training data patterns so well it performs poorly on new data', 'Is trained on too many different tasks simultaneously', 'Cannot process inputs larger than its context window'], correct: 1, explanation: 'An overfit model has memorised the training data, including its noise, and so generalises poorly to unseen examples.' },
    { question: 'The 2012 AlexNet result was significant because it demonstrated that:', options: ['Recurrent neural networks could translate languages', 'Deep convolutional neural networks could dramatically outperform traditional methods on image recognition', 'Reinforcement learning could beat humans at board games', 'Transformer architectures were superior to CNNs'], correct: 1, explanation: 'AlexNet\'s win at ImageNet 2012 — reducing error from ~26% to ~15% — showed deep learning\'s power for vision and triggered the modern AI boom.' },
    { question: 'Which split of data should NEVER be used to make decisions during model development?', options: ['Training set', 'Validation set', 'Test set', 'Augmented set'], correct: 2, explanation: 'The test set must remain untouched until final evaluation; using it during development causes data leakage and over-optimistic performance estimates.' }
  ],

  4: [
    { question: 'LIME and SHAP are examples of tools used in which field?', options: ['Natural language generation', 'Explainable AI (XAI)', 'Adversarial machine learning', 'Data augmentation'], correct: 1, explanation: 'LIME and SHAP are Explainable AI tools that help interpret why a model made a particular prediction by highlighting influential features.' },
    { question: 'Under GDPR Article 22, individuals have the right to:', options: ['Demand that companies delete all AI models trained on their data', 'Not be subject to solely automated decisions with significant effects, and to request human review', 'Receive a copy of all training data used to build AI systems', 'Prevent companies from training any AI on publicly available data'], correct: 1, explanation: 'Article 22 gives people the right to human review of significant automated decisions (e.g. credit scoring, job screening).' },
    { question: 'Amazon scrapped its AI recruitment tool in 2018 primarily because:', options: ['It was too slow to process CVs at scale', 'It systematically downgraded CVs from women, having learnt from historically male-dominated hiring data', 'Candidates discovered how to game it with keyword stuffing', 'It violated GDPR data retention rules'], correct: 1, explanation: 'Amazon\'s tool was trained on 10 years of hiring data that reflected existing gender imbalances, causing it to penalise female applicants.' },
    { question: 'A "black box" AI model is one where:', options: ['The training data is kept private', 'The internal reasoning process cannot be inspected or explained', 'The model only works in low-light image conditions', 'Outputs are encrypted before delivery'], correct: 1, explanation: 'Black box models (e.g. deep neural networks) produce outputs without providing human-interpretable explanations of how inputs map to decisions.' }
  ],

  5: [
    { question: 'COMPAS is an AI tool used in the US criminal justice system. Research by ProPublica found it was biased in which way?', options: ['It over-predicted reoffending risk for white defendants compared with Black defendants', 'It under-predicted reoffending risk for Black defendants and over-predicted it for white defendants', 'It falsely flagged Black defendants as high-risk at nearly twice the rate of white defendants', 'It was accurate overall but produced random errors for individual cases'], correct: 2, explanation: 'ProPublica\'s 2016 analysis found COMPAS was nearly twice as likely to incorrectly label Black defendants as high risk compared with white defendants.' },
    { question: 'NIST research on facial recognition accuracy found that error rates for darker-skinned women were up to how many times higher than for lighter-skinned men?', options: ['2 times', '10 times', '100 times', '1000 times'], correct: 2, explanation: 'NIST\'s 2019 FRVT study found some algorithms had false positive rates up to 100 times higher for darker-skinned women than lighter-skinned men.' },
    { question: 'Which of the following is an example of "representation bias" in training data?', options: ['A dataset containing duplicate records', 'A medical diagnosis model trained almost entirely on data from male patients', 'A model that takes too long to train on large datasets', 'A dataset where labels were applied inconsistently'], correct: 1, explanation: 'Representation bias occurs when certain groups are under- or over-represented in training data, causing the model to perform worse for underrepresented groups.' },
    { question: 'Which bias mitigation approach modifies the training data rather than the algorithm itself?', options: ['Algorithmic fairness constraints', 'Re-sampling and re-weighting the dataset', 'Post-processing model outputs', 'Using a simpler, more interpretable model'], correct: 1, explanation: 'Re-sampling (over- or under-sampling groups) and re-weighting examples directly addresses imbalances in training data before the model is trained.' }
  ],

  6: [
    { question: 'The Cambridge Analytica scandal demonstrated a risk associated with which data practice?', options: ['Governments collecting biometric data without consent', 'Third-party apps harvesting Facebook user data at scale beyond stated purpose', 'AI-generated deepfakes being used in political advertising', 'Search engines storing location data indefinitely'], correct: 1, explanation: 'Cambridge Analytica exploited a Facebook API loophole to harvest data from millions of users who had not consented, then used it for political targeting.' },
    { question: 'Under GDPR, what is the legal basis most commonly cited for processing personal data for AI training?', options: ['Public interest', 'Legitimate interests', 'Explicit consent or legitimate interests', 'Contractual necessity'], correct: 2, explanation: 'GDPR requires a lawful basis; for AI training this is commonly explicit consent or legitimate interests (subject to balancing tests).' },
    { question: 'A "data supply chain" in AI refers to:', options: ['The physical infrastructure (cables/servers) that moves training data', 'The sequence of collection, processing, labelling and licensing steps that produce training datasets', 'The pipeline that transfers model weights between data centres', 'Blockchain records of data provenance'], correct: 1, explanation: 'The AI data supply chain encompasses all the steps from raw data collection through to labelled, licensed datasets ready for model training — each step introducing potential risks.' },
    { question: 'Which principle requires that personal data collected for one purpose should not be used for a different, incompatible purpose?', options: ['Data minimisation', 'Purpose limitation', 'Storage limitation', 'Integrity and confidentiality'], correct: 1, explanation: 'Purpose limitation (GDPR Article 5(1)(b)) prevents organisations from repurposing personal data in ways individuals did not expect or consent to.' }
  ],

  7: [
    { question: 'In the trolley problem applied to autonomous vehicles, a utilitarian approach would recommend:', options: ['Always prioritising the vehicle\'s passengers regardless of other outcomes', 'Minimising total harm even if that means actively choosing who is harmed', 'Refusing to act in any scenario where harm is unavoidable', 'Deferring all decisions to human drivers via remote override'], correct: 1, explanation: 'Utilitarianism judges actions by their outcomes — the right act is whichever minimises total harm, even if it requires actively redirecting harm.' },
    { question: 'Deontological ethics, associated with Immanuel Kant, would approach autonomous vehicle dilemmas by:', options: ['Calculating which outcome saves the most lives', 'Following duty-based rules regardless of consequences', 'Asking what most people in society would prefer', 'Prioritising the interests of the vehicle manufacturer'], correct: 1, explanation: 'Deontological ethics holds that certain actions are inherently right or wrong based on rules/duties, not on the outcomes they produce.' },
    { question: 'The concept of "moral agency" is significant for AI ethics because:', options: ['It determines whether an AI system can hold legal liability for its decisions', 'It raises questions about whether AI systems can genuinely make moral choices or only simulate them', 'It defines the minimum processing power needed for an AI to operate ethically', 'It establishes international standards for autonomous weapons systems'], correct: 1, explanation: 'Moral agency requires intentionality and understanding; debating whether AI has moral agency questions whether AI decisions carry genuine ethical weight.' },
    { question: 'Which ethical framework asks "what would a reasonable person consider virtuous behaviour?" rather than focusing on rules or outcomes?', options: ['Utilitarianism', 'Deontology', 'Virtue ethics', 'Social contract theory'], correct: 2, explanation: 'Virtue ethics (Aristotle) focuses on the character of the agent and what a virtuous person would do, rather than calculating outcomes or following fixed rules.' }
  ],

  8: [
    { question: 'A "human-in-the-loop" AI system means:', options: ['An AI that trains on data generated by humans', 'A human reviews and approves AI outputs before they take effect', 'A system where AI decisions are fully automated with no human role', 'An AI assistant embedded in a human-computer interface'], correct: 1, explanation: 'Human-in-the-loop means a human must review, approve, or act on AI outputs before a decision is implemented.' },
    { question: 'In which scenario would "human-out-of-the-loop" AI be most ethically problematic?', options: ['Spam filtering for email', 'Autonomous lethal weapons systems selecting targets', 'Auto-completing text messages', 'Sorting warehouse inventory'], correct: 1, explanation: 'Lethal, irreversible decisions with life-or-death consequences require human accountability; removing the human from the loop in such contexts is widely considered ethically unacceptable.' },
    { question: 'An AI-assisted hiring tool flags a candidate as low-priority. What does "human-on-the-loop" look like in this context?', options: ['The AI rejects the candidate automatically with no human review', 'A recruiter receives the AI\'s ranking and can override it before any candidate is contacted', 'The candidate is informed in real time by the AI', 'A committee votes to approve or reject the AI\'s entire ranked list'], correct: 1, explanation: 'Human-on-the-loop means a person monitors AI outputs and retains override authority, though the AI acts first — different from in-the-loop where human approval precedes action.' },
    { question: 'Why might over-reliance on human oversight be a practical limitation in high-volume AI systems?', options: ['Humans always make worse decisions than AI at scale', 'Reviewing every AI output is infeasible when systems process thousands of decisions per second', 'Human reviewers are legally prohibited from overriding AI in many jurisdictions', 'Oversight adds cost but never improves decision quality'], correct: 1, explanation: 'At scale (e.g. content moderation at social media volume), requiring human review of every decision is operationally impractical, creating pressure to automate.' }
  ],

  9: [
    { question: 'What does the "P" in the PTFC prompting framework stand for?', options: ['Purpose', 'Persona', 'Prompt', 'Parameter'], correct: 1, explanation: 'PTFC stands for Persona, Task, Format, Context — Persona tells the AI what role or expertise to adopt.' },
    { question: 'Why does specifying a format (e.g. "bullet list" or "table") in a prompt improve AI outputs?', options: ['It reduces the computational cost of generating a response', 'It constrains the AI to structure information in a way that matches your specific use case', 'It prevents the AI from using copyrighted material', 'It makes the prompt easier to store in memory'], correct: 1, explanation: 'Specifying format aligns the output structure with how you intend to use it, reducing post-processing and making responses directly usable.' },
    { question: 'A student asks an AI "Tell me about climate change." Which improvement best applies the PTFC framework?', options: ['"Tell me everything about climate change in detail"', '"You are an environmental scientist. Summarise the three main causes of climate change for a 16-year-old in three bullet points."', '"Climate change: write a lot"', '"What is climate change? Be comprehensive."'], correct: 1, explanation: 'The improved prompt specifies Persona (environmental scientist), Task (summarise three causes), Format (three bullet points) and Context (for a 16-year-old).' },
    { question: 'What is "prompt iteration" and why is it valuable?', options: ['Automatically running the same prompt 100 times to average the outputs', 'Systematically refining a prompt based on evaluating earlier outputs to progressively improve quality', 'Copying prompts from an online library rather than writing your own', 'Using AI to generate prompts on your behalf'], correct: 1, explanation: 'Prompt iteration treats prompting as a design process — you evaluate each output, identify what is missing or wrong, and refine accordingly.' }
  ],

  10: [
    { question: 'In most jurisdictions, who currently holds copyright in an image generated entirely by an AI with no human creative input?', options: ['The AI system that generated it', 'The company that built the AI model', 'Nobody — it enters the public domain', 'The user who wrote the prompt'], correct: 2, explanation: 'Courts in the US and UK have ruled that copyright requires human authorship; purely AI-generated works with no human creative contribution cannot be copyrighted.' },
    { question: 'The "stochastic parrot" critique is relevant to AI-generated creative work because it suggests:', options: ['AI systems are too slow to be commercially useful for creative industries', 'AI outputs are novel combinations of existing human work rather than genuinely original creations', 'Creative AI always requires explicit licensing of all source material', 'AI-generated art is indistinguishable from human art'], correct: 1, explanation: 'If LLMs are statistical recombinations of training data, AI "creativity" may be sophisticated remixing of existing human work rather than true originality.' },
    { question: 'Which legal concept refers to using copyrighted material without permission in ways that courts may nonetheless permit, based on purpose and effect?', options: ['Creative commons licensing', 'Fair use / fair dealing', 'Public domain dedication', 'Moral rights waiver'], correct: 1, explanation: 'Fair use (US) and fair dealing (UK/Commonwealth) are exceptions allowing limited use of copyrighted material for purposes like commentary, education, or research.' },
    { question: 'A musician uses an AI trained on existing songs to produce a new track. Which stakeholder group has raised the strongest objections to this practice?', options: ['Streaming platforms', 'Original artists and music publishers concerned about unlicensed training data', 'Podcast producers', 'Radio broadcasters'], correct: 1, explanation: 'Artists and publishers argue that training AI on their music without consent or compensation undermines their livelihoods and violates intellectual property rights.' }
  ]

};
