/* ── Quiz Bank: additional questions per lesson ── */
var QUIZ_BANK = {

  1: [
    { question: 'Which type of AI system powers most music and video recommendation features on streaming platforms?', options: ['Rule-based expert systems', 'Collaborative filtering / ML recommendation engines', 'Symbolic AI planners', 'Computer vision models'], correct: 1, explanation: 'Streaming platforms use machine learning recommendation engines that analyse listening/viewing patterns to suggest content.' },
    { question: 'What term describes AI that is designed and trained to perform one specific task, such as playing chess?', options: ['Artificial General Intelligence (AGI)', 'Narrow AI (Weak AI)', 'Superintelligence', 'Embodied AI'], correct: 1, explanation: 'Narrow AI (also called Weak AI) is optimised for a single domain and cannot transfer skills to other tasks.' },
    { question: 'When a search engine ranks results partly based on your previous searches, which AI concept is it applying?', options: ['Reinforcement learning from human feedback', 'Personalisation through user profiling', 'Natural language generation', 'Unsupervised clustering'], correct: 1, explanation: 'Search engines build user profiles from browsing history to personalise results — a form of applied machine learning.' },
    { question: 'Which statement best describes the difference between AI and automation?', options: ['They are the same thing — all automation is AI', 'Automation follows fixed rules; AI can adapt based on data patterns', 'AI only works with images; automation handles text', 'Automation requires internet access; AI does not'], correct: 1, explanation: 'Traditional automation executes fixed, pre-programmed rules, whereas AI systems learn from data and can adapt their behaviour.' }
  ],

  2: [
    { question: 'The "stochastic parrot" metaphor, coined by Bender et al. (2021), argues that large language models are best understood as:', options: ['Truly intelligent reasoners that understand meaning', 'Statistical pattern-matchers that recombine language without understanding', 'Systems that store and retrieve exact training sentences', 'Creative writers superior to human authors'], correct: 1, explanation: 'Bender et al. argue LLMs are "stochastic parrots" — they produce fluent text by predicting statistically likely word sequences, not by understanding meaning.' },
    { question: 'John Searle\'s Chinese Room thought experiment was designed to challenge which claim?', options: ['That computers can ever process language at all', 'That syntactic manipulation of symbols is sufficient for semantic understanding', 'That AI will inevitably become conscious', 'That translation software is more accurate than humans'], correct: 1, explanation: 'Searle argues a system can manipulate symbols according to rules (syntax) without ever understanding what they mean (semantics).' },
    { question: 'What is an "emergent capability" in the context of large language models?', options: ['A feature deliberately programmed by engineers', 'An ability that appears unexpectedly at scale without being explicitly trained', 'A bug caused by insufficient training data', 'A capability shared by all language models regardless of size'], correct: 1, explanation: 'Emergent capabilities are abilities (e.g. multi-step reasoning) that appear in larger models but were not present in smaller versions and were not explicitly trained.' },
    { question: 'An LLM confidently states a false fact with no indication of uncertainty. This is known as:', options: ['Bias amplification', 'Hallucination', 'Overfitting', 'Mode collapse'], correct: 1, explanation: 'Hallucination refers to when an AI generates plausible-sounding but factually incorrect content, often with false confidence.' }
  ],

  3: [
    { question: 'In supervised learning, what is the purpose of the validation set?', options: ['To provide the final, unbiased measure of model performance', 'To tune hyperparameters and catch overfitting during training', 'To generate synthetic extra training data', 'To label unlabelled examples automatically'], correct: 1, explanation: 'The validation set is used during training to tune the model and detect overfitting; the test set is kept separate for final evaluation.' },
    { question: 'Overfitting occurs when a model:', options: ['Has too few parameters to capture any patterns', 'Learns training data patterns so well it performs poorly on new data', 'Is trained on too many different tasks simultaneously', 'Cannot process inputs larger than its context window'], correct: 1, explanation: 'An overfit model has memorised the training data, including its noise, and so generalises poorly to unseen examples.' },
    { question: 'The 2012 AlexNet result was significant because it demonstrated that:', options: ['Recurrent neural networks could translate languages', 'Deep convolutional neural networks could dramatically outperform traditional methods on image recognition', 'Reinforcement learning could beat humans at board games', 'Transformer architectures were superior to CNNs'], correct: 1, explanation: 'AlexNet\'s win at ImageNet 2012 — reducing error from ~26% to ~15% — showed deep learning\'s power for vision and triggered the modern AI boom.' },
    { question: 'Which split of data should NEVER be used to make decisions during model development?', options: ['Training set', 'Validation set', 'Test set', 'Augmented set'], correct: 2, explanation: 'The test set must remain untouched until final evaluation; using it during development causes data leakage and over-optimistic performance estimates.' }
  ],

  4: [
    { question: 'LIME and SHAP are examples of tools used in which field?', options: ['Natural language generation', 'Explainable AI (XAI)', 'Adversarial machine learning', 'Data augmentation'], correct: 1, explanation: 'LIME and SHAP are Explainable AI tools that help interpret why a model made a particular prediction by highlighting influential features.' },
    { question: 'Under GDPR Article 22, individuals have the right to:', options: ['Demand that companies delete all AI models trained on their data', 'Not be subject to solely automated decisions with significant effects, and to request human review', 'Receive a copy of all training data used to build AI systems', 'Prevent companies from training any AI on publicly available data'], correct: 1, explanation: 'Article 22 gives people the right to human review of significant automated decisions (e.g. credit scoring, job screening).' },
    { question: 'Amazon scrapped its AI recruitment tool in 2018 primarily because:', options: ['It was too slow to process CVs at scale', 'It systematically downgraded CVs from women, having learnt from historically male-dominated hiring data', 'Candidates discovered how to game it with keyword stuffing', 'It violated GDPR data retention rules'], correct: 1, explanation: 'Amazon\'s tool was trained on 10 years of hiring data that reflected existing gender imbalances, causing it to penalise female applicants.' },
    { question: 'A "black box" AI model is one where:', options: ['The training data is kept private', 'The internal reasoning process cannot be inspected or explained', 'The model only works in low-light image conditions', 'Outputs are encrypted before delivery'], correct: 1, explanation: 'Black box models (e.g. deep neural networks) produce outputs without providing human-interpretable explanations of how inputs map to decisions.' }
  ],

  5: [
    { question: 'COMPAS is an AI tool used in the US criminal justice system. Research by ProPublica found it was biased in which way?', options: ['It over-predicted reoffending risk for white defendants compared with Black defendants', 'It under-predicted reoffending risk for Black defendants and over-predicted it for white defendants', 'It falsely flagged Black defendants as high-risk at nearly twice the rate of white defendants', 'It was accurate overall but produced random errors for individual cases'], correct: 2, explanation: 'ProPublica\'s 2016 analysis found COMPAS was nearly twice as likely to incorrectly label Black defendants as high risk compared with white defendants.' },
    { question: 'NIST research on facial recognition accuracy found that error rates for darker-skinned women were up to how many times higher than for lighter-skinned men?', options: ['2 times', '10 times', '100 times', '1000 times'], correct: 2, explanation: 'NIST\'s 2019 FRVT study found some algorithms had false positive rates up to 100 times higher for darker-skinned women than lighter-skinned men.' },
    { question: 'Which of the following is an example of "representation bias" in training data?', options: ['A dataset containing duplicate records', 'A medical diagnosis model trained almost entirely on data from male patients', 'A model that takes too long to train on large datasets', 'A dataset where labels were applied inconsistently'], correct: 1, explanation: 'Representation bias occurs when certain groups are under- or over-represented in training data, causing the model to perform worse for underrepresented groups.' },
    { question: 'Which bias mitigation approach modifies the training data rather than the algorithm itself?', options: ['Algorithmic fairness constraints', 'Re-sampling and re-weighting the dataset', 'Post-processing model outputs', 'Using a simpler, more interpretable model'], correct: 1, explanation: 'Re-sampling (over- or under-sampling groups) and re-weighting examples directly addresses imbalances in training data before the model is trained.' }
  ],

  6: [
    { question: 'The Cambridge Analytica scandal demonstrated a risk associated with which data practice?', options: ['Governments collecting biometric data without consent', 'Third-party apps harvesting Facebook user data at scale beyond stated purpose', 'AI-generated deepfakes being used in political advertising', 'Search engines storing location data indefinitely'], correct: 1, explanation: 'Cambridge Analytica exploited a Facebook API loophole to harvest data from millions of users who had not consented, then used it for political targeting.' },
    { question: 'Under GDPR, what is the legal basis most commonly cited for processing personal data for AI training?', options: ['Public interest', 'Legitimate interests', 'Explicit consent or legitimate interests', 'Contractual necessity'], correct: 2, explanation: 'GDPR requires a lawful basis; for AI training this is commonly explicit consent or legitimate interests (subject to balancing tests).' },
    { question: 'A "data supply chain" in AI refers to:', options: ['The physical infrastructure (cables/servers) that moves training data', 'The sequence of collection, processing, labelling and licensing steps that produce training datasets', 'The pipeline that transfers model weights between data centres', 'Blockchain records of data provenance'], correct: 1, explanation: 'The AI data supply chain encompasses all the steps from raw data collection through to labelled, licensed datasets ready for model training — each step introducing potential risks.' },
    { question: 'Which principle requires that personal data collected for one purpose should not be used for a different, incompatible purpose?', options: ['Data minimisation', 'Purpose limitation', 'Storage limitation', 'Integrity and confidentiality'], correct: 1, explanation: 'Purpose limitation (GDPR Article 5(1)(b)) prevents organisations from repurposing personal data in ways individuals did not expect or consent to.' }
  ],

  7: [
    { question: 'In the trolley problem applied to autonomous vehicles, a utilitarian approach would recommend:', options: ['Always prioritising the vehicle\'s passengers regardless of other outcomes', 'Minimising total harm even if that means actively choosing who is harmed', 'Refusing to act in any scenario where harm is unavoidable', 'Deferring all decisions to human drivers via remote override'], correct: 1, explanation: 'Utilitarianism judges actions by their outcomes — the right act is whichever minimises total harm, even if it requires actively redirecting harm.' },
    { question: 'Deontological ethics, associated with Immanuel Kant, would approach autonomous vehicle dilemmas by:', options: ['Calculating which outcome saves the most lives', 'Following duty-based rules regardless of consequences', 'Asking what most people in society would prefer', 'Prioritising the interests of the vehicle manufacturer'], correct: 1, explanation: 'Deontological ethics holds that certain actions are inherently right or wrong based on rules/duties, not on the outcomes they produce.' },
    { question: 'The concept of "moral agency" is significant for AI ethics because:', options: ['It determines whether an AI system can hold legal liability for its decisions', 'It raises questions about whether AI systems can genuinely make moral choices or only simulate them', 'It defines the minimum processing power needed for an AI to operate ethically', 'It establishes international standards for autonomous weapons systems'], correct: 1, explanation: 'Moral agency requires intentionality and understanding; debating whether AI has moral agency questions whether AI decisions carry genuine ethical weight.' },
    { question: 'Which ethical framework asks "what would a reasonable person consider virtuous behaviour?" rather than focusing on rules or outcomes?', options: ['Utilitarianism', 'Deontology', 'Virtue ethics', 'Social contract theory'], correct: 2, explanation: 'Virtue ethics (Aristotle) focuses on the character of the agent and what a virtuous person would do, rather than calculating outcomes or following fixed rules.' }
  ],

  8: [
    { question: 'A "human-in-the-loop" AI system means:', options: ['An AI that trains on data generated by humans', 'A human reviews and approves AI outputs before they take effect', 'A system where AI decisions are fully automated with no human role', 'An AI assistant embedded in a human-computer interface'], correct: 1, explanation: 'Human-in-the-loop means a human must review, approve, or act on AI outputs before a decision is implemented.' },
    { question: 'In which scenario would "human-out-of-the-loop" AI be most ethically problematic?', options: ['Spam filtering for email', 'Autonomous lethal weapons systems selecting targets', 'Auto-completing text messages', 'Sorting warehouse inventory'], correct: 1, explanation: 'Lethal, irreversible decisions with life-or-death consequences require human accountability; removing the human from the loop in such contexts is widely considered ethically unacceptable.' },
    { question: 'An AI-assisted hiring tool flags a candidate as low-priority. What does "human-on-the-loop" look like in this context?', options: ['The AI rejects the candidate automatically with no human review', 'A recruiter receives the AI\'s ranking and can override it before any candidate is contacted', 'The candidate is informed in real time by the AI', 'A committee votes to approve or reject the AI\'s entire ranked list'], correct: 1, explanation: 'Human-on-the-loop means a person monitors AI outputs and retains override authority, though the AI acts first — different from in-the-loop where human approval precedes action.' },
    { question: 'Why might over-reliance on human oversight be a practical limitation in high-volume AI systems?', options: ['Humans always make worse decisions than AI at scale', 'Reviewing every AI output is infeasible when systems process thousands of decisions per second', 'Human reviewers are legally prohibited from overriding AI in many jurisdictions', 'Oversight adds cost but never improves decision quality'], correct: 1, explanation: 'At scale (e.g. content moderation at social media volume), requiring human review of every decision is operationally impractical, creating pressure to automate.' }
  ],

  9: [
    { question: 'What does the "P" in the PTFC prompting framework stand for?', options: ['Purpose', 'Persona', 'Prompt', 'Parameter'], correct: 1, explanation: 'PTFC stands for Persona, Task, Format, Context — Persona tells the AI what role or expertise to adopt.' },
    { question: 'Why does specifying a format (e.g. "bullet list" or "table") in a prompt improve AI outputs?', options: ['It reduces the computational cost of generating a response', 'It constrains the AI to structure information in a way that matches your specific use case', 'It prevents the AI from using copyrighted material', 'It makes the prompt easier to store in memory'], correct: 1, explanation: 'Specifying format aligns the output structure with how you intend to use it, reducing post-processing and making responses directly usable.' },
    { question: 'A student asks an AI "Tell me about climate change." Which improvement best applies the PTFC framework?', options: ['"Tell me everything about climate change in detail"', '"You are an environmental scientist. Summarise the three main causes of climate change for a 16-year-old in three bullet points."', '"Climate change: write a lot"', '"What is climate change? Be comprehensive."'], correct: 1, explanation: 'The improved prompt specifies Persona (environmental scientist), Task (summarise three causes), Format (three bullet points) and Context (for a 16-year-old).' },
    { question: 'What is "prompt iteration" and why is it valuable?', options: ['Automatically running the same prompt 100 times to average the outputs', 'Systematically refining a prompt based on evaluating earlier outputs to progressively improve quality', 'Copying prompts from an online library rather than writing your own', 'Using AI to generate prompts on your behalf'], correct: 1, explanation: 'Prompt iteration treats prompting as a design process — you evaluate each output, identify what is missing or wrong, and refine accordingly.' }
  ],

  10: [
    { question: 'In most jurisdictions, who currently holds copyright in an image generated entirely by an AI with no human creative input?', options: ['The AI system that generated it', 'The company that built the AI model', 'Nobody — it enters the public domain', 'The user who wrote the prompt'], correct: 2, explanation: 'Courts in the US and UK have ruled that copyright requires human authorship; purely AI-generated works with no human creative contribution cannot be copyrighted.' },
    { question: 'The "stochastic parrot" critique is relevant to AI-generated creative work because it suggests:', options: ['AI systems are too slow to be commercially useful for creative industries', 'AI outputs are novel combinations of existing human work rather than genuinely original creations', 'Creative AI always requires explicit licensing of all source material', 'AI-generated art is indistinguishable from human art'], correct: 1, explanation: 'If LLMs are statistical recombinations of training data, AI "creativity" may be sophisticated remixing of existing human work rather than true originality.' },
    { question: 'Which legal concept refers to using copyrighted material without permission in ways that courts may nonetheless permit, based on purpose and effect?', options: ['Creative commons licensing', 'Fair use / fair dealing', 'Public domain dedication', 'Moral rights waiver'], correct: 1, explanation: 'Fair use (US) and fair dealing (UK/Commonwealth) are exceptions allowing limited use of copyrighted material for purposes like commentary, education, or research.' },
    { question: 'A musician uses an AI trained on existing songs to produce a new track. Which stakeholder group has raised the strongest objections to this practice?', options: ['Streaming platforms', 'Original artists and music publishers concerned about unlicensed training data', 'Podcast producers', 'Radio broadcasters'], correct: 1, explanation: 'Artists and publishers argue that training AI on their music without consent or compensation undermines their livelihoods and violates intellectual property rights.' }
  ],

  11: [
    { question: 'A Goldman Sachs report estimated that generative AI could automate tasks affecting how many jobs globally?', options: ['30 million', '300 million', '3 billion', '30 billion'], correct: 1, explanation: 'Goldman Sachs (2023) estimated generative AI could expose 300 million full-time jobs globally to automation of at least some tasks.' },
    { question: 'The World Economic Forum\'s "centaur model" of future work suggests:', options: ['AI will replace all human knowledge workers within a decade', 'The most productive workers will combine human judgement with AI capabilities', 'Only technical roles will survive widespread automation', 'Human creativity is irrelevant once AI reaches human-level performance'], correct: 1, explanation: 'Like the chess centaur (human + computer), future high-value work will combine irreplaceable human skills (judgement, ethics, creativity) with AI\'s processing power.' },
    { question: 'When using AI for research, "triangulating" a claim means:', options: ['Asking the same AI three times and taking the majority answer', 'Verifying the AI\'s output against multiple independent, authoritative primary sources', 'Using three different AI tools and comparing their answers', 'Checking that the claim appears in at least three Wikipedia articles'], correct: 1, explanation: 'Triangulation means cross-referencing AI-generated claims against independent primary sources (academic papers, official reports) to verify accuracy.' },
    { question: 'Which sector did Goldman Sachs identify as among the MOST exposed to AI-driven task automation?', options: ['Agriculture and forestry', 'Construction and manual trades', 'Administrative and office support roles', 'Emergency services'], correct: 2, explanation: 'Administrative and office support jobs, which involve repetitive information processing, were identified as highly exposed to automation by generative AI.' }
  ],

  12: [
    { question: 'A Wharton Business School study found that professionals using AI with iterative prompting outperformed those without AI by approximately:', options: ['10%', '25%', '40%', '75%'], correct: 2, explanation: 'The Wharton study found that workers using AI with 3+ iterations of prompt refinement achieved outputs roughly 40% better than those without AI assistance.' },
    { question: 'What is the core risk of using AI as a revision partner for academic work without exercising critical judgement?', options: ['AI suggestions are always too formal for academic writing', 'Accepting AI suggestions uncritically can weaken your argument or introduce inaccuracies', 'AI cannot process documents longer than one page', 'Schools can always detect AI-revised work with plagiarism software'], correct: 1, explanation: 'AI revision tools often prioritise fluency over accuracy or logical strength — uncritical acceptance can substitute an AI\'s generic phrasing for your more precise original argument.' },
    { question: 'Which academic integrity principle is most relevant when using AI to revise your own written work?', options: ['Ensuring all sources are in Harvard referencing format', 'Transparency about AI use and ensuring the ideas and arguments remain genuinely your own', 'Not using AI for any part of assessed work under any circumstances', 'Limiting AI use to grammar checking only'], correct: 1, explanation: 'Most academic integrity frameworks require disclosure of AI use and that the intellectual contribution — ideas, argument, analysis — is the student\'s own work.' },
    { question: 'The "iteration mindset" in prompt engineering treats prompting as analogous to:', options: ['Memorising a fixed set of magic commands', 'A design or writing process where multiple drafts progressively improve the output', 'Searching a database with increasingly specific keywords', 'Programming a function with fixed inputs and outputs'], correct: 1, explanation: 'Like drafting and redrafting a piece of writing, the iteration mindset sees each AI output as a draft to evaluate and improve through refined prompts.' }
  ],

  13: [
    { question: 'GANs (Generative Adversarial Networks) create convincing deepfakes through:', options: ['Copying and pasting frames from existing video footage', 'A generator and discriminator network competing until outputs are indistinguishable from real content', 'Rule-based face-swapping using 3D mesh mapping', 'Retrieving the most similar face from a database of images'], correct: 1, explanation: 'GANs use two competing neural networks — a generator creates fakes and a discriminator tries to detect them — training each other until fakes become convincing.' },
    { question: 'What is the "liar\'s dividend" in the context of deepfakes?', options: ['The financial gain made by selling deepfake-generating software', 'The ability for bad actors to dismiss authentic evidence as a deepfake', 'The legal protection journalists have when publishing deepfakes in the public interest', 'Profit made from deepfake content on social media platforms'], correct: 1, explanation: 'The liar\'s dividend is the secondary harm of deepfakes: even real footage can be dismissed as "probably a deepfake," eroding trust in genuine evidence.' },
    { question: 'C2PA (Coalition for Content Provenance and Authenticity) aims to combat deepfakes by:', options: ['Banning all AI image generation tools', 'Embedding cryptographic provenance metadata into media at the point of creation', 'Requiring social media platforms to label all images as AI or human', 'Training classifiers to detect deepfakes after the fact'], correct: 1, explanation: 'C2PA creates a standard for signing media with tamper-evident provenance data at creation, allowing recipients to verify origin and edit history.' },
    { question: 'The SIFT method for evaluating online content stands for:', options: ['Search, Identify, Filter, Trust', 'Stop, Investigate the source, Find better coverage, Trace claims', 'Source, Information, Fact-check, Triangulate', 'Skim, Infer, Flag, Thoroughly check'], correct: 1, explanation: 'SIFT is a lateral reading framework: Stop before sharing, Investigate the source, Find better coverage upstream, Trace claims to their origin.' }
  ],

  14: [
    { question: 'London has approximately how many CCTV cameras, making it one of the most surveilled cities globally?', options: ['94,000', '940,000', '9,400', '9,400,000'], correct: 0, explanation: 'London has an estimated 940,000 CCTV cameras — approximately one for every nine residents — among the highest densities of any city globally.' },
    { question: 'In 2020, Robert Williams became the first US citizen known to be wrongly arrested due to a facial recognition error. The core failure was:', options: ['The system was hacked by criminals to frame him', 'A facial recognition system matched him to a blurry CCTV still; officers arrested him without further verification', 'He was misidentified by a human officer who blamed AI retroactively', 'The AI confused him with a family member who was a suspect'], correct: 1, explanation: 'Detroit police used a facial recognition match from grainy footage as justification for arrest without additional corroborating evidence — a failure of human oversight.' },
    { question: 'The EU AI Act classifies real-time remote biometric identification in public spaces as:', options: ['Minimal risk — permitted without restriction', 'Limited risk — permitted with transparency obligations', 'High risk — permitted with strict safeguards', 'Unacceptable risk — prohibited (with narrow law enforcement exceptions)'], correct: 3, explanation: 'The EU AI Act generally prohibits real-time biometric surveillance in public spaces, treating it as unacceptable risk, with narrow exceptions for serious crime prevention.' },
    { question: 'NIST\'s Face Recognition Vendor Testing (FRVT) found accuracy disparities are particularly pronounced for which demographic group?', options: ['Older white males', 'Younger Black and East Asian women', 'Children under 12 of all ethnicities', 'Middle-aged South Asian men'], correct: 1, explanation: 'NIST found the largest accuracy gaps (up to 100x higher false positive rates) for darker-skinned women — particularly Black and East Asian female faces.' }
  ],

  15: [
    { question: 'Training GPT-3 was estimated to produce approximately how much CO₂?', options: ['55 tonnes', '552 tonnes', '5,520 tonnes', '55,200 tonnes'], correct: 1, explanation: 'Training GPT-3 was estimated to produce around 552 tonnes of CO₂ equivalent — comparable to the lifetime emissions of five average cars.' },
    { question: 'How does a single ChatGPT query compare to a standard Google search in terms of energy consumption?', options: ['About the same energy', 'Approximately 10 times more energy', 'Approximately 100 times more energy', 'Slightly less energy'], correct: 1, explanation: 'Research estimates a ChatGPT query uses roughly 10x the energy of a Google search due to the computational demands of large language model inference.' },
    { question: 'DeepMind\'s GNoME project is cited as an example of AI\'s potential positive environmental impact because it:', options: ['Optimised Google\'s data centre cooling to reduce energy use by 40%', 'Discovered 2.2 million new crystal structures that could accelerate materials science including better batteries', 'Predicted 10-day weather forecasts with greater accuracy than traditional models', 'Identified optimal locations for wind and solar farms globally'], correct: 1, explanation: 'GNoME used AI to predict stable crystal structures at scale, potentially accelerating discovery of materials for solar cells, batteries, and other clean technologies.' },
    { question: 'Beyond carbon emissions, AI data centres have which other significant environmental impact?', options: ['Soil contamination from server manufacturing', 'Enormous freshwater consumption for cooling systems', 'Electromagnetic interference with local wildlife', 'Deforestation for mineral extraction'], correct: 1, explanation: 'Data centres use vast quantities of fresh water for cooling — Google reported using 5.6 billion gallons in 2022 — creating competition with local communities for water resources.' }
  ],

  16: [
    { question: 'Under the EU AI Act, which application is classified as "unacceptable risk" and banned outright?', options: ['AI used in university admissions decisions', 'Social scoring systems that rank citizens based on their behaviour', 'AI-powered customer service chatbots', 'Recommendation algorithms on social media'], correct: 1, explanation: 'The EU AI Act bans "unacceptable risk" uses including social scoring by governments, subliminal manipulation, and (with exceptions) real-time biometric surveillance.' },
    { question: 'The UK\'s approach to AI regulation (as of 2023–24) differs from the EU\'s by:', options: ['Being more restrictive with stricter penalties for violations', 'Favouring a pro-innovation, principles-based approach without a single binding AI law', 'Focusing exclusively on military and defence applications', 'Requiring all AI systems to be certified before deployment'], correct: 1, explanation: 'The UK has opted for a "pro-innovation" approach: directing existing regulators to apply their sector-specific powers to AI rather than creating a new overarching AI law.' },
    { question: 'China\'s national AI strategy includes which distinctive governance feature not present in most Western approaches?', options: ['A total ban on generative AI for consumer use', 'Requiring AI-generated content to carry watermarks and tying providers to state security obligations', 'Mandating open-source release of all AI models', 'Prohibiting foreign AI companies from operating in China'], correct: 1, explanation: 'China requires AI content watermarking, mandates that providers verify user identities, and places AI firms under national security laws — embedding AI governance into state control.' },
    { question: 'Which EU AI Act risk tier applies to AI used in CV screening and job recruitment?', options: ['Minimal risk', 'Limited risk', 'High risk', 'Unacceptable risk'], correct: 2, explanation: 'The EU AI Act classifies AI used in employment decisions (hiring, promotion, task allocation) as high risk, requiring transparency, human oversight, and conformity assessments.' }
  ],

  17: [
    { question: 'In a policy gap analysis for AI use in schools, which comparison is most useful as a benchmark?', options: ['The most permissive policy you can find online', 'Policies from comparable institutions, sector guidance documents, and regulatory frameworks', 'Your own intuition about what seems reasonable', 'Only the school\'s existing acceptable use policy for general IT'], correct: 1, explanation: 'Effective benchmarking draws on policies from peer institutions, official guidance (e.g. government frameworks), and relevant regulation to identify gaps in current practice.' },
    { question: 'When auditing an existing school AI policy, which question is most important to ask first?', options: ['How many pages is the current policy?', 'Does the policy actually reflect how AI is being used in the school right now?', 'Was the policy written by a legal professional?', 'How many staff have signed to say they have read it?'], correct: 1, explanation: 'The first audit question is whether the policy is current — policies quickly become outdated as AI tools evolve, creating a gap between stated rules and actual practice.' },
    { question: 'A "status quo" analysis in policy development refers to:', options: ['Deciding in advance what the final policy should say', 'Documenting the current situation — what AI tools are used, by whom, and under what rules — before drafting changes', 'Surveying students about their opinions on AI', 'Reviewing other countries\' national AI strategies'], correct: 1, explanation: 'Analysing the status quo means mapping the current reality — tools in use, existing rules, gaps and risks — to understand what the policy needs to address.' },
    { question: 'Which data would be most useful when assessing AI-related risks in a school setting?', options: ['The age of the school\'s IT infrastructure', 'Incidents of academic misconduct, data breaches, and student/staff AI use patterns', 'The school\'s Ofsted rating', 'The number of AI-related newspaper articles published this year'], correct: 1, explanation: 'Risk assessment requires evidence about actual harms and near-misses (misconduct, breaches, misuse patterns) to prioritise what a policy needs to address.' }
  ],

  18: [
    { question: 'An effective acceptable use policy for AI should include which of the following?', options: ['A list of every AI tool that will ever exist', 'Clear definitions, permitted uses, prohibited uses, and consequences for violations', 'Only restrictions — no guidance on permitted uses', 'Technical specifications for how AI models work'], correct: 1, explanation: 'A robust AUP balances clarity (definitions, permitted and prohibited uses) with accountability (consequences), giving users clear guidance on expected behaviour.' },
    { question: 'Why is it important to involve students in drafting a school AI acceptable use policy?', options: ['Students are legally required to co-author school policies', 'Student involvement increases ownership, surfaces real use cases, and produces more effective and fair policies', 'It reduces the time needed to write the policy', 'Students can provide technical expertise that teachers lack'], correct: 1, explanation: 'Participatory policy-making builds buy-in, ensures the policy addresses actual student behaviour, and develops students\' own understanding of responsible AI use.' },
    { question: 'Which scenario illustrates a conflict between "innovation" and "safeguarding" in an AI acceptable use policy?', options: ['Deciding whether to buy new computers for the school', 'Allowing students to use AI writing tools which boost engagement but may enable academic dishonesty', 'Choosing between two different brands of firewall', 'Deciding how to run parent information evenings about technology'], correct: 1, explanation: 'AI writing tools exemplify the tension: they may genuinely help struggling writers (innovation/access benefit) while also enabling submitting AI work as one\'s own (safeguarding risk).' },
    { question: 'What does "proportionality" mean in the context of AI policy enforcement?', options: ['All violations should receive the same punishment regardless of severity', 'Consequences should be calibrated to the seriousness of the violation and the student\'s intent', 'Policies only need to address the most serious possible misuses', 'Enforcement should be automatic and not involve human judgement'], correct: 1, explanation: 'Proportional enforcement means minor unintentional violations (e.g. accidentally using AI without disclosure) are treated differently from deliberate academic fraud.' }
  ],

  19: [
    { question: 'Which feature of formal policy language distinguishes it from informal guidance?', options: ['It uses shorter sentences', 'It uses precise, defined terms; modal verbs (must/shall/may); and numbered provisions', 'It avoids any reference to specific technologies', 'It is written in the first person'], correct: 1, explanation: 'Formal policy language uses precisely defined terms, mandatory ("must/shall") vs permissive ("may") language, and numbered provisions to avoid ambiguity.' },
    { question: 'An enforcement mechanism in a policy document serves what purpose?', options: ['It explains the technical details of AI systems covered by the policy', 'It specifies how violations will be identified, investigated, and what consequences will follow', 'It lists the names of people responsible for writing the policy', 'It provides a glossary of technical terms'], correct: 1, explanation: 'Without enforcement mechanisms (who monitors compliance, what investigation looks like, what sanctions apply), a policy has no teeth — it becomes aspirational rather than effective.' },
    { question: 'In policy drafting, a "scope" clause is used to:', options: ['Summarise the history of AI regulation', 'Define exactly who and what the policy applies to — and critically, what it does not cover', 'List all the AI tools currently in use at the organisation', 'Explain the ethical principles behind the policy'], correct: 1, explanation: 'The scope clause sets boundaries: which people, systems, and activities the policy covers, and which fall outside it — essential for avoiding ambiguity in application.' },
    { question: 'Why should a school AI policy include a review clause specifying when it will next be updated?', options: ['It is a legal requirement under GDPR', 'AI technology evolves rapidly; without scheduled reviews, policies quickly become outdated and unenforceable', 'Review clauses make policies look more professional', 'It allows the school to avoid responsibility during the review period'], correct: 1, explanation: 'AI capabilities change faster than most policy cycles — a review clause ensures the policy remains current, relevant, and enforceable as new tools emerge.' }
  ],

  20: [
    { question: 'In a simulated school policy ratification process, what is the purpose of a deliberative debate before voting?', options: ['To delay the vote until all disagreements disappear', 'To allow competing arguments to be heard and scrutinised so the vote is informed rather than arbitrary', 'To give teachers more time to write their own alternative policies', 'To ensure the most popular student\'s policy always wins'], correct: 1, explanation: 'Deliberative debate surfaces tradeoffs and challenges, enabling participants to make a more informed, considered vote rather than reacting to initial impressions.' },
    { question: 'When presenting a policy proposal, which rhetorical strategy is most effective at the opening?', options: ['Immediately reading out every clause of the policy', 'Opening with a concrete, relatable scenario that illustrates the problem your policy solves', 'Starting with a detailed explanation of how AI works technically', 'Criticising all competing policy proposals first'], correct: 1, explanation: 'A concrete opening scenario makes the problem vivid and personally relevant to your audience before introducing your solution — a classic persuasive structure.' },
    { question: 'A policy amendment proposed during debate should be evaluated on which primary criterion?', options: ['Whether it makes the policy longer', 'Whether it improves the policy\'s effectiveness, clarity, or fairness without undermining its core purpose', 'Whether the person proposing it is senior to the original author', 'Whether it has been tested at another institution first'], correct: 1, explanation: 'Amendments should be judged on their merits — whether they strengthen the policy — not on who proposes them or procedural factors.' },
    { question: 'After a class votes to ratify an AI policy, what is the most important next step for the policy to have real impact?', options: ['Filing it in a policy folder and not mentioning it again', 'Communicating it clearly to all stakeholders and establishing who is responsible for implementation', 'Publishing it on the school website for legal protection', 'Sending it to the local council for approval'], correct: 1, explanation: 'Ratification is only the start — a policy only works if stakeholders know about it, understand it, and someone is accountable for ensuring it is followed.' }
  ]

};
