/* ── Quiz Bank: additional questions per lesson ── */
var QUIZ_BANK = {

  1: [
    { question: 'Which type of AI system powers most music and video recommendation features on streaming platforms?', options: ['Rule-based expert systems', 'Collaborative filtering / ML recommendation engines', 'Symbolic AI planners', 'Computer vision models'], correct: 1, explanation: 'Streaming platforms use machine learning recommendation engines that analyse listening/viewing patterns to suggest content.' },
    { question: 'What term describes AI that is designed and trained to perform one specific task, such as playing chess?', options: ['Artificial General Intelligence (AGI)', 'Narrow AI (Weak AI)', 'Superintelligence', 'Embodied AI'], correct: 1, explanation: 'Narrow AI (also called Weak AI) is optimised for a single domain and cannot transfer skills to other tasks.' },
    { question: 'When a search engine ranks results partly based on your previous searches, which AI concept is it applying?', options: ['Reinforcement learning from human feedback', 'Personalisation through user profiling', 'Natural language generation', 'Unsupervised clustering'], correct: 1, explanation: 'Search engines build user profiles from browsing history to personalise results — a form of applied machine learning.' },
    { question: 'Which statement best describes the difference between AI and automation?', options: ['They are the same thing — all automation is AI', 'Automation follows fixed rules; AI can adapt based on data patterns', 'AI only works with images; automation handles text', 'Automation requires internet access; AI does not'], correct: 1, explanation: 'Traditional automation executes fixed, pre-programmed rules, whereas AI systems learn from data and can adapt their behaviour.' }
  ],

  2: [
    { question: 'The "stochastic parrot" metaphor, coined by Bender et al. (2021), argues that large language models are best understood as:', options: ['Truly intelligent reasoners that understand meaning', 'Statistical pattern-matchers that recombine language without understanding', 'Systems that store and retrieve exact training sentences', 'Creative writers superior to human authors'], correct: 1, explanation: 'Bender et al. argue LLMs are "stochastic parrots" — they produce fluent text by predicting statistically likely word sequences, not by understanding meaning.' },
    { question: 'John Searle\'s Chinese Room thought experiment was designed to challenge which claim?', options: ['That computers can ever process language at all', 'That syntactic manipulation of symbols is sufficient for semantic understanding', 'That AI will inevitably become conscious', 'That translation software is more accurate than humans'], correct: 1, explanation: 'Searle argues a system can manipulate symbols according to rules (syntax) without ever understanding what they mean (semantics).' },
    { question: 'What is an "emergent capability" in the context of large language models?', options: ['A feature deliberately programmed by engineers', 'An ability that appears unexpectedly at scale without being explicitly trained', 'A bug caused by insufficient training data', 'A capability shared by all language models regardless of size'], correct: 1, explanation: 'Emergent capabilities are abilities (e.g. multi-step reasoning) that appear in larger models but were not present in smaller versions and were not explicitly trained.' },
    { question: 'An LLM confidently states a false fact with no indication of uncertainty. This is known as:', options: ['Bias amplification', 'Hallucination', 'Overfitting', 'Mode collapse'], correct: 1, explanation: 'Hallucination refers to when an AI generates plausible-sounding but factually incorrect content, often with false confidence.' }
  ],

  3: [
    { question: 'In supervised learning, what is the purpose of the validation set?', options: ['To provide the final, unbiased measure of model performance', 'To tune hyperparameters and catch overfitting during training', 'To generate synthetic extra training data', 'To label unlabelled examples automatically'], correct: 1, explanation: 'The validation set is used during training to tune the model and detect overfitting; the test set is kept separate for final evaluation.' },
    { question: 'Overfitting occurs when a model:', options: ['Has too few parameters to capture any patterns', 'Learns training data patterns so well it performs poorly on new data', 'Is trained on too many different tasks simultaneously', 'Cannot process inputs larger than its context window'], correct: 1, explanation: 'An overfit model has memorised the training data, including its noise, and so generalises poorly to unseen examples.' },
    { question: 'The 2012 AlexNet result was significant because it demonstrated that:', options: ['Recurrent neural networks could translate languages', 'Deep convolutional neural networks could dramatically outperform traditional methods on image recognition', 'Reinforcement learning could beat humans at board games', 'Transformer architectures were superior to CNNs'], correct: 1, explanation: 'AlexNet\'s win at ImageNet 2012 — reducing error from ~26% to ~15% — showed deep learning\'s power for vision and triggered the modern AI boom.' },
    { question: 'Which split of data should NEVER be used to make decisions during model development?', options: ['Training set', 'Validation set', 'Test set', 'Augmented set'], correct: 2, explanation: 'The test set must remain untouched until final evaluation; using it during development causes data leakage and over-optimistic performance estimates.' }
  ],

  4: [
    { question: 'LIME and SHAP are examples of tools used in which field?', options: ['Natural language generation', 'Explainable AI (XAI)', 'Adversarial machine learning', 'Data augmentation'], correct: 1, explanation: 'LIME and SHAP are Explainable AI tools that help interpret why a model made a particular prediction by highlighting influential features.' },
    { question: 'Under GDPR Article 22, individuals have the right to:', options: ['Demand that companies delete all AI models trained on their data', 'Not be subject to solely automated decisions with significant effects, and to request human review', 'Receive a copy of all training data used to build AI systems', 'Prevent companies from training any AI on publicly available data'], correct: 1, explanation: 'Article 22 gives people the right to human review of significant automated decisions (e.g. credit scoring, job screening).' },
    { question: 'Amazon scrapped its AI recruitment tool in 2018 primarily because:', options: ['It was too slow to process CVs at scale', 'It systematically downgraded CVs from women, having learnt from historically male-dominated hiring data', 'Candidates discovered how to game it with keyword stuffing', 'It violated GDPR data retention rules'], correct: 1, explanation: 'Amazon\'s tool was trained on 10 years of hiring data that reflected existing gender imbalances, causing it to penalise female applicants.' },
    { question: 'A "black box" AI model is one where:', options: ['The training data is kept private', 'The internal reasoning process cannot be inspected or explained', 'The model only works in low-light image conditions', 'Outputs are encrypted before delivery'], correct: 1, explanation: 'Black box models (e.g. deep neural networks) produce outputs without providing human-interpretable explanations of how inputs map to decisions.' }
  ],

  5: [
    { question: 'COMPAS is an AI tool used in the US criminal justice system. Research by ProPublica found it was biased in which way?', options: ['It over-predicted reoffending risk for white defendants compared with Black defendants', 'It under-predicted reoffending risk for Black defendants and over-predicted it for white defendants', 'It falsely flagged Black defendants as high-risk at nearly twice the rate of white defendants', 'It was accurate overall but produced random errors for individual cases'], correct: 2, explanation: 'ProPublica\'s 2016 analysis found COMPAS was nearly twice as likely to incorrectly label Black defendants as high risk compared with white defendants.' },
    { question: 'NIST research on facial recognition accuracy found that error rates for darker-skinned women were up to how many times higher than for lighter-skinned men?', options: ['2 times', '10 times', '100 times', '1000 times'], correct: 2, explanation: 'NIST\'s 2019 FRVT study found some algorithms had false positive rates up to 100 times higher for darker-skinned women than lighter-skinned men.' },
    { question: 'Which of the following is an example of "representation bias" in training data?', options: ['A dataset containing duplicate records', 'A medical diagnosis model trained almost entirely on data from male patients', 'A model that takes too long to train on large datasets', 'A dataset where labels were applied inconsistently'], correct: 1, explanation: 'Representation bias occurs when certain groups are under- or over-represented in training data, causing the model to perform worse for underrepresented groups.' },
    { question: 'Which bias mitigation approach modifies the training data rather than the algorithm itself?', options: ['Algorithmic fairness constraints', 'Re-sampling and re-weighting the dataset', 'Post-processing model outputs', 'Using a simpler, more interpretable model'], correct: 1, explanation: 'Re-sampling (over- or under-sampling groups) and re-weighting examples directly addresses imbalances in training data before the model is trained.' }
  ],

  6: [
    { question: 'The Cambridge Analytica scandal demonstrated a risk associated with which data practice?', options: ['Governments collecting biometric data without consent', 'Third-party apps harvesting Facebook user data at scale beyond stated purpose', 'AI-generated deepfakes being used in political advertising', 'Search engines storing location data indefinitely'], correct: 1, explanation: 'Cambridge Analytica exploited a Facebook API loophole to harvest data from millions of users who had not consented, then used it for political targeting.' },
    { question: 'Under GDPR, what is the legal basis most commonly cited for processing personal data for AI training?', options: ['Public interest', 'Legitimate interests', 'Explicit consent or legitimate interests', 'Contractual necessity'], correct: 2, explanation: 'GDPR requires a lawful basis; for AI training this is commonly explicit consent or legitimate interests (subject to balancing tests).' },
    { question: 'A "data supply chain" in AI refers to:', options: ['The physical infrastructure (cables/servers) that moves training data', 'The sequence of collection, processing, labelling and licensing steps that produce training datasets', 'The pipeline that transfers model weights between data centres', 'Blockchain records of data provenance'], correct: 1, explanation: 'The AI data supply chain encompasses all the steps from raw data collection through to labelled, licensed datasets ready for model training — each step introducing potential risks.' },
    { question: 'Which principle requires that personal data collected for one purpose should not be used for a different, incompatible purpose?', options: ['Data minimisation', 'Purpose limitation', 'Storage limitation', 'Integrity and confidentiality'], correct: 1, explanation: 'Purpose limitation (GDPR Article 5(1)(b)) prevents organisations from repurposing personal data in ways individuals did not expect or consent to.' }
  ],

  7: [
    { question: 'In the trolley problem applied to autonomous vehicles, a utilitarian approach would recommend:', options: ['Always prioritising the vehicle\'s passengers regardless of other outcomes', 'Minimising total harm even if that means actively choosing who is harmed', 'Refusing to act in any scenario where harm is unavoidable', 'Deferring all decisions to human drivers via remote override'], correct: 1, explanation: 'Utilitarianism judges actions by their outcomes — the right act is whichever minimises total harm, even if it requires actively redirecting harm.' },
    { question: 'Deontological ethics, associated with Immanuel Kant, would approach autonomous vehicle dilemmas by:', options: ['Calculating which outcome saves the most lives', 'Following duty-based rules regardless of consequences', 'Asking what most people in society would prefer', 'Prioritising the interests of the vehicle manufacturer'], correct: 1, explanation: 'Deontological ethics holds that certain actions are inherently right or wrong based on rules/duties, not on the outcomes they produce.' },
    { question: 'The concept of "moral agency" is significant for AI ethics because:', options: ['It determines whether an AI system can hold legal liability for its decisions', 'It raises questions about whether AI systems can genuinely make moral choices or only simulate them', 'It defines the minimum processing power needed for an AI to operate ethically', 'It establishes international standards for autonomous weapons systems'], correct: 1, explanation: 'Moral agency requires intentionality and understanding; debating whether AI has moral agency questions whether AI decisions carry genuine ethical weight.' },
    { question: 'Which ethical framework asks "what would a reasonable person consider virtuous behaviour?" rather than focusing on rules or outcomes?', options: ['Utilitarianism', 'Deontology', 'Virtue ethics', 'Social contract theory'], correct: 2, explanation: 'Virtue ethics (Aristotle) focuses on the character of the agent and what a virtuous person would do, rather than calculating outcomes or following fixed rules.' }
  ],

  8: [
    { question: 'A "human-in-the-loop" AI system means:', options: ['An AI that trains on data generated by humans', 'A human reviews and approves AI outputs before they take effect', 'A system where AI decisions are fully automated with no human role', 'An AI assistant embedded in a human-computer interface'], correct: 1, explanation: 'Human-in-the-loop means a human must review, approve, or act on AI outputs before a decision is implemented.' },
    { question: 'In which scenario would "human-out-of-the-loop" AI be most ethically problematic?', options: ['Spam filtering for email', 'Autonomous lethal weapons systems selecting targets', 'Auto-completing text messages', 'Sorting warehouse inventory'], correct: 1, explanation: 'Lethal, irreversible decisions with life-or-death consequences require human accountability; removing the human from the loop in such contexts is widely considered ethically unacceptable.' },
    { question: 'An AI-assisted hiring tool flags a candidate as low-priority. What does "human-on-the-loop" look like in this context?', options: ['The AI rejects the candidate automatically with no human review', 'A recruiter receives the AI\'s ranking and can override it before any candidate is contacted', 'The candidate is informed in real time by the AI', 'A committee votes to approve or reject the AI\'s entire ranked list'], correct: 1, explanation: 'Human-on-the-loop means a person monitors AI outputs and retains override authority, though the AI acts first — different from in-the-loop where human approval precedes action.' },
    { question: 'Why might over-reliance on human oversight be a practical limitation in high-volume AI systems?', options: ['Humans always make worse decisions than AI at scale', 'Reviewing every AI output is infeasible when systems process thousands of decisions per second', 'Human reviewers are legally prohibited from overriding AI in many jurisdictions', 'Oversight adds cost but never improves decision quality'], correct: 1, explanation: 'At scale (e.g. content moderation at social media volume), requiring human review of every decision is operationally impractical, creating pressure to automate.' }
  ],

  9: [
    { question: 'What does the "P" in the PTFC prompting framework stand for?', options: ['Purpose', 'Persona', 'Prompt', 'Parameter'], correct: 1, explanation: 'PTFC stands for Persona, Task, Format, Context — Persona tells the AI what role or expertise to adopt.' },
    { question: 'Why does specifying a format (e.g. "bullet list" or "table") in a prompt improve AI outputs?', options: ['It reduces the computational cost of generating a response', 'It constrains the AI to structure information in a way that matches your specific use case', 'It prevents the AI from using copyrighted material', 'It makes the prompt easier to store in memory'], correct: 1, explanation: 'Specifying format aligns the output structure with how you intend to use it, reducing post-processing and making responses directly usable.' },
    { question: 'A student asks an AI "Tell me about climate change." Which improvement best applies the PTFC framework?', options: ['"Tell me everything about climate change in detail"', '"You are an environmental scientist. Summarise the three main causes of climate change for a 16-year-old in three bullet points."', '"Climate change: write a lot"', '"What is climate change? Be comprehensive."'], correct: 1, explanation: 'The improved prompt specifies Persona (environmental scientist), Task (summarise three causes), Format (three bullet points) and Context (for a 16-year-old).' },
    { question: 'What is "prompt iteration" and why is it valuable?', options: ['Automatically running the same prompt 100 times to average the outputs', 'Systematically refining a prompt based on evaluating earlier outputs to progressively improve quality', 'Copying prompts from an online library rather than writing your own', 'Using AI to generate prompts on your behalf'], correct: 1, explanation: 'Prompt iteration treats prompting as a design process — you evaluate each output, identify what is missing or wrong, and refine accordingly.' }
  ],

  10: [
    { question: 'In most jurisdictions, who currently holds copyright in an image generated entirely by an AI with no human creative input?', options: ['The AI system that generated it', 'The company that built the AI model', 'Nobody — it enters the public domain', 'The user who wrote the prompt'], correct: 2, explanation: 'Courts in the US and UK have ruled that copyright requires human authorship; purely AI-generated works with no human creative contribution cannot be copyrighted.' },
    { question: 'The "stochastic parrot" critique is relevant to AI-generated creative work because it suggests:', options: ['AI systems are too slow to be commercially useful for creative industries', 'AI outputs are novel combinations of existing human work rather than genuinely original creations', 'Creative AI always requires explicit licensing of all source material', 'AI-generated art is indistinguishable from human art'], correct: 1, explanation: 'If LLMs are statistical recombinations of training data, AI "creativity" may be sophisticated remixing of existing human work rather than true originality.' },
    { question: 'Which legal concept refers to using copyrighted material without permission in ways that courts may nonetheless permit, based on purpose and effect?', options: ['Creative commons licensing', 'Fair use / fair dealing', 'Public domain dedication', 'Moral rights waiver'], correct: 1, explanation: 'Fair use (US) and fair dealing (UK/Commonwealth) are exceptions allowing limited use of copyrighted material for purposes like commentary, education, or research.' },
    { question: 'A musician uses an AI trained on existing songs to produce a new track. Which stakeholder group has raised the strongest objections to this practice?', options: ['Streaming platforms', 'Original artists and music publishers concerned about unlicensed training data', 'Podcast producers', 'Radio broadcasters'], correct: 1, explanation: 'Artists and publishers argue that training AI on their music without consent or compensation undermines their livelihoods and violates intellectual property rights.' }
  ],

  11: [
    { question: 'A Goldman Sachs report estimated that generative AI could automate tasks affecting how many jobs globally?', options: ['30 million', '300 million', '3 billion', '30 billion'], correct: 1, explanation: 'Goldman Sachs (2023) estimated generative AI could expose 300 million full-time jobs globally to automation of at least some tasks.' },
    { question: 'The World Economic Forum\'s "centaur model" of future work suggests:', options: ['AI will replace all human knowledge workers within a decade', 'The most productive workers will combine human judgement with AI capabilities', 'Only technical roles will survive widespread automation', 'Human creativity is irrelevant once AI reaches human-level performance'], correct: 1, explanation: 'Like the chess centaur (human + computer), future high-value work will combine irreplaceable human skills (judgement, ethics, creativity) with AI\'s processing power.' },
    { question: 'When using AI for research, "triangulating" a claim means:', options: ['Asking the same AI three times and taking the majority answer', 'Verifying the AI\'s output against multiple independent, authoritative primary sources', 'Using three different AI tools and comparing their answers', 'Checking that the claim appears in at least three Wikipedia articles'], correct: 1, explanation: 'Triangulation means cross-referencing AI-generated claims against independent primary sources (academic papers, official reports) to verify accuracy.' },
    { question: 'Which sector did Goldman Sachs identify as among the MOST exposed to AI-driven task automation?', options: ['Agriculture and forestry', 'Construction and manual trades', 'Administrative and office support roles', 'Emergency services'], correct: 2, explanation: 'Administrative and office support jobs, which involve repetitive information processing, were identified as highly exposed to automation by generative AI.' }
  ],

  12: [
    { question: 'A Wharton Business School study found that professionals using AI with iterative prompting outperformed those without AI by approximately:', options: ['10%', '25%', '40%', '75%'], correct: 2, explanation: 'The Wharton study found that workers using AI with 3+ iterations of prompt refinement achieved outputs roughly 40% better than those without AI assistance.' },
    { question: 'What is the core risk of using AI as a revision partner for academic work without exercising critical judgement?', options: ['AI suggestions are always too formal for academic writing', 'Accepting AI suggestions uncritically can weaken your argument or introduce inaccuracies', 'AI cannot process documents longer than one page', 'Schools can always detect AI-revised work with plagiarism software'], correct: 1, explanation: 'AI revision tools often prioritise fluency over accuracy or logical strength — uncritical acceptance can substitute an AI\'s generic phrasing for your more precise original argument.' },
    { question: 'Which academic integrity principle is most relevant when using AI to revise your own written work?', options: ['Ensuring all sources are in Harvard referencing format', 'Transparency about AI use and ensuring the ideas and arguments remain genuinely your own', 'Not using AI for any part of assessed work under any circumstances', 'Limiting AI use to grammar checking only'], correct: 1, explanation: 'Most academic integrity frameworks require disclosure of AI use and that the intellectual contribution — ideas, argument, analysis — is the student\'s own work.' },
    { question: 'The "iteration mindset" in prompt engineering treats prompting as analogous to:', options: ['Memorising a fixed set of magic commands', 'A design or writing process where multiple drafts progressively improve the output', 'Searching a database with increasingly specific keywords', 'Programming a function with fixed inputs and outputs'], correct: 1, explanation: 'Like drafting and redrafting a piece of writing, the iteration mindset sees each AI output as a draft to evaluate and improve through refined prompts.' }
  ],

  13: [
    { question: 'GANs (Generative Adversarial Networks) create convincing deepfakes through:', options: ['Copying and pasting frames from existing video footage', 'A generator and discriminator network competing until outputs are indistinguishable from real content', 'Rule-based face-swapping using 3D mesh mapping', 'Retrieving the most similar face from a database of images'], correct: 1, explanation: 'GANs use two competing neural networks — a generator creates fakes and a discriminator tries to detect them — training each other until fakes become convincing.' },
    { question: 'What is the "liar\'s dividend" in the context of deepfakes?', options: ['The financial gain made by selling deepfake-generating software', 'The ability for bad actors to dismiss authentic evidence as a deepfake', 'The legal protection journalists have when publishing deepfakes in the public interest', 'Profit made from deepfake content on social media platforms'], correct: 1, explanation: 'The liar\'s dividend is the secondary harm of deepfakes: even real footage can be dismissed as "probably a deepfake," eroding trust in genuine evidence.' },
    { question: 'C2PA (Coalition for Content Provenance and Authenticity) aims to combat deepfakes by:', options: ['Banning all AI image generation tools', 'Embedding cryptographic provenance metadata into media at the point of creation', 'Requiring social media platforms to label all images as AI or human', 'Training classifiers to detect deepfakes after the fact'], correct: 1, explanation: 'C2PA creates a standard for signing media with tamper-evident provenance data at creation, allowing recipients to verify origin and edit history.' },
    { question: 'The SIFT method for evaluating online content stands for:', options: ['Search, Identify, Filter, Trust', 'Stop, Investigate the source, Find better coverage, Trace claims', 'Source, Information, Fact-check, Triangulate', 'Skim, Infer, Flag, Thoroughly check'], correct: 1, explanation: 'SIFT is a lateral reading framework: Stop before sharing, Investigate the source, Find better coverage upstream, Trace claims to their origin.' }
  ],

  14: [
    { question: 'London has approximately how many CCTV cameras, making it one of the most surveilled cities globally?', options: ['94,000', '940,000', '9,400', '9,400,000'], correct: 0, explanation: 'London has an estimated 940,000 CCTV cameras — approximately one for every nine residents — among the highest densities of any city globally.' },
    { question: 'In 2020, Robert Williams became the first US citizen known to be wrongly arrested due to a facial recognition error. The core failure was:', options: ['The system was hacked by criminals to frame him', 'A facial recognition system matched him to a blurry CCTV still; officers arrested him without further verification', 'He was misidentified by a human officer who blamed AI retroactively', 'The AI confused him with a family member who was a suspect'], correct: 1, explanation: 'Detroit police used a facial recognition match from grainy footage as justification for arrest without additional corroborating evidence — a failure of human oversight.' },
    { question: 'The EU AI Act classifies real-time remote biometric identification in public spaces as:', options: ['Minimal risk — permitted without restriction', 'Limited risk — permitted with transparency obligations', 'High risk — permitted with strict safeguards', 'Unacceptable risk — prohibited (with narrow law enforcement exceptions)'], correct: 3, explanation: 'The EU AI Act generally prohibits real-time biometric surveillance in public spaces, treating it as unacceptable risk, with narrow exceptions for serious crime prevention.' },
    { question: 'NIST\'s Face Recognition Vendor Testing (FRVT) found accuracy disparities are particularly pronounced for which demographic group?', options: ['Older white males', 'Younger Black and East Asian women', 'Children under 12 of all ethnicities', 'Middle-aged South Asian men'], correct: 1, explanation: 'NIST found the largest accuracy gaps (up to 100x higher false positive rates) for darker-skinned women — particularly Black and East Asian female faces.' }
  ],

  15: [
    { question: 'Training GPT-3 was estimated to produce approximately how much CO₂?', options: ['55 tonnes', '552 tonnes', '5,520 tonnes', '55,200 tonnes'], correct: 1, explanation: 'Training GPT-3 was estimated to produce around 552 tonnes of CO₂ equivalent — comparable to the lifetime emissions of five average cars.' },
    { question: 'How does a single ChatGPT query compare to a standard Google search in terms of energy consumption?', options: ['About the same energy', 'Approximately 10 times more energy', 'Approximately 100 times more energy', 'Slightly less energy'], correct: 1, explanation: 'Research estimates a ChatGPT query uses roughly 10x the energy of a Google search due to the computational demands of large language model inference.' },
    { question: 'DeepMind\'s GNoME project is cited as an example of AI\'s potential positive environmental impact because it:', options: ['Optimised Google\'s data centre cooling to reduce energy use by 40%', 'Discovered 2.2 million new crystal structures that could accelerate materials science including better batteries', 'Predicted 10-day weather forecasts with greater accuracy than traditional models', 'Identified optimal locations for wind and solar farms globally'], correct: 1, explanation: 'GNoME used AI to predict stable crystal structures at scale, potentially accelerating discovery of materials for solar cells, batteries, and other clean technologies.' },
    { question: 'Beyond carbon emissions, AI data centres have which other significant environmental impact?', options: ['Soil contamination from server manufacturing', 'Enormous freshwater consumption for cooling systems', 'Electromagnetic interference with local wildlife', 'Deforestation for mineral extraction'], correct: 1, explanation: 'Data centres use vast quantities of fresh water for cooling — Google reported using 5.6 billion gallons in 2022 — creating competition with local communities for water resources.' }
  ],

  16: [
    { question: 'Under the EU AI Act, which application is classified as "unacceptable risk" and banned outright?', options: ['AI used in university admissions decisions', 'Social scoring systems that rank citizens based on their behaviour', 'AI-powered customer service chatbots', 'Recommendation algorithms on social media'], correct: 1, explanation: 'The EU AI Act bans "unacceptable risk" uses including social scoring by governments, subliminal manipulation, and (with exceptions) real-time biometric surveillance.' },
    { question: 'The UK\'s approach to AI regulation (as of 2023–24) differs from the EU\'s by:', options: ['Being more restrictive with stricter penalties for violations', 'Favouring a pro-innovation, principles-based approach without a single binding AI law', 'Focusing exclusively on military and defence applications', 'Requiring all AI systems to be certified before deployment'], correct: 1, explanation: 'The UK has opted for a "pro-innovation" approach: directing existing regulators to apply their sector-specific powers to AI rather than creating a new overarching AI law.' },
    { question: 'China\'s national AI strategy includes which distinctive governance feature not present in most Western approaches?', options: ['A total ban on generative AI for consumer use', 'Requiring AI-generated content to carry watermarks and tying providers to state security obligations', 'Mandating open-source release of all AI models', 'Prohibiting foreign AI companies from operating in China'], correct: 1, explanation: 'China requires AI content watermarking, mandates that providers verify user identities, and places AI firms under national security laws — embedding AI governance into state control.' },
    { question: 'Which EU AI Act risk tier applies to AI used in CV screening and job recruitment?', options: ['Minimal risk', 'Limited risk', 'High risk', 'Unacceptable risk'], correct: 2, explanation: 'The EU AI Act classifies AI used in employment decisions (hiring, promotion, task allocation) as high risk, requiring transparency, human oversight, and conformity assessments.' }
  ],

  17: [
    { question: 'In a policy gap analysis for AI use in schools, which comparison is most useful as a benchmark?', options: ['The most permissive policy you can find online', 'Policies from comparable institutions, sector guidance documents, and regulatory frameworks', 'Your own intuition about what seems reasonable', 'Only the school\'s existing acceptable use policy for general IT'], correct: 1, explanation: 'Effective benchmarking draws on policies from peer institutions, official guidance (e.g. government frameworks), and relevant regulation to identify gaps in current practice.' },
    { question: 'When auditing an existing school AI policy, which question is most important to ask first?', options: ['How many pages is the current policy?', 'Does the policy actually reflect how AI is being used in the school right now?', 'Was the policy written by a legal professional?', 'How many staff have signed to say they have read it?'], correct: 1, explanation: 'The first audit question is whether the policy is current — policies quickly become outdated as AI tools evolve, creating a gap between stated rules and actual practice.' },
    { question: 'A "status quo" analysis in policy development refers to:', options: ['Deciding in advance what the final policy should say', 'Documenting the current situation — what AI tools are used, by whom, and under what rules — before drafting changes', 'Surveying students about their opinions on AI', 'Reviewing other countries\' national AI strategies'], correct: 1, explanation: 'Analysing the status quo means mapping the current reality — tools in use, existing rules, gaps and risks — to understand what the policy needs to address.' },
    { question: 'Which data would be most useful when assessing AI-related risks in a school setting?', options: ['The age of the school\'s IT infrastructure', 'Incidents of academic misconduct, data breaches, and student/staff AI use patterns', 'The school\'s Ofsted rating', 'The number of AI-related newspaper articles published this year'], correct: 1, explanation: 'Risk assessment requires evidence about actual harms and near-misses (misconduct, breaches, misuse patterns) to prioritise what a policy needs to address.' }
  ],

  18: [
    { question: 'An effective acceptable use policy for AI should include which of the following?', options: ['A list of every AI tool that will ever exist', 'Clear definitions, permitted uses, prohibited uses, and consequences for violations', 'Only restrictions — no guidance on permitted uses', 'Technical specifications for how AI models work'], correct: 1, explanation: 'A robust AUP balances clarity (definitions, permitted and prohibited uses) with accountability (consequences), giving users clear guidance on expected behaviour.' },
    { question: 'Why is it important to involve students in drafting a school AI acceptable use policy?', options: ['Students are legally required to co-author school policies', 'Student involvement increases ownership, surfaces real use cases, and produces more effective and fair policies', 'It reduces the time needed to write the policy', 'Students can provide technical expertise that teachers lack'], correct: 1, explanation: 'Participatory policy-making builds buy-in, ensures the policy addresses actual student behaviour, and develops students\' own understanding of responsible AI use.' },
    { question: 'Which scenario illustrates a conflict between "innovation" and "safeguarding" in an AI acceptable use policy?', options: ['Deciding whether to buy new computers for the school', 'Allowing students to use AI writing tools which boost engagement but may enable academic dishonesty', 'Choosing between two different brands of firewall', 'Deciding how to run parent information evenings about technology'], correct: 1, explanation: 'AI writing tools exemplify the tension: they may genuinely help struggling writers (innovation/access benefit) while also enabling submitting AI work as one\'s own (safeguarding risk).' },
    { question: 'What does "proportionality" mean in the context of AI policy enforcement?', options: ['All violations should receive the same punishment regardless of severity', 'Consequences should be calibrated to the seriousness of the violation and the student\'s intent', 'Policies only need to address the most serious possible misuses', 'Enforcement should be automatic and not involve human judgement'], correct: 1, explanation: 'Proportional enforcement means minor unintentional violations (e.g. accidentally using AI without disclosure) are treated differently from deliberate academic fraud.' }
  ],

  19: [
    { question: 'Which feature of formal policy language distinguishes it from informal guidance?', options: ['It uses shorter sentences', 'It uses precise, defined terms; modal verbs (must/shall/may); and numbered provisions', 'It avoids any reference to specific technologies', 'It is written in the first person'], correct: 1, explanation: 'Formal policy language uses precisely defined terms, mandatory ("must/shall") vs permissive ("may") language, and numbered provisions to avoid ambiguity.' },
    { question: 'An enforcement mechanism in a policy document serves what purpose?', options: ['It explains the technical details of AI systems covered by the policy', 'It specifies how violations will be identified, investigated, and what consequences will follow', 'It lists the names of people responsible for writing the policy', 'It provides a glossary of technical terms'], correct: 1, explanation: 'Without enforcement mechanisms (who monitors compliance, what investigation looks like, what sanctions apply), a policy has no teeth — it becomes aspirational rather than effective.' },
    { question: 'In policy drafting, a "scope" clause is used to:', options: ['Summarise the history of AI regulation', 'Define exactly who and what the policy applies to — and critically, what it does not cover', 'List all the AI tools currently in use at the organisation', 'Explain the ethical principles behind the policy'], correct: 1, explanation: 'The scope clause sets boundaries: which people, systems, and activities the policy covers, and which fall outside it — essential for avoiding ambiguity in application.' },
    { question: 'Why should a school AI policy include a review clause specifying when it will next be updated?', options: ['It is a legal requirement under GDPR', 'AI technology evolves rapidly; without scheduled reviews, policies quickly become outdated and unenforceable', 'Review clauses make policies look more professional', 'It allows the school to avoid responsibility during the review period'], correct: 1, explanation: 'AI capabilities change faster than most policy cycles — a review clause ensures the policy remains current, relevant, and enforceable as new tools emerge.' }
  ],

  20: [
    { question: 'In a simulated school policy ratification process, what is the purpose of a deliberative debate before voting?', options: ['To delay the vote until all disagreements disappear', 'To allow competing arguments to be heard and scrutinised so the vote is informed rather than arbitrary', 'To give teachers more time to write their own alternative policies', 'To ensure the most popular student\'s policy always wins'], correct: 1, explanation: 'Deliberative debate surfaces tradeoffs and challenges, enabling participants to make a more informed, considered vote rather than reacting to initial impressions.' },
    { question: 'When presenting a policy proposal, which rhetorical strategy is most effective at the opening?', options: ['Immediately reading out every clause of the policy', 'Opening with a concrete, relatable scenario that illustrates the problem your policy solves', 'Starting with a detailed explanation of how AI works technically', 'Criticising all competing policy proposals first'], correct: 1, explanation: 'A concrete opening scenario makes the problem vivid and personally relevant to your audience before introducing your solution — a classic persuasive structure.' },
    { question: 'A policy amendment proposed during debate should be evaluated on which primary criterion?', options: ['Whether it makes the policy longer', 'Whether it improves the policy\'s effectiveness, clarity, or fairness without undermining its core purpose', 'Whether the person proposing it is senior to the original author', 'Whether it has been tested at another institution first'], correct: 1, explanation: 'Amendments should be judged on their merits — whether they strengthen the policy — not on who proposes them or procedural factors.' },
    { question: 'After a class votes to ratify an AI policy, what is the most important next step for the policy to have real impact?', options: ['Filing it in a policy folder and not mentioning it again', 'Communicating it clearly to all stakeholders and establishing who is responsible for implementation', 'Publishing it on the school website for legal protection', 'Sending it to the local council for approval'], correct: 1, explanation: 'Ratification is only the start — a policy only works if stakeholders know about it, understand it, and someone is accountable for ensuring it is followed.' }
  ],

  21: [
    { question: 'What is the key mindset shift described in the transition from "consumer to co-creator" of AI tools?', options: ['Accepting AI outputs without questioning them', 'Moving from passively using AI products to actively shaping how AI solves real problems', 'Learning to code neural networks from scratch', 'Avoiding AI tools and relying on traditional methods'], correct: 1, explanation: 'The co-creator mindset means you define the problem, design the solution, and use AI as a tool — rather than simply consuming whatever AI produces.' },
    { question: 'A good capstone project problem statement should be:', options: ['As broad as possible to allow maximum flexibility', 'Specific, scoped, and testable — with clear success criteria', 'Chosen by the teacher to ensure quality', 'Based on an existing commercial AI product'], correct: 1, explanation: 'A focused problem statement with measurable success criteria keeps the project manageable and makes it possible to evaluate whether the solution actually works.' },
    { question: 'Which of the following is the best example of a capstone project suitable for this course?', options: ['Recreating GPT-4 from scratch', 'Building a prompt-based tool that helps KS3 students revise for science tests using AI feedback', 'Redesigning Instagram\'s recommendation algorithm', 'Writing a 10,000-word essay about AI history'], correct: 1, explanation: 'Good capstone projects are realistic in scope, solve a real problem for a real audience, and use AI tools (like prompting) rather than requiring advanced ML engineering.' },
    { question: 'Why is it valuable to present your capstone project to an audience who did not help build it?', options: ['It is a legal requirement for school assessments', 'External audiences surface assumptions you didn\'t know you were making and test whether your tool is genuinely usable', 'It motivates you to make the project look better aesthetically', 'Teachers are not qualified to evaluate technical AI projects alone'], correct: 1, explanation: 'Presenting to fresh eyes reveals gaps in explanation, assumptions baked into the design, and usability issues invisible to the creator.' }
  ],

  22: [
    { question: 'Which element transforms a vague project idea into a strong problem statement?', options: ['Adding more detail about AI technology', 'Specifying who is affected, what the problem is, and why existing solutions are inadequate', 'Using technical jargon to sound credible', 'Identifying a problem that has already been solved elsewhere'], correct: 1, explanation: 'A strong problem statement names the stakeholder, defines the specific gap or pain point, and explains why current approaches fail to address it.' },
    { question: 'Success criteria for an AI project should ideally be:', options: ['Defined after the project is built so you know what worked', 'Set before building so you can objectively evaluate whether you achieved your goal', 'Vague enough to allow flexibility throughout development', 'Focused exclusively on technical performance metrics'], correct: 1, explanation: 'Pre-defined success criteria prevent post-hoc rationalisation ("it worked because we changed what success meant") and give you objective evaluation benchmarks.' },
    { question: '"Problem validation" means:', options: ['Getting a teacher to confirm your problem statement is grammatically correct', 'Verifying that the problem genuinely exists and matters to real users before investing time in a solution', 'Testing your solution on a small group', 'Checking that no AI solution for the problem already exists'], correct: 1, explanation: 'Validating the problem before building prevents wasting effort on solutions to problems that either don\'t exist at the scale you assumed or don\'t matter to your target users.' },
    { question: 'A student says "I want to build an AI that helps everyone with everything." What is the main problem with this?', options: ['It is technically impossible', 'It is too vague to build, test, or evaluate — there is no specific problem or user', 'It would require a commercial AI licence', 'It is not original enough'], correct: 1, explanation: 'Without a specific problem and specific user, you cannot define scope, measure success, or make design decisions — the statement needs to be narrowed significantly.' }
  ],

  23: [
    { question: '"Ethics by design" means:', options: ['Adding an ethics section to your project report after building', 'Considering potential harms and building safeguards into the design from the start', 'Getting ethical approval from a committee before coding', 'Avoiding any AI application that could be misused'], correct: 1, explanation: 'Ethics by design integrates harm prevention into the design process itself, rather than adding ethical review as an afterthought once the product is complete.' },
    { question: 'Which question is most important to ask during the harm identification phase of an AI project?', options: ['Will this make money?', 'Who could be harmed, excluded, or disadvantaged by this system — and how?', 'Has this exact tool been built before?', 'What programming language should I use?'], correct: 1, explanation: 'Proactively asking "who could be harmed?" forces designers to consider unintended impacts on all stakeholders, not just the intended users.' },
    { question: 'A student builds a homework helper AI. What safeguard best addresses the risk of students submitting AI output as their own work?', options: ['Making the tool free to use', 'Designing the tool to provide hints and explanations rather than complete answers, prompting the student to think', 'Adding a warning message that students should not cheat', 'Requiring students to type rather than copy-paste'], correct: 1, explanation: 'Tool design that scaffolds thinking (hints, explanations, follow-up questions) rather than providing direct answers reduces misuse risk at the design level.' },
    { question: 'Which stakeholder is most commonly overlooked in AI project ethics reviews?', options: ['The developer', 'The primary intended user', 'Indirect third parties who may be affected by the tool\'s outputs', 'The teacher assessing the project'], correct: 2, explanation: 'AI systems often impact people beyond direct users — e.g. a hiring tool affects candidates who never interact with it; overlooking third-party stakeholders is a common design failure.' }
  ],

  24: [
    { question: 'Sprint-based planning in a capstone project means:', options: ['Working as fast as possible without planning', 'Breaking the project into short, focused work periods with specific goals and review points', 'Competing against classmates to finish first', 'Completing all planning before writing a single line of code'], correct: 1, explanation: 'Sprints (from agile methodology) are time-boxed periods focused on specific deliverables, with review and adaptation at the end of each cycle.' },
    { question: 'What is the purpose of a technical architecture diagram in a project plan?', options: ['To impress the examiner with complexity', 'To map how components, data, and user interactions connect — making dependencies and risks visible before building', 'To provide detailed code for each module', 'To replace the need for a written project plan'], correct: 1, explanation: 'An architecture diagram externalises the system\'s structure, revealing dependencies and potential bottlenecks before they become problems during build.' },
    { question: 'Why should milestones be set for a capstone project rather than just a final deadline?', options: ['Milestones allow teachers to give partial marks', 'They create checkpoints to catch problems early and ensure steady progress rather than a last-minute rush', 'They are required by examination boards', 'Milestones make the project look more professional in the portfolio'], correct: 1, explanation: 'Milestones force regular progress checks — if you\'re behind at milestone 2, you can adjust scope or approach; without them, problems only surface at the end.' },
    { question: 'When estimating how long a task will take during project planning, the best approach is to:', options: ['Assume everything will go smoothly and estimate optimistically', 'Double your initial estimate and add buffer for unknowns', 'Ask the AI to predict how long it will take', 'Only estimate tasks you have done before'], correct: 1, explanation: 'Project management research consistently shows that task durations are underestimated; adding contingency buffer is standard practice to account for unknowns.' }
  ],

  25: [
    { question: 'A "prompt library" in a production AI project is:', options: ['A collection of books about prompt engineering', 'A version-controlled set of tested, documented prompts used consistently across a project', 'A database of training examples for fine-tuning', 'The AI model\'s internal memory of previous conversations'], correct: 1, explanation: 'A prompt library ensures consistent, tested prompts are reused rather than recreated each time — essential when multiple prompts power different features.' },
    { question: 'What does "systematic prompt testing" involve in a production context?', options: ['Running a prompt once and accepting the first output', 'Testing prompts against a range of representative inputs and edge cases, documenting outputs and failures', 'Using the longest prompt possible to cover all scenarios', 'Asking multiple people to rate which version they prefer'], correct: 1, explanation: 'Systematic testing means defining test cases (including edge cases), running prompts against them, and documenting results — treating prompts with the same rigour as code.' },
    { question: 'Why might a prompt that works well in development fail in production?', options: ['The AI model is updated without notice', 'Production inputs from real users are more varied and unpredictable than the developer\'s test cases', 'Production servers have different AI models than development environments', 'Users intentionally try to break AI systems'], correct: 1, explanation: 'Real users phrase things unexpectedly, provide incomplete inputs, or use the tool in ways not anticipated during development — production conditions are always more varied.' },
    { question: 'Which PTFC element is most important to specify when building a customer-facing AI tool with a consistent brand voice?', options: ['Task — to ensure the AI always answers the same type of question', 'Persona — to give the AI a consistent tone, style, and domain expertise', 'Format — to control the length of responses', 'Context — to prevent the AI from discussing competitors'], correct: 1, explanation: 'Persona defines the AI\'s voice, expertise, and boundaries — critical for brand consistency and appropriate scope in customer-facing applications.' }
  ],

  26: [
    { question: 'A logic flow diagram for an AI tool is most useful for:', options: ['Showing the neural network architecture of the underlying model', 'Mapping decision points, user inputs, and AI outputs so edge cases can be identified before building', 'Demonstrating to investors how the product works', 'Replacing written documentation'], correct: 1, explanation: 'Logic flows externalise the system\'s decision structure, making it possible to trace what happens in each scenario and spot missing branches or unhandled inputs.' },
    { question: 'What is an "edge case" in software and AI development?', options: ['A feature that is added at the last minute', 'An input or scenario at the boundary of expected use that may cause unexpected behaviour', 'A calculation that produces a number larger than expected', 'A user who does not follow the intended workflow'], correct: 1, explanation: 'Edge cases are boundary conditions or unusual inputs that the system was not primarily designed for — they are common sources of failures if not explicitly handled.' },
    { question: 'Why is error handling particularly important in AI-powered tools compared with traditional software?', options: ['AI tools are inherently more expensive to fix when they break', 'AI outputs are probabilistic and may be confidently wrong, so the system needs fallbacks for failure modes', 'Traditional software cannot produce errors', 'AI tools run slower, so errors cause longer delays'], correct: 1, explanation: 'Unlike deterministic software, AI can produce wrong outputs with high apparent confidence — error handling must account for hallucinations, misunderstood inputs, and out-of-scope queries.' },
    { question: 'Which approach best handles an edge case where a user asks an AI homework tool a question completely outside its intended scope?', options: ['Have the AI answer anyway to be helpful', 'Design a fallback response that politely declines and redirects to the tool\'s purpose', 'Crash the application to signal an error', 'Log the query and ignore it'], correct: 1, explanation: 'Graceful degradation — a polite, clear refusal that explains what the tool is for — prevents scope creep, misuse, and confusing outputs outside the tool\'s competence.' }
  ],

  27: [
    { question: 'During deep work sprint sessions, which practice best maintains project momentum?', options: ['Switching between tasks frequently to stay stimulated', 'Beginning each session by reviewing what was completed last time and what the specific goal for this session is', 'Waiting until inspiration strikes before starting', 'Working alone without any peer feedback until the project is complete'], correct: 1, explanation: 'Starting each session with a clear review of progress and a specific goal prevents wasted time re-establishing context and keeps work focused.' },
    { question: 'In iterative AI tool development, what should you do when your AI produces unexpectedly poor outputs during a sprint?', options: ['Abandon that feature entirely', 'Document the failure case, analyse what caused it, and refine the prompt or design', 'Switch to a different AI model immediately', 'Accept the output and move to the next feature'], correct: 1, explanation: 'Failure during development is valuable signal — documenting and analysing it improves the tool and produces evidence of critical evaluation for your portfolio.' },
    { question: 'Which type of documentation is most valuable to maintain during sprint-based development?', options: ['A complete technical manual written at the end', 'Running notes on decisions made, problems encountered, and how they were resolved', 'A daily word count of code written', 'Marketing copy describing the finished product'], correct: 1, explanation: 'Incremental decision logs capture the "why" behind design choices — essential for evaluation, viva defence, and avoiding repeating mistakes.' },
    { question: 'Why is testing your AI tool with users outside your immediate group important during build sprints?', options: ['External testers are always more technically skilled', 'They reveal usability issues and misunderstandings invisible to creators who know the tool too well', 'It is a formal requirement of agile methodology', 'External users provide better qualitative feedback than peers'], correct: 1, explanation: 'Creators have "curse of knowledge" — they know how the tool is supposed to work and unconsciously work around its problems. External testers use it naively and surface real issues.' }
  ],

  28: [
    { question: 'During a build sprint, what should you do if you realise your original design is not technically achievable in the time available?', options: ['Abandon the project entirely', 'Descope to a smaller, achievable version and document the original ambition as future work', 'Ask the teacher to extend the deadline', 'Keep building the original plan and hope for the best'], correct: 1, explanation: 'Controlled descoping — delivering a smaller working version — is a professional project management skill; shipping something useful beats not shipping an ambitious failure.' },
    { question: 'What is "version control" and why is it important during an AI build project?', options: ['Keeping track of which version of the AI model you are using', 'Saving incremental snapshots of your work so you can revert to an earlier state if something breaks', 'Numbering your slides to keep them in order', 'Ensuring your project uses the latest available AI tools'], correct: 1, explanation: 'Version control (e.g. Git) lets you roll back to a working state after a breaking change — essential when experimenting with prompts or code changes.' },
    { question: 'Peer code or prompt review during a sprint is valuable because:', options: ['It transfers responsibility to the reviewer if something goes wrong', 'A second pair of eyes spots logical errors, unclear prompts, and missed edge cases you have become blind to', 'It slows down development and should be avoided under time pressure', 'Only the strongest developer\'s opinions should influence the project'], correct: 1, explanation: 'Review by someone who hasn\'t been staring at the same prompt for hours brings fresh perspective and catches issues the creator normalised.' },
    { question: 'Which activity best belongs in a sprint retrospective at the end of a build session?', options: ['Starting to build the next feature immediately', 'Reflecting on what worked well, what slowed you down, and what you will do differently next sprint', 'Presenting your project to the class', 'Rewriting your problem statement from scratch'], correct: 1, explanation: 'Sprint retrospectives are structured reflection — capturing lessons learned while they\'re fresh so the next sprint is more efficient.' }
  ],

  29: [
    { question: 'When your AI tool produces an output that is factually correct but misses the user\'s intent, what should you adjust?', options: ['The underlying AI model', 'The context or task component of your prompt to better specify what "success" looks like', 'The user interface colours', 'The programming language you are using'], correct: 1, explanation: 'Intent mismatches are usually prompt problems — the AI wasn\'t told enough about what you actually need; adding context or a concrete example typically resolves it.' },
    { question: 'In iterative product development, a "minimum viable product" (MVP) is:', options: ['The least effort version you can get away with', 'The simplest version that delivers the core value proposition and can be tested with real users', 'A legal requirement before releasing software', 'A version with all features but not yet tested'], correct: 1, explanation: 'An MVP is the smallest useful thing you can build — it validates core assumptions with real users before investing in additional features.' },
    { question: 'You test your AI homework helper with three students and all three ask the same question it cannot answer. What should you do?', options: ['Remove those students from your test group', 'Treat this as a confirmed gap and redesign the prompt or scope to handle it', 'Tell the students they are using the tool incorrectly', 'Note it as a minor edge case and move on'], correct: 1, explanation: 'Consistent failure across multiple users confirms a real design gap, not a one-off edge case — it warrants a design response, not rationalisation.' },
    { question: 'Why is it important to keep a log of prompt changes during development?', options: ['To prove to the teacher you worked hard', 'To track what changed between versions so you can understand why outputs improved or worsened', 'Prompt logs are automatically saved by AI tools', 'It helps the AI remember your previous prompts'], correct: 1, explanation: 'Without a change log, you lose the ability to trace which specific change caused which improvement — making it impossible to replicate success intentionally.' }
  ],

  30: [
    { question: 'When testing an AI tool with a diverse group of users, why does diversity matter?', options: ['Diverse groups generate more feedback overall', 'Different users have different needs, language patterns, and contexts — testing only a homogeneous group may miss failures for underrepresented users', 'Diverse testers are harder to please and improve overall quality', 'It satisfies equality requirements for school projects'], correct: 1, explanation: 'An AI tool may work well for some demographics and fail others — diverse testing is the only way to surface biases or accessibility issues before deployment.' },
    { question: 'Usability testing for an AI tool should measure:', options: ['Only whether the technical output is factually correct', 'Whether real users can achieve their goal with the tool without external help or confusion', 'How impressed users are with the technology', 'Whether the tool is faster than Google Search'], correct: 1, explanation: 'Usability testing focuses on whether users can independently achieve their goals — uncovering where they get stuck, confused, or misunderstand what the tool does.' },
    { question: 'A student\'s AI revision tool is tested and works well for students who are already confident in the subject but confuses struggling students. This is an example of:', options: ['A successful product that only needs minor polish', 'A design that serves its primary audience (struggling learners) poorly — the group who needs it most', 'Normal variation in user ability that cannot be designed around', 'An AI hallucination problem'], correct: 1, explanation: 'If a revision tool fails the students who most need it, the tool has failed its core purpose — this is a fundamental design problem requiring redesign, not polish.' },
    { question: 'After gathering user feedback, how should you prioritise which issues to fix in your remaining sprint time?', options: ['Fix the easiest issues first to show lots of improvements', 'Prioritise by impact on core user goals and frequency across testers', 'Fix issues in the order users mentioned them', 'Only fix issues that your teacher also identified'], correct: 1, explanation: 'High-impact, frequently-reported issues affect the most users most severely — prioritising these maximises the improvement to your tool within limited time.' }
  ],

  31: [
    { question: 'Documentation for an AI project should explain which of the following?', options: ['Only the code syntax used', 'How to use the tool, what it is designed to do, its limitations, and how it was built', 'The full biography of each team member', 'Every conversation you had with your AI during development'], correct: 1, explanation: 'Good documentation enables someone who didn\'t build the project to understand its purpose, use it correctly, and know its limitations — essential for handover and evaluation.' },
    { question: 'What is the purpose of a "user guide" in a student AI project?', options: ['It proves the project is complete enough to submit', 'It helps real users understand how to interact with the tool correctly and what to do if something goes wrong', 'It provides a detailed technical explanation for the examiner', 'It replaces the need for a pitch presentation'], correct: 1, explanation: 'A user guide bridges the gap between the tool\'s capabilities and a new user\'s understanding — without it, even a well-designed tool may be unusable in practice.' },
    { question: 'In your project portfolio, reflecting on what you would do differently next time demonstrates:', options: ['That the project failed', 'Critical self-evaluation — a high-level skill that distinguishes excellent from good student work', 'That you did not plan adequately', 'Weakness that examiners will penalise'], correct: 1, explanation: 'Genuine critical reflection shows you can evaluate your own work honestly and extract learning — a marker of sophisticated thinking that examiners reward.' },
    { question: 'Which sprint artefact is most useful to include in your final project portfolio?', options: ['Screenshots of every AI conversation you had', 'Selected prompt iterations with commentary explaining why each change was made and what improved', 'A complete list of all AI tools you considered but didn\'t use', 'The full unedited transcript of all user testing sessions'], correct: 1, explanation: 'Annotated prompt iterations show your design thinking process — they demonstrate iteration, critical evaluation, and improvement rather than simply showing a finished product.' }
  ],

  32: [
    { question: 'When integrating multiple AI prompts into a single tool workflow, what is the most important thing to verify?', options: ['That each prompt is as long as possible', 'That the output of each prompt is in the right format to serve as input for the next stage', 'That all prompts use the same AI model', 'That no prompt repeats any instructions from a previous one'], correct: 1, explanation: 'In multi-step AI pipelines, output format consistency between stages prevents failures where one step produces something the next cannot process.' },
    { question: 'A student uses five separate AI prompts that each work individually but produce inconsistent outputs when chained together. The most likely cause is:', options: ['The AI model has a bug', 'Each prompt lacks context about what came before, causing inconsistent framing and tone', 'The internet connection is too slow', 'The prompts are too short'], correct: 1, explanation: 'Without shared context, each prompt call starts fresh — inconsistencies arise because the AI doesn\'t know the overall goal or the tone established by previous responses.' },
    { question: 'What does "graceful degradation" mean in an AI-powered tool?', options: ['The tool becomes slower over time as it processes more data', 'When the AI fails or is uncertain, the tool handles this cleanly rather than crashing or producing harmful outputs', 'The UI design becomes simpler on slower devices', 'The AI reduces its output quality to save computing costs'], correct: 1, explanation: 'Graceful degradation means designing explicit fallback behaviours for AI failures — e.g. showing a "I can\'t help with that" message rather than an error screen or hallucinated response.' },
    { question: 'Why is it important to test your AI tool with unusual or adversarial inputs?', options: ['To demonstrate technical skill to the examiner', 'To discover failure modes before users do — inputs designed to break, confuse, or misuse the system', 'Because examiners always test AI tools adversarially', 'To prove the AI cannot be jailbroken'], correct: 1, explanation: 'Real users will inevitably input unexpected things — testing adversarially before deployment reveals edge cases and safety gaps while you can still fix them.' }
  ],

  33: [
    { question: 'What is the purpose of a "sprint review" in a capstone project?', options: ['A formal examination of the project by an external panel', 'A structured session to demonstrate what was built in the sprint and gather feedback before the next sprint begins', 'A review of the project rules and assessment criteria', 'A chance to restart the project if the sprint went badly'], correct: 1, explanation: 'Sprint reviews create accountability and feedback loops — you show your progress, get input, and use it to prioritise the next sprint.' },
    { question: 'Which factor most often distinguishes excellent final AI projects from average ones?', options: ['Using more advanced AI models', 'Evidence of iteration — showing how the project evolved in response to feedback and testing', 'Having more features than other projects', 'A more visually polished presentation slide deck'], correct: 1, explanation: 'Examiners reward evidence of a design-test-reflect cycle; a simple tool with clear iterations and honest evaluation often outscores a complex tool with no visible development process.' },
    { question: 'When presenting your build process, what should you include alongside screenshots of your final product?', options: ['Only the positive results and smooth iterations', 'Examples of what went wrong, why it went wrong, and how you addressed it', 'The complete history of every AI output generated', 'Testimonials from friends who used the tool'], correct: 1, explanation: 'Showing failures and how you responded to them demonstrates the genuine design process and critical thinking that examiners are looking for — not just a polished end state.' },
    { question: 'Finishing a build sprint with a half-built feature is best handled by:', options: ['Leaving it in the project and hoping the examiner doesn\'t notice', 'Disabling the unfinished feature and documenting it as planned future work', 'Starting over from scratch', 'Submitting the project without that component and not mentioning it'], correct: 1, explanation: 'A clearly scoped tool that works reliably is better than one with broken features — documenting unfinished work as future development shows honest project management.' }
  ],

  34: [
    { question: 'An ethical audit of an AI project should include which of the following?', options: ['Only positive outcomes and achievements', 'A systematic review of potential harms, who is affected, and what mitigations are in place', 'A comparison with competitor products', 'A legal compliance checklist only'], correct: 1, explanation: 'A thorough ethical audit maps harms, affected stakeholders, existing safeguards, and remaining risks — honest about limitations, not just a showcase of positives.' },
    { question: 'When documenting risks in an ethical audit, what should accompany each risk identified?', options: ['A disclaimer stating you are not responsible for misuse', 'A probability/impact assessment and the specific mitigation steps taken or proposed', 'A legal citation showing the risk is permitted', 'Evidence that no similar product has faced this risk'], correct: 1, explanation: 'Each risk needs context (how likely, how serious) and a clear mitigation — without mitigations, the audit is just a list of problems rather than a responsible design document.' },
    { question: 'A student\'s AI project helps users write cover letters. Which risk should their ethical audit prioritise?', options: ['The risk that the tool will make too much money', 'The risk that outputs homogenise applicant voices, disadvantage non-native English speakers, or enable fraudulent applications', 'The risk that the tool uses too much computing power', 'The risk that the interface is not visually appealing'], correct: 1, explanation: 'Cover letter tools risk homogenising authentic voices, creating unfair advantages, and enabling identity misrepresentation — all significant ethical concerns worth auditing.' },
    { question: 'Why should an ethical audit be completed before the final presentation, not after?', options: ['The examination board requires it to be submitted first', 'It may reveal issues that require changes to the design — completing it after the build locks in those problems', 'It is easier to write when you are tired from presenting', 'Post-build audits are never valid'], correct: 1, explanation: 'An audit only adds value if its findings can inform design changes; completing it at the end makes it a retrospective box-tick rather than a genuine design tool.' }
  ],

  35: [
    { question: 'The most effective opening for a capstone pitch is:', options: ['A detailed technical explanation of how your AI model works', 'A compelling hook — a question, statistic, or short scenario that makes the problem feel real and urgent', 'Reading your project brief aloud', 'Showing your code editor with the project open'], correct: 1, explanation: 'Pitches win or lose on the first 60 seconds — a concrete, vivid hook establishes why the problem matters before you explain your solution.' },
    { question: 'When communicating a technical AI concept to a non-technical audience, the most effective strategy is:', options: ['Using correct technical terminology throughout to sound credible', 'Using an analogy that maps the concept onto something familiar from everyday life', 'Avoiding any explanation and directing them to the documentation', 'Showing the source code so they can see it works'], correct: 1, explanation: 'Analogies bridge the gap between new technical concepts and existing understanding — they enable non-technical audiences to grasp the idea without requiring technical background.' },
    { question: 'The "problem-solution" structure in a pitch means:', options: ['Explaining the problem for 80% of the pitch and rushing the solution', 'Clearly establishing the problem and why it matters before presenting your tool as the specific answer to it', 'Listing all possible solutions before settling on yours', 'Presenting your solution first, then explaining what problem it solves'], correct: 1, explanation: 'Establishing the problem first creates the need your solution then satisfies — audiences are far more receptive to solutions when they already feel the problem.' },
    { question: 'Which slide should appear in every capstone pitch deck?', options: ['A competitor comparison table', 'A "what\'s next?" slide showing limitations and potential improvements', 'A financial projection', 'A technical architecture diagram'], correct: 1, explanation: 'A "what\'s next / limitations" slide demonstrates critical self-awareness and intellectual honesty — examiners expect you to know what your project doesn\'t do yet.' }
  ],

  36: [
    { question: 'During a dress rehearsal, which type of feedback is most valuable to prioritise?', options: ['Positive feedback about what you did well', 'Specific, actionable feedback about what was unclear, unconvincing, or missing', 'Feedback about your visual slides\' colour scheme', 'Feedback from people who know your project best'], correct: 1, explanation: 'Actionable feedback — "I didn\'t understand why you chose X over Y" — is what you can act on to improve. General praise or minor aesthetic notes are lower priority.' },
    { question: 'When practising responses to panel Q&A, which strategy best prepares you for unexpected questions?', options: ['Memorising answers to the ten most likely questions', 'Practising explaining your design decisions out loud to someone unfamiliar with your project', 'Refusing to answer questions you haven\'t prepared for', 'Focusing only on technical questions'], correct: 1, explanation: 'Explaining your project to a non-expert out loud exposes gaps in your understanding and practises real-time articulation better than memorised answers.' },
    { question: 'If you are asked a question during a presentation that you genuinely do not know the answer to, the best response is:', options: ['Making up a plausible-sounding answer', 'Acknowledging you don\'t know, explaining what you do know, and offering to find out', 'Changing the subject immediately', 'Saying the question is out of scope for your project'], correct: 1, explanation: 'Honest acknowledgement of uncertainty, paired with what you do know, demonstrates intellectual integrity. Fabricating an answer risks being caught and damages credibility far more.' },
    { question: 'Why is timed rehearsal (practising with a stopwatch) important before a final presentation?', options: ['It trains you to speak faster', 'It reveals whether you are over or under the time limit so you can adjust depth and pacing', 'It is required by examiners as part of the assessment', 'It reduces nerves more than any other technique'], correct: 1, explanation: 'Untimed rehearsals consistently produce presentations that are too long or too short when the actual deadline is applied — timing reveals pacing issues before they cost marks.' }
  ],

  37: [
    { question: 'When presenting your capstone project to a panel, what is the most important thing to do in your opening 60 seconds?', options: ['Explain every technical decision you made', 'Establish the problem and why it matters before introducing your solution', 'Apologise for any limitations in the project', 'Read your project brief word for word'], correct: 1, explanation: 'Panels need to feel the problem is real and significant before they care about your solution — context first, solution second.' },
    { question: 'A panel member asks "why didn\'t you consider X approach?" The best response is:', options: ['Saying you didn\'t have time', 'Explaining the trade-off you considered and why you chose differently — or honestly acknowledging it as a gap', 'Arguing that X would not have worked without explaining why', 'Redirecting to a different aspect of your project'], correct: 1, explanation: 'Demonstrating you weighed options (even imperfectly) shows design thinking; honest acknowledgement of gaps is far better than bluffing.' },
    { question: 'Why is it important to stay within your allotted presentation time?', options: ['Going over time is a legal violation in examinations', 'Overrunning cuts into Q&A time, signals poor preparation, and may frustrate panel members marking on time discipline', 'Panel members always stop listening after the allotted time', 'Shorter presentations always score higher marks'], correct: 1, explanation: 'Time management in a presentation is itself assessed — overrunning suggests you couldn\'t prioritise what matters most about your project.' },
    { question: 'After your presentation, a panel member gives critical feedback. The appropriate response is:', options: ['Defending your original decisions without acknowledging the feedback', 'Listening carefully, acknowledging the point, and engaging thoughtfully with the critique', 'Agreeing with everything they say regardless of whether you believe it', 'Asking them to repeat the question to buy time'], correct: 1, explanation: 'Engaging genuinely with critique — even when you disagree — demonstrates intellectual maturity and the ability to learn from feedback.' }
  ],

  38: [
    { question: 'During a panel Q&A, you are asked a question you did not prepare for. The best approach is:', options: ['Making up a confident-sounding answer', 'Taking a moment to think, then giving your honest best answer — flagging uncertainty where it exists', 'Saying "that is not relevant to my project"', 'Asking the panel member to answer their own question'], correct: 1, explanation: 'Genuine engagement with unexpected questions — including flagging uncertainty — is more impressive than polished answers to scripted questions.' },
    { question: 'What does "responding to the panel" require beyond just answering questions?', options: ['Using technical terminology to demonstrate expertise', 'Reading the room — adjusting depth and language based on what the panel seems to need more or less of', 'Keeping all answers to exactly 30 seconds', 'Repeating key points from your presentation in your answers'], correct: 1, explanation: 'Effective panel responses are dialogic — you read cues about whether the panel wants more detail, a simpler explanation, or a different angle.' },
    { question: 'If two panel members disagree in their questions — one wants more safeguards, one thinks you over-restricted the tool — how should you respond?', options: ['Agree with whichever panel member seems more senior', 'Acknowledge the genuine tension, explain your design rationale, and note it as an area of ongoing debate', 'Ignore one question and only answer the other', 'Ask the panel to resolve their disagreement before you answer'], correct: 1, explanation: 'Real design involves genuine trade-offs — showing you understand the tension and made a considered choice is exactly the analytical skill being assessed.' },
    { question: 'Which type of question at panel presentations most often catches students unprepared?', options: ['Questions about the technical details of the AI model used', 'Questions about ethical implications or who could be harmed by the tool', '"What would you do differently?" questions', 'Questions about the presentation slides\' visual design'], correct: 2, explanation: '"What would you do differently?" requires genuine critical self-reflection — students who only prepared to defend their work often struggle with honest self-evaluation questions.' }
  ],

  39: [
    { question: 'A viva voce examination tests which skill that a written submission cannot?', options: ['The ability to write clearly under time pressure', 'The ability to articulate, defend, and extend your ideas in real-time dialogue', 'The depth of your literature review', 'Your ability to format references correctly'], correct: 1, explanation: 'A viva tests genuine understanding — you cannot rely on a polished draft; you must demonstrate live that the ideas are truly yours and you can engage with challenges.' },
    { question: 'If you are asked in a viva "explain the ethical risks of your project" and you only see positives, the examiner will most likely conclude:', options: ['You built an unusually safe project', 'You have not thought critically about your own work — a serious weakness in AI development', 'You answered the question correctly', 'Your project does not need an ethical review'], correct: 1, explanation: 'Every AI project has potential risks — failing to identify any suggests a lack of critical thinking about your own work, which is a fundamental gap.' },
    { question: 'In a viva, you are asked to "defend your design decision to use a rule-based filter rather than a second AI prompt." What makes a strong defence?', options: ['Saying "it was easier to implement"', 'Explaining the trade-off: the filter is deterministic and auditable vs a second prompt which adds latency and unpredictability', 'Saying "my teacher suggested it"', 'Arguing that all approaches would have given the same result'], correct: 1, explanation: 'Strong defence articulates the trade-off you considered — what you gained and what you sacrificed — showing the decision was deliberate and reasoned.' },
    { question: 'Which preparation strategy is most effective for a viva voce?', options: ['Memorising a script for every possible question', 'Practising explaining your project out loud to someone unfamiliar with it, then answering their spontaneous questions', 'Re-reading your written submission the night before', 'Preparing only for the questions you found hardest during the project'], correct: 1, explanation: 'Live explanation to a naive audience simulates viva conditions better than any other preparation — it forces real-time articulation and surfaces gaps in your understanding.' }
  ],

  40: [
    { question: 'The term "viva voce" comes from Latin and means:', options: ['Written examination', 'With living voice — referring to an oral examination', 'Final assessment', 'Verbal agreement'], correct: 1, explanation: '"Viva voce" literally means "with living voice" — it describes an oral examination where understanding is tested through live dialogue rather than written responses.' },
    { question: 'An examiner asks "what assumptions did you make when designing your tool?" A weak response would be:', options: ['Listing specific assumptions and explaining why you made them', 'Saying "I didn\'t make any assumptions — I based everything on evidence"', 'Noting an assumption you made and explaining its impact on your design', 'Acknowledging an assumption that turned out to be wrong'], correct: 1, explanation: 'All design involves assumptions — claiming you made none reveals either lack of self-awareness or dishonesty, both serious weaknesses in a viva.' },
    { question: 'When defending an ethical choice in a viva — e.g. deciding to log user queries — what framework should structure your answer?', options: ['Legal compliance only: "it is permitted by GDPR"', 'Weighing the benefit (e.g. safety monitoring) against the harm (privacy cost) and explaining what safeguards reduce the harm', '"Everyone does this in commercial products"', '"The AI model requires it to function"'], correct: 1, explanation: 'Ethical defence requires demonstrating you weighed competing values and applied safeguards — not just that something is legal or common practice.' },
    { question: 'You are asked in a viva "if you had three more weeks, what would you build next?" This question is testing:', options: ['Whether you ran out of time due to poor planning', 'Your forward vision, understanding of your tool\'s limitations, and ability to prioritise future development', 'Whether you followed your original project plan', 'Your knowledge of other AI tools on the market'], correct: 1, explanation: 'This question assesses whether you understand your own project deeply enough to know what it lacks and where the highest-value improvements lie.' }
  ],

  41: [
    { question: 'Research on AI in higher education suggests which risk for graduates who over-rely on AI tools?', options: ['Their degree certificates will be invalidated', 'They may enter the workforce with underdeveloped core skills that employers expect graduates to have independently', 'Universities will charge higher fees for AI-assisted degrees', 'AI tools will become unavailable after graduation'], correct: 1, explanation: 'If students use AI to compensate for skills they never develop (critical writing, synthesis, analysis), they risk being unprepared for roles where those skills are assumed.' },
    { question: 'The "centaur" model of graduate employability suggests that future graduates will be most competitive if they:', options: ['Can use AI tools faster than their peers', 'Combine irreplaceable human skills (judgement, creativity, ethics) with effective AI collaboration', 'Specialise exclusively in AI engineering', 'Can work entirely independently without AI tools'], correct: 1, explanation: 'The centaur model (human + AI as one unit) predicts that graduates who amplify strong human skills with AI will outperform both pure human workers and pure AI in most professional roles.' },
    { question: 'Which skill does AI currently struggle most to replicate in professional contexts?', options: ['Summarising large volumes of text', 'Exercising moral and contextual judgement in high-stakes, novel situations', 'Generating first drafts of routine documents', 'Answering factual questions from a knowledge base'], correct: 1, explanation: 'Genuine moral and contextual judgement — knowing what to do in genuinely novel ethical dilemmas — remains a distinctively human capacity that AI cannot reliably replicate.' },
    { question: 'A student says "AI will do all writing jobs, so there\'s no point developing writing skills." What is the strongest counter-argument?', options: ['AI writing tools will be banned in most workplaces', 'Strong human writing ability is what enables you to critically evaluate, direct, and improve AI outputs — without it you cannot tell good from bad', 'Writing will be entirely automated within two years', 'Only creative writing will survive; functional writing is already automated'], correct: 1, explanation: 'You cannot effectively direct or evaluate AI writing without strong writing ability yourself — the skill remains foundational even if AI handles more drafting.' }
  ],

  42: [
    { question: 'When using AI to help draft a personal statement, which risk is most important to guard against?', options: ['The AI using outdated grammar rules', 'The statement losing your authentic voice and specific personal experiences — becoming generic', 'The statement being too long', 'The AI including information from other applicants\' statements'], correct: 1, explanation: 'AI tends to produce polished but generic prose — personal statements succeed through specific, personal detail that AI cannot supply and that distinguishes you from other applicants.' },
    { question: 'What is the most academically honest way to use AI when writing a personal statement?', options: ['Submitting an AI-generated draft with minor edits as your own work', 'Using AI to identify structural weaknesses or unclear sections, then rewriting those sections yourself', 'Asking AI to rewrite your entire statement "in a better style"', 'Using AI to generate examples of experiences you wish you had'], correct: 1, explanation: 'Using AI as a critical editor — finding problems for you to fix — preserves your authorship and authentic voice while improving quality.' },
    { question: 'A UCAS personal statement generated entirely by AI and submitted as your own work constitutes:', options: ['Acceptable use of available technology', 'Academic fraud — misrepresentation that can result in offer withdrawal or exclusion', 'A minor academic integrity issue with no serious consequences', 'Only a problem if the university detects it'], correct: 1, explanation: 'Submitting AI-generated work as your own to gain a place at university is fraudulent misrepresentation — universities explicitly prohibit it and can withdraw offers or places.' },
    { question: 'Which element of a personal statement is impossible for AI to write authentically?', options: ['The opening sentence', 'Specific reflections on a real experience that changed how you think about your subject', 'The concluding paragraph', 'A description of your career aspirations'], correct: 1, explanation: 'Genuine personal reflection on real, specific experiences is something only you can provide — AI can only generate plausible-sounding generic experiences it has no knowledge of.' }
  ],

  43: [
    { question: 'A retrospective framework asks teams to reflect on "what went well, what did not, and what to change." Why is the "what to change" step the most important?', options: ['It is the longest section and therefore most thorough', 'Without concrete actions to change, reflection produces no improvement — insight must translate to behaviour', 'It is the easiest part of a retrospective to complete', 'Changes should only be made by senior team members'], correct: 1, explanation: 'Retrospectives without actionable commitments become mere complaint sessions — the value is in the specific changes you commit to making differently next time.' },
    { question: 'Looking back at the full course, which skill is most transferable to life beyond school?', options: ['Knowing the exact training process of GPT-4', 'The ability to critically evaluate AI outputs, identify their limitations, and use them responsibly', 'Memorising the EU AI Act risk tier categories', 'Being able to write Python code to call an API'], correct: 1, explanation: 'Critical, responsible AI use is a durable meta-skill — the specific tools will change but the ability to evaluate and use them wisely applies across all future contexts.' },
    { question: 'Which retrospective question is most useful for identifying where your learning was deepest?', options: ['"Which lessons did I find most enjoyable?"', '"Where did I change my mind about something I was previously confident about?"', '"Which topics will appear in the exam?"', '"Which lessons were shortest?"'], correct: 1, explanation: 'Genuine conceptual change — updating a belief you held confidently — is a marker of deep learning; enjoyment and exam relevance are different dimensions entirely.' },
    { question: 'In a course retrospective, identifying a topic where you still have significant uncertainty is:', options: ['Evidence that the course failed to teach it effectively', 'Valuable — it shows metacognitive awareness and identifies where further learning is needed', 'Something to hide from teachers and peers', 'A sign you did not engage seriously with the course'], correct: 1, explanation: 'Knowing what you don\'t know (metacognition) is a sophisticated intellectual skill — it enables targeted further learning rather than false confidence.' }
  ],

  44: [
    { question: 'An "AI manifesto" at the end of a course asks you to articulate your personal principles. Why is this exercise valuable beyond the course itself?', options: ['It produces a document you can submit to universities', 'Making your values explicit helps you act consistently on them — especially under pressure to use AI conveniently rather than responsibly', 'It demonstrates to teachers that you paid attention', 'Manifestos are legally binding commitments to AI use standards'], correct: 1, explanation: 'Explicit personal principles act as a decision-making anchor — when facing a convenient but ethically questionable AI use, your stated values give you a standard to check yourself against.' },
    { question: 'A student\'s AI manifesto includes the principle "I will always disclose when AI contributed to my work." What does this commitment require in practice?', options: ['Only disclosing AI use when directly asked', 'Proactively noting AI contributions in submissions, conversations, and professional work — even when not required', 'Disclosing only if AI wrote more than 50% of the content', 'Only disclosing in academic contexts, not personal or professional ones'], correct: 1, explanation: 'A genuine commitment to transparency is unconditional — selectively disclosing undermines the principle and the trust it is meant to build.' },
    { question: 'Which of the following best reflects a "forward-looking" AI manifesto principle?', options: ['"I will not use AI for anything important"', '"I will keep learning about AI as the field evolves and update my approach as I learn more"', '"I will only use AI tools that existed when I took this course"', '"I will avoid AI in my career as much as possible"'], correct: 1, explanation: 'A forward-looking principle acknowledges that AI is changing rapidly — committing to ongoing learning and adaptation is more durable than any fixed list of permitted tools.' },
    { question: 'The final lesson asks you to synthesise the course into a personal position on AI. The word "synthesise" means:', options: ['Summarise every topic covered in order', 'Combine ideas from across the course into a coherent, original standpoint that is distinctively yours', 'Write a conclusion to the course essay', 'Agree with the positions expressed by the course materials'], correct: 1, explanation: 'Synthesis goes beyond summary — it means integrating diverse ideas into a new, coherent position that reflects your own developed thinking, not just a recap of content.' }
  ],

  45: [
    { question: 'The CRAAP test (Currency, Relevance, Authority, Accuracy, Purpose) was designed to evaluate sources. Why does AI struggle to meet the "accuracy" criterion?', options: ['AI responses are always too short to be accurate', 'AI cannot verify its own outputs against reality — it generates plausible text, not confirmed facts', 'AI only has access to inaccurate internet sources', 'AI accuracy depends entirely on the user\'s prompting skill'], correct: 1, explanation: 'AI generates statistically likely text rather than verifying claims — it has no internal fact-checking mechanism, making external verification essential.' },
    { question: 'The "illusory truth effect" is directly relevant to AI use because:', options: ['AI tools create an illusion of being more intelligent than they are', 'Repeated exposure to AI-generated misinformation can make it feel true even when you know AI can hallucinate', 'AI outputs always contain an illusion of certainty in their formatting', 'The effect only applies to human-to-human communication, not AI'], correct: 1, explanation: 'Cognitive psychology shows that repeated exposure increases perceived truth — consuming AI-generated content regularly can embed false information even in critical users.' },
    { question: 'Google\'s AI Overviews disaster (telling users to eat rocks, add glue to pizza) illustrated which fundamental limitation?', options: ['Google\'s servers were not powerful enough to run the AI', 'AI cannot reliably distinguish between reliable information and absurd content found online', 'The AI was deliberately programmed incorrectly by Google engineers', 'AI Overviews only work in certain languages'], correct: 1, explanation: 'The AI scraped and synthesised content without understanding or verifying it — producing confident, dangerous nonsense from unreliable web sources.' },
    { question: 'Epistemology, the study of knowledge, asks "how do you know what you know?" Applied to AI use, the most important epistemological question is:', options: ['"How fast can AI process information?"', '"What is the original source of this claim, and how was it verified?"', '"Which AI model has the largest training dataset?"', '"How many people agree with this AI output?"'], correct: 1, explanation: 'Tracing a claim to its original source and understanding how it was verified is the epistemological core of evaluating AI outputs — popularity and speed are irrelevant to truth.' }
  ]

};
