/* ── Curated Slide Content: Units 5 & 6 (Lessons 21-44) ── */

var SLIDES_U5U6 = {

  21: [
    { type: 'hook', title: 'From Consumer to Co-Creator', body: 'Until now, you have been consumers of AI — using ChatGPT, generating images, running searches. From today, you become co-creators. Your capstone project is your opportunity to build something original with AI: a tool, a system, or a solution that addresses a real problem. The best capstone projects from previous cohorts have included AI-powered revision tools, ethical audit frameworks, and community information systems. What will you create?' },
    { type: 'concept', title: 'The Capstone Brief', body: 'Your capstone project is the centrepiece of this course. Understanding the requirements now will set you up for success across the next 16 lessons.', bullets: ['Choose a real problem that AI can help solve — it must matter to someone', 'Build a working prototype or detailed design that demonstrates your solution', 'Apply ethical considerations from the ground up — not as an afterthought', 'Document your process in a sprint diary — decisions, blockers, and reflections', 'Present your work in a pitch-style presentation with Q&A', 'Complete a reflective essay connecting your project to course themes'], callout: 'The capstone is assessed on process as much as product. A well-documented failed experiment can score higher than an undocumented success.' },
    { type: 'concept', title: 'Shifting Your Mindset', body: 'Moving from consumer to creator requires a fundamental shift in how you think about AI. Creators ask different questions than consumers.', bullets: ['Consumer mindset: "What can AI do for me?" Creator mindset: "What can I build with AI?"', 'Consumers accept default outputs. Creators design systems that produce specific, reliable results', 'Consumers use one tool. Creators combine tools, APIs, and custom prompts into workflows', 'Consumers focus on single interactions. Creators think about user experience, edge cases, and failure modes', 'Every professional field increasingly needs people who can design AI-enhanced workflows — this is that skill'], callout: 'You do not need to be a programmer to be an AI creator. Prompt engineering, workflow design, and ethical analysis are all creation skills.' },
    { type: 'activity', title: 'Project Brainstorm', instructions: 'Generate at least 10 potential capstone project ideas using structured brainstorming techniques.', steps: ['Solo brainstorm (5 min): Write down every problem you encounter in daily life that AI could help solve', 'Category scan: Consider problems in education, health, environment, accessibility, community, and creative arts', 'Pair share: Discuss your ideas with a partner — add to each other\'s lists', 'Feasibility filter: For each idea, rate Feasibility (1-5) and Impact (1-5)', 'Shortlist your top 3 ideas based on combined feasibility and impact scores', 'Share your top idea with the class for initial feedback'] },
    { type: 'discussion', title: 'What Makes a Great Project?', questions: [{ num: 1, text: 'What is the difference between a project that uses AI and a project that needs AI? Which should your capstone be?' }, { num: 2, text: 'Should you choose a project you are passionate about or one that is technically impressive? Can you have both?' }, { num: 3, text: 'How will you balance ambition with feasibility given the time constraints?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🚀', label: 'Creator mindset', text: 'Shift from asking what AI can do for you to asking what you can build with AI' }, { icon: '📋', label: 'Process matters', text: 'Your capstone is assessed on documentation and reflection, not just the final product' }, { icon: '💡', label: 'Start with the problem', text: 'The best projects solve real problems for real people — technology comes second' }] }
  ],

  22: [
    { type: 'hook', title: 'Defining the Problem Statement', body: 'Einstein allegedly said: "If I had an hour to solve a problem, I would spend 55 minutes thinking about the problem and 5 minutes thinking about solutions." Most failed projects do not fail because of bad solutions — they fail because they solved the wrong problem. A clear problem statement is the foundation of everything that follows. Get this right and the rest flows naturally. Get it wrong and no amount of brilliant coding will save you.' },
    { type: 'concept', title: 'Anatomy of a Problem Statement', body: 'A strong problem statement is specific, measurable, and focused on the problem — not the solution. It answers who is affected, what the problem is, and why it matters.', bullets: ['Who: Identify the specific group affected — "Year 12 students" not "people"', 'What: Describe the problem precisely — "struggle to find relevant revision resources" not "have trouble revising"', 'Why it matters: Quantify the impact if possible — "leading to 15% lower average grades in mock exams"', 'Scope boundary: What is included and excluded — "this project focuses on biology A-Level, not all subjects"', 'Do NOT include the solution in your problem statement — that comes later'], callout: 'Weak: "Students need better AI tools." Strong: "Year 12 biology students at UK state schools spend an average of 3 hours per week searching for revision resources, with 60% reporting they cannot find materials matched to their exam board."' },
    { type: 'concept', title: 'Validating Your Problem', body: 'A problem statement is only as good as the evidence behind it. Before committing to a project, you need to validate that the problem is real, significant, and solvable.', bullets: ['Primary research: Survey or interview at least 5 people who experience the problem', 'Secondary research: Find statistics, studies, or reports that confirm the problem exists at scale', 'Competitor analysis: What solutions already exist? Why are they insufficient?', 'Feasibility check: Can you realistically address this problem with available tools and time?', 'The "so what" test: If you solved this problem, would anyone notice? Would anyone care?'], callout: 'If you cannot find anyone who cares about your problem, it is probably not the right problem to solve. Validation saves weeks of wasted effort.' },
    { type: 'activity', title: 'Write Your Problem Statement', instructions: 'Craft your capstone problem statement using the Capstone Project Brief Template from Resources.', steps: ['Open the Capstone Project Brief Template', 'Write a first draft of your problem statement using the Who-What-Why framework', 'Apply the "so what" test — does your problem matter enough to spend 16 lessons on?', 'Identify 3 pieces of evidence that validate your problem (survey your classmates if needed)', 'Revise your problem statement based on the evidence', 'Read it to a partner — can they explain the problem back to you clearly?'] },
    { type: 'discussion', title: 'Problem Framing', questions: [{ num: 1, text: 'How does the way you frame a problem influence the solutions you consider? Can framing introduce bias?' }, { num: 2, text: 'What is the risk of falling in love with a solution before properly defining the problem?' }, { num: 3, text: 'How would you validate a problem that affects a group you do not personally belong to?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎯', label: 'Problem first', text: 'A clear problem statement is the foundation — spend 55 minutes on the problem, 5 on the solution' }, { icon: '📊', label: 'Validate with evidence', text: 'Survey users, find data, check competitors — never assume a problem exists without proof' }, { icon: '✍️', label: 'Who-What-Why', text: 'Specific audience, precise problem, measurable impact, clear scope boundary' }] }
  ],

  23: [
    { type: 'hook', title: 'Ethics by Design', body: 'In 2023, a university student built an AI study companion for their capstone. It worked brilliantly — until they realised it was storing every question students asked, including personal struggles with mental health, without any consent mechanism. The student had not considered ethics until after building the tool. Ethics by design means building ethical considerations into your project from day one — not bolting them on as an afterthought.' },
    { type: 'concept', title: 'Ethics by Design Principles', body: 'Ethics by design is a proactive approach that embeds ethical thinking into every stage of project development, from conception to deployment.', bullets: ['Privacy by default: Collect the minimum data necessary. If you do not need it, do not collect it', 'Transparency: Users should understand what your system does, how it works, and what data it uses', 'Fairness: Test your system with diverse users and inputs to identify bias before deployment', 'Accountability: Define who is responsible when things go wrong. Document decisions and reasoning', 'Consent: Users must actively opt in to data collection and understand what they are agreeing to', 'Reversibility: Can users undo actions, delete their data, and withdraw from your system?'], callout: 'It is 100x cheaper to build ethics in from the start than to retrofit it after launch. The student with the study companion had to rebuild the entire data layer.' },
    { type: 'concept', title: 'Identifying Potential Harms', body: 'Every AI project carries potential for unintended harm. A systematic approach to harm identification helps you anticipate and prevent problems.', bullets: ['Direct harm: Could your system give wrong advice, discriminate, or invade privacy?', 'Indirect harm: Could your system be misused for purposes you did not intend?', 'Exclusion harm: Does your system work equally well for all users, or does it exclude some groups?', 'Dependency harm: Could users become unhealthily dependent on your system?', 'Environmental harm: What is the computational cost of running your system?'], callout: 'The Ethics Audit Checklist from Resources provides a structured framework for identifying harms. Use it now, not after your project is built.' },
    { type: 'activity', title: 'Ethical Impact Assessment', instructions: 'Conduct a pre-build ethical impact assessment for your capstone project using the Ethics Audit Checklist.', steps: ['Open the Ethics Audit Checklist from Resources', 'For your capstone project, work through each section: Data Privacy, Bias, Transparency, Accountability, Environment, Accessibility, Misinformation', 'For each potential harm identified, write: The risk, the likelihood (High/Medium/Low), and your mitigation strategy', 'Identify the single biggest ethical risk in your project', 'Design at least one safeguard that is built into the system by default', 'Share your assessment with a partner for feedback'] },
    { type: 'discussion', title: 'Ethics and Innovation', questions: [{ num: 1, text: 'Does embedding ethics slow down innovation? Is that an acceptable trade-off?' }, { num: 2, text: 'Who should be responsible for the ethical impact of a student project — the student, the teacher, or the school?' }, { num: 3, text: 'Can you think of a product you use daily that clearly did NOT consider ethics by design? What went wrong?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🛡️', label: 'Build it in', text: 'Ethics by design is 100x cheaper than retrofitting — embed ethical thinking from day one' }, { icon: '⚠️', label: 'Anticipate harms', text: 'Direct, indirect, exclusion, dependency, and environmental harms must all be considered' }, { icon: '📋', label: 'Use the checklist', text: 'The Ethics Audit Checklist provides a systematic framework for pre-build harm identification' }] }
  ],

  24: [
    { type: 'hook', title: 'Project Planning & Architecture', body: 'Software projects that skip planning are 3x more likely to fail, take 2x longer, and cost 4x more to fix. Yet most student projects jump straight to building. Today you will create a structured project plan with sprints, milestones, and a technical architecture that will keep you on track across the next 12 build sessions. The plan is not a bureaucratic exercise — it is your map through the wilderness.' },
    { type: 'concept', title: 'Sprint-Based Planning', body: 'Agile sprint methodology breaks large projects into small, manageable chunks — typically 1-2 week cycles. Each sprint has a clear goal, defined tasks, and a deliverable.', bullets: ['Sprint 0 (Foundation): Set up infrastructure, core functionality, testing approach', 'Sprint 1 (Core features): Build the minimum viable product (MVP)', 'Sprint 2 (Refinement): Integrate feedback, fix issues, add secondary features', 'Sprint 3 (Polish): User experience, testing, documentation, audit preparation', 'Each sprint ends with a review: What was completed? What blocked progress? What changes for next sprint?', 'Use the Sprint Diary Template from Resources to track daily and weekly progress'], callout: 'The most common student mistake is trying to build everything in Sprint 0. An MVP that works is better than a full-featured project that crashes.' },
    { type: 'concept', title: 'Technical Architecture', body: 'Before writing a line of code or crafting a single prompt, map out how the pieces of your project fit together. This is your technical architecture.', bullets: ['Inputs: What goes into your system? User text, uploaded files, API data, sensor readings?', 'Processing: What does your system do with the inputs? AI analysis, prompt chains, data transformation?', 'Outputs: What does the user receive? Text, visuals, recommendations, reports?', 'Data flow: How does information move through your system from input to output?', 'Dependencies: What external services, APIs, or tools does your project rely on?', 'Draw it out: A simple boxes-and-arrows diagram is worth a thousand words of description'], callout: 'If you cannot draw your system on a whiteboard in 2 minutes, it is too complicated. Simplify until you can.' },
    { type: 'activity', title: 'Build Your Project Plan', instructions: 'Create a sprint-based project plan and technical architecture diagram for your capstone.', steps: ['Open the Capstone Project Brief Template and Sprint Diary Template from Resources', 'Define your MVP — the simplest version of your project that demonstrates the core idea', 'Break the MVP into tasks and assign them to Sprint 0 (Foundation) and Sprint 1 (Core)', 'List Sprint 2 and Sprint 3 goals (these may change as you learn more)', 'Draw your technical architecture: Inputs, Processing, Outputs, Dependencies', 'Set 3 measurable milestones with dates — how will you know if you are on track?'] },
    { type: 'discussion', title: 'Planning and Reality', questions: [{ num: 1, text: 'Why do so many projects skip the planning phase? What makes jumping to building so tempting?' }, { num: 2, text: 'How detailed should a plan be? At what point does planning become procrastination?' }, { num: 3, text: 'What will you do when your plan inevitably meets reality and something does not work as expected?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📅', label: 'Sprint methodology', text: 'Break your project into 4 sprints with clear goals — Foundation, Core, Refinement, Polish' }, { icon: '🏗️', label: 'Architecture first', text: 'Map inputs, processing, outputs, and dependencies before you build anything' }, { icon: '🎯', label: 'MVP mindset', text: 'Build the simplest version that works first, then iterate — perfection is the enemy of progress' }] }
  ],

  25: [
    { type: 'hook', title: 'Applying Prompt Architecture', body: 'A single well-designed prompt can transform a chatbot from a generic question-answerer into a specialised expert tutor, medical triage assistant, or legal research tool. The PTFC framework you learned in Lesson 9 was training wheels. Today, you apply it at production scale — designing prompt systems that are reliable, consistent, and robust enough for real users to depend on.' },
    { type: 'concept', title: 'From Single Prompts to Prompt Systems', body: 'Production AI systems rarely rely on a single prompt. They use chains, templates, and dynamic prompts that work together as a system.', bullets: ['System prompts: Define the AI\'s role, personality, and constraints — persist across the conversation', 'User prompt templates: Structured templates that insert user input into a well-designed prompt', 'Prompt chains: Multiple prompts in sequence — output of one becomes input to the next', 'Guardrails: Instructions that prevent the AI from going off-topic, generating harmful content, or hallucinating', 'Few-shot examples: Including example inputs and desired outputs in the prompt to guide the model'], callout: 'ChatGPT\'s custom instructions are a system prompt. When you create a custom GPT, you are designing a prompt system. This is what professionals do.' },
    { type: 'concept', title: 'Testing Prompts Systematically', body: 'Production prompts must be tested like software. A prompt that works for one input might fail catastrophically for another.', bullets: ['Happy path testing: Does the prompt work with typical, expected inputs?', 'Edge case testing: What happens with unusual, extreme, or ambiguous inputs?', 'Adversarial testing: Can a user deliberately make the system produce harmful or wrong output?', 'Consistency testing: Does the same input produce similar quality output across multiple runs?', 'Regression testing: When you change one prompt, do other prompts in the chain still work?'], callout: 'Keep a Prompt Iteration Log (from Resources) for every prompt in your system. Record the version, what changed, and the test results. This documentation is gold during your viva.' },
    { type: 'activity', title: 'Design Your Prompt System', instructions: 'Design the prompt architecture for your capstone project. Create, test, and document at least 3 prompts.', steps: ['Identify every point in your project where AI is used — list each as a "prompt slot"', 'For each slot, write a PTFC prompt including system-level instructions', 'Design at least one prompt chain where output feeds into the next prompt', 'Test each prompt with 3 different inputs: typical, edge case, and adversarial', 'Record all prompts and test results in your Prompt Iteration Log', 'Refine any prompt that fails edge case or adversarial testing'] },
    { type: 'discussion', title: 'Prompt Engineering as a Profession', questions: [{ num: 1, text: 'Is prompt engineering a genuine professional skill or a temporary novelty that will disappear as AI improves?' }, { num: 2, text: 'How do you ensure prompt-based systems are reliable enough for real users to depend on?' }, { num: 3, text: 'What ethical responsibilities come with designing prompts that shape how AI interacts with people?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '⛓️', label: 'Prompt systems', text: 'Production AI uses chains, templates, and guardrails — not isolated single prompts' }, { icon: '🧪', label: 'Test systematically', text: 'Happy path, edge case, adversarial, consistency, and regression testing for every prompt' }, { icon: '📝', label: 'Document everything', text: 'A prompt iteration log is essential for tracking what works and defending your design choices' }] }
  ],

  26: [
    { type: 'hook', title: 'Logic Flows & Edge Cases', body: 'In 2014, a self-driving car encountered a cyclist balancing on one wheel at an intersection. The car\'s logic had no rule for this — it froze, unable to decide if the cyclist was moving or stationary. Edge cases like this are not rare exceptions; they are the reason most AI projects fail in the real world. Today, you will map the logic flows of your capstone and hunt for the edge cases that could break it.' },
    { type: 'concept', title: 'Logic Flow Design', body: 'A logic flow diagram maps every decision point in your system, showing what happens at each step and which paths the system can take.', bullets: ['Start with the user\'s entry point — what is the first thing they do?', 'Map every decision: If X then Y, else Z', 'Include error paths — what happens when something goes wrong?', 'Identify loops — can the user get stuck in a cycle?', 'Mark exit points — how does the user finish or leave the system?', 'Use standard flowchart symbols: rectangles for processes, diamonds for decisions, arrows for flow'], callout: 'If your logic flow has more than 15 steps, your system is too complex. Simplify until each path is clear and testable.' },
    { type: 'concept', title: 'Hunting Edge Cases', body: 'Edge cases are unusual inputs or situations that your system was not explicitly designed to handle. They are where most real-world failures occur.', bullets: ['Empty input: What happens if the user submits nothing?', 'Extreme input: Very long text, special characters, numbers where text is expected', 'Ambiguous input: Queries your system could interpret multiple ways', 'Adversarial input: Users deliberately trying to break or trick your system', 'Context mismatch: Users using your system for a purpose you did not intend', 'Failure cascades: What happens if an external API your system depends on goes down?'], callout: 'Professional developers spend 40% of their time on edge cases. Students typically spend 5%. This is the single biggest quality gap between amateur and professional work.' },
    { type: 'activity', title: 'Map and Break', instructions: 'Draw the logic flow of your capstone project, then systematically try to break it by finding edge cases.', steps: ['Draw the complete logic flow of your project on paper or a whiteboard', 'Trace through 3 typical user journeys — does the flow work for each?', 'List 10 edge cases specific to your project (use the categories above)', 'For each edge case, determine: Does your system handle it? How?', 'Identify the 3 most critical edge cases — the ones most likely to occur', 'Design a handling strategy for each: graceful error message, default behaviour, or prevention'] },
    { type: 'discussion', title: 'Designing for Failure', questions: [{ num: 1, text: 'Is it better to have a system that handles edge cases gracefully or one that prevents them from occurring? Can you do both?' }, { num: 2, text: 'How do you decide which edge cases are worth handling and which are too unlikely to worry about?' }, { num: 3, text: 'What is the difference between a system that fails silently and one that fails loudly? Which is more dangerous?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔀', label: 'Map every path', text: 'Logic flow diagrams reveal decision points, error paths, and loops before you build' }, { icon: '🔨', label: 'Break it first', text: 'Hunting edge cases before building saves enormous time and prevents embarrassing failures' }, { icon: '⚡', label: 'Handle failures gracefully', text: 'Every system fails — the question is whether it fails in a way the user can recover from' }] }
  ],

  27: [
    { type: 'hook', title: 'Sprint 0 — The Foundation', body: 'Every skyscraper starts with foundations. You cannot see them from the street, but they determine whether the building stands or falls. Sprint 0 is your foundation: the infrastructure, core functionality, and testing approach that everything else depends on. Today you start building. The goal is not a finished product — it is a solid base that you can build on confidently.' },
    { type: 'concept', title: 'Sprint 0 Goals', body: 'Sprint 0 is about establishing the foundations. Do not try to build features — focus on the infrastructure that makes features possible.', bullets: ['Set up your development environment and tools', 'Implement the absolute core functionality — the one thing your project must do', 'Establish a testing approach: How will you know if something works?', 'Create your project structure and file organisation', 'Set up version control or a backup system for your work', 'Begin your Sprint Diary — document every decision and the reasoning behind it'], callout: 'Sprint 0 success metric: By the end of today, your project should do one thing — however simple — and you should be able to demonstrate it.' },
    { type: 'concept', title: 'Working Effectively', body: 'Build sessions are most productive when you work with structure and discipline. These habits separate productive builders from frustrated ones.', bullets: ['Start with a 5-minute plan: Write down exactly what you will accomplish this session', 'Work in 25-minute focused blocks (Pomodoro technique) with 5-minute breaks', 'When stuck for more than 10 minutes, ask for help — do not burn time being stuck', 'Document as you go — notes written now save hours of confusion later', 'Test frequently — every 15-20 minutes, check that what you built still works', 'End with a 5-minute review: What did you accomplish? What will you do next session?'], callout: 'Write in your Sprint Diary at the end of every session. Future-you will thank present-you when it comes time for the reflective essay and viva.' },
    { type: 'activity', title: 'Build Session', instructions: 'Your first structured build session. Set up your project foundations and implement core functionality.', steps: ['5-min plan: Write down your 3 goals for this session', 'Set up your project environment (files, tools, accounts)', 'Implement your core functionality — the simplest possible version', 'Test it: Does it work? Document the result', 'If it works: Push further. If not: Debug, document the issue, ask for help if stuck', 'End-of-session review: Update your Sprint Diary with what you did, learned, and plan next'] },
    { type: 'discussion', title: 'Building Habits', questions: [{ num: 1, text: 'What was the hardest part of today\'s build session? How could you make it easier next time?' }, { num: 2, text: 'Did you write in your Sprint Diary? If not, what stopped you? How will you build this habit?' }, { num: 3, text: 'What is the current biggest risk to your project succeeding?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🏗️', label: 'Foundations first', text: 'Sprint 0 is about infrastructure and core functionality, not features' }, { icon: '📓', label: 'Document everything', text: 'Sprint Diary entries now save hours of confusion later and strengthen your reflective essay' }, { icon: '⏱️', label: 'Work with structure', text: 'Plan, build in focused blocks, test frequently, review at the end' }] }
  ],

  28: [
    { type: 'hook', title: 'Initial Peer Review', body: 'The most effective teams at companies like Google, Pixar, and SpaceX have one thing in common: a culture of candid feedback. Research shows that projects receiving structured peer feedback in early stages are 60% more likely to succeed. Today, you will give and receive honest, constructive feedback on your Sprint 0 work. This is not about being nice — it is about making each other\'s projects better.' },
    { type: 'concept', title: 'Giving Effective Feedback', body: 'Good feedback is specific, actionable, and balanced. It focuses on the work, not the person, and provides a clear path to improvement.', bullets: ['Be specific: "The input validation is missing" not "It needs work"', 'Be actionable: Every criticism should come with a suggestion for improvement', 'Balance: Start with what works well, then address what needs improvement', 'Focus on impact: How does the issue affect the user experience or project goals?', 'Ask questions: "Have you considered...?" is often more useful than "You should..."', 'Use the Peer Review Feedback Form from Resources for structure'], callout: 'The most valuable feedback is the hardest to give and hear. "This is great" is pleasant but useless. "Your error handling does not cover empty inputs, which could crash the system" is uncomfortable but invaluable.' },
    { type: 'concept', title: 'Receiving and Processing Feedback', body: 'How you receive feedback determines whether it improves your project. Defensiveness is natural but counterproductive.', bullets: ['Listen fully before responding — do not formulate rebuttals while the other person is talking', 'Ask clarifying questions: "Can you give me an example of what you mean?"', 'Take notes — you will not remember specific feedback an hour later', 'Separate your ego from your project — criticism of your work is not criticism of you', 'Triage: Not all feedback is equally important. Identify what to act on now, later, or never', 'Thank the reviewer — they invested time and thought in helping you improve'], callout: 'You do not have to implement every piece of feedback. But you should be able to explain why you chose not to act on a specific suggestion.' },
    { type: 'activity', title: 'Peer Review Session', instructions: 'Give and receive structured feedback on Sprint 0 deliverables using the Peer Review Feedback Form.', steps: ['Pair up with someone working on a different project', 'Demo your project (5 minutes): Show what you built, explain your architecture, and identify known issues', 'Your reviewer completes the Peer Review Feedback Form (10 minutes)', 'Discuss the feedback together (5 minutes) — ask clarifying questions', 'Swap roles and repeat', 'Write an action plan: Top 3 changes based on feedback, with priority order'] },
    { type: 'discussion', title: 'Feedback Culture', questions: [{ num: 1, text: 'Was it harder to give honest feedback or receive it? Why?' }, { num: 2, text: 'Did any feedback surprise you — something you had not noticed about your own project?' }, { num: 3, text: 'How can you build a habit of seeking feedback regularly rather than waiting for formal review sessions?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '💬', label: 'Specific and actionable', text: 'Good feedback names the issue, explains its impact, and suggests a solution' }, { icon: '👂', label: 'Listen before reacting', text: 'Separate ego from work — feedback on your project is not feedback on your worth' }, { icon: '📋', label: 'Triage and act', text: 'Not all feedback is equal — prioritise what to address now, later, or not at all' }] }
  ],

  29: [
    { type: 'hook', title: 'Deep Work Session 1', body: 'Cal Newport defines deep work as "professional activities performed in a state of distraction-free concentration that push your cognitive capabilities to their limit." Research shows that it takes an average of 23 minutes to regain focus after a distraction. In a 60-minute session, a single phone notification could cost you 40% of your productive time. Today, commit to deep work.' },
    { type: 'concept', title: 'Session Focus: Building Core Features', body: 'This is your first extended build session. The focus is making meaningful progress on your capstone while maintaining documentation discipline.', bullets: ['Review your Sprint Diary from last session — what did you plan to do today?', 'Set 2-3 specific, achievable goals for this session', 'Integrate the top priority feedback from your peer review', 'Test as you build — do not wait until the end to discover something is broken', 'If you hit a blocker, document it and move to a different task — do not lose momentum', 'Update your Sprint Diary before the session ends'], callout: 'Progress is rarely linear. Some sessions you will accomplish twice what you planned. Others you will spend the entire time debugging one issue. Both are normal.' },
    { type: 'activity', title: 'Deep Work Build', instructions: 'Extended build session with structured check-ins.', steps: ['5-min plan: Review Sprint Diary, set today\'s goals, identify potential blockers', '20-min build block 1: Work on your highest priority task', 'Quick check-in: Are you on track? Need help? Adjust if needed', '20-min build block 2: Continue building or move to next task', 'Quick check-in: Test what you have built so far', '10-min close: Update Sprint Diary with progress, blockers, and next steps'] },
    { type: 'discussion', title: 'Progress Check', questions: [{ num: 1, text: 'What did you accomplish today that you are most proud of?' }, { num: 2, text: 'What was your biggest blocker and how did you handle it?' }, { num: 3, text: 'On a scale of 1-10, how confident are you that your project will be ready on time?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎯', label: 'Goals and focus', text: 'Set specific goals, work in focused blocks, and eliminate distractions' }, { icon: '📓', label: 'Document as you go', text: 'Sprint Diary entries are evidence for your reflective essay and viva' }, { icon: '🔄', label: 'Adapt and continue', text: 'Hit a blocker? Document it, move to another task, and come back later' }] }
  ],

  30: [
    { type: 'hook', title: 'Deep Work Session 2', body: 'Feedback is only valuable if you act on it. Studies show that teams who integrate feedback within 48 hours see 3x the improvement compared to those who wait a week. Today\'s focus is integrating the feedback from your peer review and resolving any issues identified. Your project should visibly improve by the end of this session.' },
    { type: 'concept', title: 'Session Focus: Integrating Feedback', body: 'Today\'s priority is acting on the peer review feedback and resolving identified issues. This is where good projects become great.', bullets: ['Review your peer review action plan — what were your top 3 priorities?', 'Start with the highest-impact change that is achievable in this session', 'Test each change after implementing it — does it actually solve the issue?', 'If a suggested change conflicts with your design, document why you chose not to implement it', 'Look for patterns in the feedback — if multiple reviewers flagged the same issue, prioritise it', 'Update your Sprint Diary with what you changed and why'], callout: 'Being able to explain why you accepted or rejected specific feedback demonstrates critical thinking — this is exactly what your viva will assess.' },
    { type: 'activity', title: 'Feedback Integration Build', instructions: 'Focused build session on integrating peer review feedback and advancing core features.', steps: ['5-min plan: Review peer review action plan and prioritise changes', '20-min build block 1: Implement highest priority feedback change', 'Quick test: Does the change work? Does it break anything else?', '20-min build block 2: Continue with next priority or advance core features', 'Quick test: Run through your main user journey — does everything still work?', '10-min close: Update Sprint Diary — note what feedback was implemented and any decisions made'] },
    { type: 'discussion', title: 'Feedback in Action', questions: [{ num: 1, text: 'Which piece of feedback had the biggest positive impact on your project?' }, { num: 2, text: 'Did you choose not to implement any feedback? What was your reasoning?' }, { num: 3, text: 'What would you ask your next reviewer to focus on?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔧', label: 'Act on feedback quickly', text: 'Teams who integrate feedback within 48 hours see 3x the improvement' }, { icon: '🧠', label: 'Think critically', text: 'Accept, reject, or adapt feedback — but always document your reasoning' }, { icon: '✅', label: 'Test after every change', text: 'Every modification should be tested to ensure it solves the issue without creating new ones' }] }
  ],

  31: [
    { type: 'hook', title: 'Deep Work Session 3', body: 'You are now past the halfway point of your capstone build. This is where the "messy middle" hits — the initial excitement has faded, the finish line feels far away, and the bugs are multiplying. Research on creative projects shows this is the most critical phase: 70% of abandoned projects are abandoned in the middle third. Push through. The best work is on the other side.' },
    { type: 'concept', title: 'Session Focus: Testing and Refinement', body: 'Mid-project is the time to shift from building new features to testing and refining what you have. A polished MVP beats a broken full-feature prototype every time.', bullets: ['Systematic testing: Work through every user path in your system methodically', 'Bug triage: List every issue, classify as Critical, Major, or Minor, fix in that order', 'User experience review: Is your system intuitive? Could someone use it without instruction?', 'Performance check: Is your system responsive? Do prompts return results in reasonable time?', 'Edge case sweep: Test the 10 edge cases you identified in Lesson 26', 'Document: Update your Sprint Diary with test results and decisions'], callout: 'A project with 3 features that all work perfectly will always score higher than a project with 10 features where 4 are broken.' },
    { type: 'activity', title: 'Test and Refine Build', instructions: 'Focused session on systematic testing and refinement of your capstone project.', steps: ['5-min plan: List everything you need to test', '15-min testing: Work through every user path. Note every bug and issue', '5-min triage: Classify bugs as Critical, Major, or Minor', '20-min fix: Address critical and major bugs', 'Quick retest: Verify your fixes work and have not broken anything else', '10-min close: Update Sprint Diary with test results and remaining issues'] },
    { type: 'discussion', title: 'The Messy Middle', questions: [{ num: 1, text: 'How are you feeling about your project right now? What would help you push through any frustration?' }, { num: 2, text: 'What feature or aspect of your project are you most proud of so far?' }, { num: 3, text: 'If you could restart your project with what you know now, what would you do differently?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🧪', label: 'Test systematically', text: 'Work through every path, classify bugs by severity, fix critical issues first' }, { icon: '💪', label: 'Push through the middle', text: '70% of abandoned projects fail in the middle third — persistence is a skill' }, { icon: '✨', label: 'Polish over features', text: '3 working features beat 10 broken ones every time' }] }
  ],

  32: [
    { type: 'hook', title: 'Deep Work Session 4', body: 'Your ethical audit is next lesson. Before an audit, professional teams run a "pre-audit" — reviewing their own work against the audit criteria to identify and fix issues before the formal assessment. Today, you polish your project and prepare for the ethical audit. Think of this as your last chance to address ethical gaps before someone else finds them.' },
    { type: 'concept', title: 'Session Focus: Polish and Audit Prep', body: 'Today has two priorities: completing core functionality and conducting a self-audit against the Ethics Audit Checklist before the formal audit next session.', bullets: ['Complete any remaining core features — focus on what is achievable today', 'User interface polish: Clear labels, consistent design, helpful error messages', 'Pre-audit: Work through the Ethics Audit Checklist yourself', 'Data handling: Are you collecting only what you need? Is consent clear? Can data be deleted?', 'Transparency: Can users understand what your system does and how it works?', 'Bias check: Have you tested with diverse inputs and users?'], callout: 'Finding your own ethical gaps before the formal audit demonstrates maturity and self-awareness — qualities assessors value highly.' },
    { type: 'activity', title: 'Polish and Pre-Audit Build', instructions: 'Complete core features and conduct a self-audit using the Ethics Audit Checklist.', steps: ['5-min plan: What must be finished today? What can be cut?', '20-min build: Complete and polish core functionality', '15-min self-audit: Work through the Ethics Audit Checklist for your project', 'Note every issue found — classify as Must Fix, Should Fix, or Acknowledged Risk', '10-min fix: Address any Must Fix ethical issues', '5-min close: Update Sprint Diary. Note what you found in your self-audit'] },
    { type: 'discussion', title: 'Audit Readiness', questions: [{ num: 1, text: 'Did your self-audit reveal any ethical issues you had not previously considered?' }, { num: 2, text: 'How confident are you that your project handles user data ethically?' }, { num: 3, text: 'What is the single biggest ethical risk remaining in your project?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔍', label: 'Self-audit first', text: 'Finding your own issues before formal audit shows maturity and self-awareness' }, { icon: '✅', label: 'Complete over perfect', text: 'A complete, working project with known limitations beats an incomplete ambitious one' }, { icon: '📋', label: 'Prepare for scrutiny', text: 'The ethical audit is next — know your project\'s strengths and weaknesses inside out' }] }
  ],

  33: [
    { type: 'hook', title: 'Deep Work Session 5', body: 'This is your final build session. After today, your project must be ready to present and defend. Professional teams call this the "code freeze" — the point where you stop adding features and focus entirely on stability, documentation, and presentation readiness. Every minute spent on a new feature now is a minute not spent ensuring what you have actually works.' },
    { type: 'concept', title: 'Session Focus: Finalise and Document', body: 'Your final session priorities: address any ethical audit findings, finalise deliverables, and complete documentation.', bullets: ['Address ethical audit findings from Lesson 34 (if already completed) or self-audit issues', 'Feature freeze: No new features. Fix bugs, polish UI, improve error handling only', 'Complete your Sprint Diary — ensure every session is documented', 'Write your project README or user guide: What does it do? How do you use it?', 'Prepare a 2-minute demo: What will you show? In what order?', 'Final test: Run through the complete user journey one last time'], callout: 'Your documentation is as important as your code. Assessors who cannot understand your project cannot give it the marks it deserves.' },
    { type: 'activity', title: 'Final Build Session', instructions: 'Finalise your capstone project. No new features — focus on stability, documentation, and presentation readiness.', steps: ['5-min plan: List only critical final tasks (no new features!)', '15-min fixes: Address audit findings and remaining bugs', '15-min documentation: Complete Sprint Diary, write user guide', '10-min demo prep: Plan your 2-minute demonstration', '10-min final test: Complete user journey test', '5-min close: Final Sprint Diary entry — reflect on the entire build process'] },
    { type: 'discussion', title: 'Looking Back', questions: [{ num: 1, text: 'What was the most valuable lesson you learned during the build process?' }, { num: 2, text: 'If you had one more week, what would you add or change?' }, { num: 3, text: 'How has building a project changed your perspective on AI compared to just using AI?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🛑', label: 'Feature freeze', text: 'Stop adding features. Focus on stability, documentation, and presentation readiness' }, { icon: '📝', label: 'Documentation is essential', text: 'Assessors who cannot understand your project cannot give it the marks it deserves' }, { icon: '🎯', label: 'Demo readiness', text: 'Prepare a clear 2-minute demonstration that showcases your core functionality' }] }
  ],

  34: [
    { type: 'hook', title: 'The Ethical Audit', body: 'In 2023, the UK Government launched the AI Safety Institute — the world\'s first state-backed body dedicated to testing advanced AI for safety risks. Their audits examine fairness, transparency, security, and potential for misuse. Today, you will conduct a formal ethical audit of a classmate\'s project using the same principles. This is not a rubber stamp exercise — it is genuine scrutiny that will strengthen both the project and the auditor\'s ethical reasoning.' },
    { type: 'concept', title: 'The Audit Process', body: 'A formal ethical audit is a structured assessment of a system\'s alignment with ethical principles. It examines what the system does, how it does it, and what could go wrong.', bullets: ['Scope: Define what you are auditing — the entire system, or specific components?', 'Evidence gathering: Test the system, review documentation, interview the developer', 'Assessment: Score each ethical dimension against defined criteria', 'Findings: Document issues classified by severity — Critical, Major, Minor, Observation', 'Recommendations: Actionable steps to address each finding', 'Response: The developer responds to each finding — accept, mitigate, or acknowledge as limitation'], callout: 'A good auditor is thorough but fair. The goal is improvement, not punishment. The most useful audits identify real risks and propose practical solutions.' },
    { type: 'concept', title: 'Ethical Dimensions', body: 'The Ethics Audit Checklist examines seven key dimensions. Each requires evidence-based assessment, not opinion.', bullets: ['Data Privacy: What data is collected? Is consent obtained? Can data be deleted?', 'Bias & Fairness: Does the system perform equally well for different user groups?', 'Transparency: Can users understand how the system works and makes decisions?', 'Accountability: Who is responsible when the system makes an error?', 'Environmental Impact: What are the computational costs of running the system?', 'Accessibility: Can users with different needs access and use the system?', 'Misinformation Risk: Could the system generate, amplify, or spread false information?'], callout: 'An ethical system is not one with zero risks — it is one where risks are identified, assessed, and managed transparently.' },
    { type: 'activity', title: 'Conduct the Ethical Audit', instructions: 'Audit a classmate\'s capstone project using the Ethics Audit Checklist from Resources.', steps: ['Pair up with someone whose project you have not reviewed before', 'The developer gives a 5-minute demo and overview of their project', 'Using the Ethics Audit Checklist, work through each of the 7 dimensions', 'For each dimension, record: Evidence observed, Score (1-5), and Specific findings', 'Write 3 key recommendations with severity ratings', 'Present your findings to the developer. Developer responds to each finding'] },
    { type: 'discussion', title: 'Ethics in Practice', questions: [{ num: 1, text: 'Was conducting an ethical audit harder or easier than you expected? What surprised you?' }, { num: 2, text: 'How did it feel to have your own project audited? Did you agree with the findings?' }, { num: 3, text: 'Should ethical audits be mandatory for all AI products before they launch? Who should conduct them?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔍', label: 'Structured assessment', text: 'Ethical audits use evidence-based assessment across defined dimensions, not opinion' }, { icon: '📊', label: 'Seven dimensions', text: 'Privacy, fairness, transparency, accountability, environment, accessibility, and misinformation' }, { icon: '🤝', label: 'Improvement not punishment', text: 'The goal is to identify real risks and propose practical solutions' }] }
  ],

  35: [
    { type: 'hook', title: 'The Pitch Deck', body: 'In 2005, Airbnb\'s original pitch deck was rejected by every investor who saw it. But the deck itself was brilliantly structured: Problem, Solution, Market, Business Model, Team. Today, the same structure powers the most successful pitch presentations in the world. Your capstone pitch is not just a school presentation — it is a professional skill that will serve you in university applications, job interviews, and startup pitches throughout your career.' },
    { type: 'concept', title: 'Pitch Deck Structure', body: 'An effective pitch follows a proven narrative arc that takes the audience from problem to solution to impact. Use the Pitch Deck Structure Guide from Resources.', bullets: ['Slide 1 — Hook: A compelling statistic, question, or scenario that grabs attention', 'Slide 2 — Problem: What problem are you solving? Who does it affect? Why does it matter?', 'Slide 3 — Solution: Your project. What does it do? How does it work?', 'Slide 4 — Demo: Live demonstration or walkthrough of your key feature', 'Slide 5 — Ethics: How have you addressed ethical considerations?', 'Slide 6 — Reflection: What did you learn? What would you do differently?', 'Slide 7 — Ask: What do you want from your audience? Questions you are ready for?'], callout: 'The best pitches are stories, not feature lists. Take your audience on a journey from problem to solution to impact.' },
    { type: 'concept', title: 'Presentation Design Principles', body: 'Your slides should support your speaking, not replace it. Visual design has a direct impact on how persuasive your presentation is.', bullets: ['One idea per slide — if a slide makes two points, split it into two slides', 'Minimal text — maximum 6 words per bullet, maximum 6 bullets per slide', 'High-contrast visuals — dark backgrounds with light text, or vice versa', 'Screenshots and demos over descriptions — show, do not tell', 'Consistent design — same fonts, colours, and layout throughout', 'No reading from slides — if you are reading, you do not know your material'], callout: 'Steve Jobs\' famous product launches averaged 7 words per slide. Your slides are a backdrop for your speaking, not a script.' },
    { type: 'activity', title: 'Build Your Pitch Deck', instructions: 'Create your capstone pitch deck using the Pitch Deck Structure Guide from Resources.', steps: ['Open the Pitch Deck Structure Guide resource', 'Create slides 1-7 following the structure: Hook, Problem, Solution, Demo, Ethics, Reflection, Ask', 'Apply design principles: One idea per slide, minimal text, high contrast', 'Plan your demo: What will you show? Prepare a backup (screenshots) in case of tech failure', 'Time yourself: Your pitch should be 5-7 minutes with 3-5 minutes for Q&A', 'Practice once: Deliver your pitch to yourself or a partner'] },
    { type: 'discussion', title: 'Communicating Technical Ideas', questions: [{ num: 1, text: 'What is the hardest part of explaining a technical project to a non-technical audience?' }, { num: 2, text: 'How do you balance showing technical depth with keeping the audience engaged?' }, { num: 3, text: 'What makes you trust a presenter? What makes you switch off?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📊', label: 'Structure is everything', text: 'Hook, Problem, Solution, Demo, Ethics, Reflection, Ask — a proven narrative arc' }, { icon: '🎨', label: 'Design supports speaking', text: 'One idea per slide, minimal text, high contrast — slides are backdrops, not scripts' }, { icon: '🎤', label: 'Stories over features', text: 'Take your audience on a journey from problem to solution to impact' }] }
  ],

  36: [
    { type: 'hook', title: 'Dress Rehearsal', body: 'Research shows that presenters who rehearse at least 3 times deliver presentations rated 20% higher than those who rehearse once. Elite speakers like Steve Jobs rehearsed for weeks. TED Talk speakers practice an average of 200 times. You probably will not manage 200 rehearsals, but today\'s dress rehearsal is your chance to deliver your full presentation, get real feedback, and refine before the final showcase.' },
    { type: 'concept', title: 'Presentation Skills', body: 'Great presentations combine content, delivery, and audience awareness. Today, focus on delivery — the content is done.', bullets: ['Pacing: Aim for 130-150 words per minute. Most nervous speakers go too fast', 'Eye contact: Look at individuals in the audience, not the screen or the floor', 'Pausing: Silence is powerful. Pause after key points to let them land', 'Body language: Open stance, purposeful movement, natural gestures', 'Voice modulation: Vary pitch, speed, and volume to maintain interest', 'Handling questions: Repeat the question, answer concisely, admit when you do not know'], callout: 'The single most common presentation mistake: reading from slides. If you catch yourself doing it, stop, look at the audience, and say what you mean in your own words.' },
    { type: 'activity', title: 'Full Dress Rehearsal', instructions: 'Deliver your complete presentation to a small group. Receive structured feedback using the Presentation Assessment Rubric.', steps: ['Form groups of 3-4 students', 'Each person delivers their full presentation (5-7 minutes + Q&A)', 'Audience members complete the Presentation Assessment Rubric for each presenter', 'Focus feedback on: timing, clarity, demo quality, audience engagement, and Q&A handling', 'After all presentations, share feedback with each presenter', 'Each person writes down their top 3 improvements for the final presentation'] },
    { type: 'discussion', title: 'Performance and Nerves', questions: [{ num: 1, text: 'What was the most useful feedback you received? How will you act on it?' }, { num: 2, text: 'What strategies do you use to manage presentation anxiety?' }, { num: 3, text: 'Did watching others present teach you anything about your own presentation style?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎤', label: 'Practice matters', text: 'Presenters who rehearse 3+ times score 20% higher — there is no substitute for practice' }, { icon: '👁️', label: 'Delivery over content', text: 'Eye contact, pacing, pausing, and body language are as important as what you say' }, { icon: '📋', label: 'Act on feedback', text: 'Identify your top 3 improvements and implement them before the final showcase' }] }
  ],

  37: [
    { type: 'hook', title: 'Presentations — Group 1', body: 'This is it. Months of work come down to these minutes. You have identified a problem, designed a solution, built a prototype, conducted an ethical audit, and prepared a pitch. Now you present to a panel and your peers. Remember: the panel is not looking for perfection — they are looking for understanding, critical thinking, and the ability to communicate your work clearly.' },
    { type: 'concept', title: 'What the Panel Assesses', body: 'Understanding the assessment criteria helps you focus your presentation on what matters most. Use the Presentation Assessment Rubric as your guide.', bullets: ['Problem understanding: Do you clearly articulate the problem and why it matters?', 'Solution quality: Does your project address the problem effectively?', 'Technical depth: Do you demonstrate understanding of how your system works?', 'Ethical awareness: Have you considered and addressed ethical implications?', 'Presentation skills: Is your delivery clear, confident, and well-structured?', 'Q&A performance: Can you think on your feet and defend your decisions?'], callout: 'The best presentations are honest about limitations. Saying "this does not work perfectly because..." shows far more understanding than pretending everything is flawless.' },
    { type: 'activity', title: 'Present and Assess', instructions: 'Group 1 delivers capstone presentations. All students assess using the rubric.', steps: ['Group 1 presenters deliver their presentations (5-7 minutes each)', 'Panel asks 2-3 questions after each presentation', 'All audience members complete the Presentation Assessment Rubric', 'Audience members prepare one constructive question for each presenter', 'After all presentations, brief feedback is shared', 'Non-presenting students: Take notes on techniques you want to adopt for your own presentation'] },
    { type: 'discussion', title: 'Presentation Reflections', questions: [{ num: 1, text: 'Which presentation stood out to you and why?' }, { num: 2, text: 'What technique did you see that you want to adopt for your own presentation?' }, { num: 3, text: 'How did the Q&A sections go? What makes someone good at answering unexpected questions?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎯', label: 'Clarity over complexity', text: 'The best presentations communicate complex ideas simply and honestly' }, { icon: '🤔', label: 'Honesty about limitations', text: 'Acknowledging weaknesses demonstrates deeper understanding than pretending perfection' }, { icon: '💡', label: 'Learn from each other', text: 'Every presentation teaches you something about your own communication style' }] }
  ],

  38: [
    { type: 'hook', title: 'Presentations — Group 2', body: 'Group 2 — you have had the advantage of watching Group 1 present. Use what you observed. Notice what worked: clear structure, honest reflection, confident Q&A handling. Notice what did not: rushing, reading from slides, avoiding hard questions. Your presentation starts now.' },
    { type: 'concept', title: 'Learning from Group 1', body: 'Having observed Group 1, you can refine your approach in the final moments before presenting.', bullets: ['Timing: Did Group 1 presenters run over or under? Adjust your pacing accordingly', 'Q&A patterns: What questions did the panel ask? Prepare answers to similar questions', 'Demo issues: Did anyone have technical problems? Prepare your backup plan', 'Engagement: What kept the audience\'s attention? What lost it?', 'Honesty: Presenters who acknowledged limitations were more convincing, not less', 'Confidence: You know your project better than anyone in the room — trust your preparation'], callout: 'The panel asks similar question types across presentations: "Why did you choose this approach?", "What would you do differently?", "How did you address ethics?". Prepare for these.' },
    { type: 'activity', title: 'Present and Assess', instructions: 'Group 2 delivers capstone presentations. All students assess using the rubric.', steps: ['Group 2 presenters deliver their presentations (5-7 minutes each)', 'Panel asks 2-3 questions after each presentation', 'All audience members complete the Presentation Assessment Rubric', 'Audience members prepare one constructive question for each presenter', 'After all presentations, brief feedback is shared', 'Class discussion: Compare overall themes and quality between Group 1 and Group 2'] },
    { type: 'discussion', title: 'Collective Reflection', questions: [{ num: 1, text: 'Having now seen all presentations, what common strengths and weaknesses do you notice across the class?' }, { num: 2, text: 'Which project do you think has the most potential for real-world impact? Why?' }, { num: 3, text: 'How has presenting your own work changed your relationship with your project?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📊', label: 'Observe and adapt', text: 'Watching others present teaches you as much as presenting yourself' }, { icon: '🎤', label: 'Trust your preparation', text: 'You know your project better than anyone — confidence comes from understanding' }, { icon: '🌟', label: 'Celebrate the work', text: 'Every presentation represents months of learning, building, and critical thinking' }] }
  ],

  39: [
    { type: 'hook', title: 'Viva Voce — Session 1', body: 'The viva voce (Latin for "living voice") is an oral examination tradition dating back to medieval universities. Unlike a written exam, a viva tests your ability to think, articulate, and defend your ideas in real time. There is no hiding behind rehearsed scripts — the examiner will follow your answers with probing follow-up questions. This is where deep understanding separates from surface-level knowledge.' },
    { type: 'concept', title: 'Preparing for the Viva', body: 'A viva voce tests depth of understanding, critical reflection, and the ability to articulate your thinking under pressure. Use the Viva Voce Question Bank from Resources to prepare.', bullets: ['Know your project inside out: Every design decision, every ethical choice, every compromise', 'Be ready to explain WHY, not just WHAT — "I chose this approach because..."', 'Prepare for "what would you do differently?" — self-awareness scores highly', 'Connect your project to course themes: ethics, bias, regulation, human oversight', 'Practice thinking aloud: The examiner wants to see your reasoning process, not just your conclusions', 'It is perfectly acceptable to say "That is a great question — let me think about that for a moment"'], callout: 'The viva is a conversation, not an interrogation. The examiner wants you to succeed. They ask probing questions because they want to see the depth of your thinking.' },
    { type: 'activity', title: 'Viva Practice', instructions: 'Practice viva-style questioning with a partner using the Viva Voce Question Bank.', steps: ['Pair up with a partner', 'Take turns asking questions from the Viva Voce Question Bank (5 minutes each)', 'Focus on follow-up questions: "Why?", "What if?", "How do you know?"', 'Give feedback: Was the answer clear? Did they demonstrate depth? Did they connect to course themes?', 'Identify your 3 weakest areas and prepare stronger answers', 'If time permits, repeat with a different partner'] },
    { type: 'discussion', title: 'Articulating Understanding', questions: [{ num: 1, text: 'What is the difference between knowing something and being able to explain it clearly to someone else?' }, { num: 2, text: 'Which course theme do you feel most confident discussing? Which feels weakest?' }, { num: 3, text: 'How can you demonstrate depth of understanding rather than surface-level knowledge?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🗣️', label: 'Think aloud', text: 'The viva tests your reasoning process, not just your conclusions — show your thinking' }, { icon: '🔗', label: 'Connect the dots', text: 'Link your project to course themes: ethics, bias, regulation, human oversight' }, { icon: '💡', label: 'Why, not what', text: 'Be ready to explain every decision — the reasoning matters more than the choice itself' }] }
  ],

  40: [
    { type: 'hook', title: 'Viva Voce — Session 2', body: 'Continuation of the viva voce examinations. If you have not yet been examined, use this time to prepare. If you have, reflect on your performance and support your classmates.' },
    { type: 'concept', title: 'Viva Tips from Session 1', body: 'Based on common patterns from the first viva session, here are refined tips for remaining candidates.', bullets: ['Take a breath before answering — a 3-second pause shows thoughtfulness, not uncertainty', 'Structure your answers: State your position, give evidence, acknowledge counter-arguments', 'If you do not understand a question, ask for clarification — this is expected and normal', 'Connect to specific course content: Reference specific lessons, case studies, or frameworks', 'Be honest about what you do not know — genuine reflection scores higher than bluffing', 'End answers confidently — do not trail off with "so yeah..." or "I think..."'], callout: 'The strongest viva candidates are not the ones with perfect projects — they are the ones who can articulate what they learned, including from their mistakes.' },
    { type: 'activity', title: 'Viva Examinations Continue', instructions: 'Remaining students complete their viva voce examinations.', steps: ['If waiting: Review the Viva Voce Question Bank one more time', 'During your viva: Listen carefully, think before answering, connect to course themes', 'After your viva: Write a brief reflection — What went well? What would you improve?', 'If already examined: Support classmates by being a quiet, supportive audience', 'Complete any outstanding course documentation', 'Begin thinking about your reflective essay'] },
    { type: 'discussion', title: 'Post-Viva Reflection', questions: [{ num: 1, text: 'How did the viva compare to your expectations? Was it harder or easier than you thought?' }, { num: 2, text: 'What question challenged you the most? How would you answer it now?' }, { num: 3, text: 'How has the viva experience changed how you think about oral communication as a skill?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '✨', label: 'Reflection over perfection', text: 'The strongest candidates articulate what they learned, including from mistakes' }, { icon: '🎯', label: 'Structure your answers', text: 'Position, evidence, counter-argument — give the examiner a clear framework' }, { icon: '🗣️', label: 'Oral skills matter', text: 'The ability to defend your ideas verbally is a lifelong professional skill' }] }
  ]

};
