/* ── Curated Slide Content: Units 5 & 6 (Lessons 21-44) ── */

var SLIDES_U5U6 = {

  21: [
    { type: 'hook', title: 'From Consumer to Co-Creator', body: 'Until now, you have been consumers of AI — using ChatGPT, generating images, running searches. From today, you become co-creators. Your capstone project is your opportunity to build something original with AI: a tool, a system, or a solution that addresses a real problem. The best capstone projects from previous cohorts have included AI-powered revision tools, ethical audit frameworks, and community information systems. What will you create?' },
    { type: 'concept', title: 'The Capstone Brief', body: 'Your capstone project is the centrepiece of this course. Understanding the requirements now will set you up for success across the next 16 lessons.', bullets: ['Choose a real problem that AI can help solve — it must matter to someone', 'Build a working prototype or detailed design that demonstrates your solution', 'Apply ethical considerations from the ground up — not as an afterthought', 'Document your process in a sprint diary — decisions, blockers, and reflections', 'Present your work in a pitch-style presentation with Q&A', 'Complete a reflective essay connecting your project to course themes'], callout: 'The capstone is assessed on process as much as product. A well-documented failed experiment can score higher than an undocumented success.' },
    { type: 'concept', title: 'Shifting Your Mindset', body: 'Moving from consumer to creator requires a fundamental shift in how you think about AI. Creators ask different questions than consumers.', bullets: ['Consumer mindset: "What can AI do for me?" Creator mindset: "What can I build with AI?"', 'Consumers accept default outputs. Creators design systems that produce specific, reliable results', 'Consumers use one tool. Creators combine tools, APIs, and custom prompts into workflows', 'Consumers focus on single interactions. Creators think about user experience, edge cases, and failure modes', 'Every professional field increasingly needs people who can design AI-enhanced workflows — this is that skill'], callout: 'You do not need to be a programmer to be an AI creator. Prompt engineering, workflow design, and ethical analysis are all creation skills.' },
    { type: 'activity', title: 'Project Brainstorm', instructions: 'Generate at least 10 potential capstone project ideas using structured brainstorming techniques.', steps: ['Solo brainstorm (5 min): Write down every problem you encounter in daily life that AI could help solve', 'Category scan: Consider problems in education, health, environment, accessibility, community, and creative arts', 'Pair share: Discuss your ideas with a partner — add to each other\'s lists', 'Feasibility filter: For each idea, rate Feasibility (1-5) and Impact (1-5)', 'Shortlist your top 3 ideas based on combined feasibility and impact scores', 'Share your top idea with the class for initial feedback'] },
    { type: 'discussion', title: 'What Makes a Great Project?', questions: [{ num: 1, text: 'What is the difference between a project that uses AI and a project that needs AI? Which should your capstone be?' }, { num: 2, text: 'Should you choose a project you are passionate about or one that is technically impressive? Can you have both?' }, { num: 3, text: 'How will you balance ambition with feasibility given the time constraints?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🚀', label: 'Creator mindset', text: 'Shift from asking what AI can do for you to asking what you can build with AI' }, { icon: '📋', label: 'Process matters', text: 'Your capstone is assessed on documentation and reflection, not just the final product' }, { icon: '💡', label: 'Start with the problem', text: 'The best projects solve real problems for real people — technology comes second' }] }
  ],

  22: [
    { type: 'hook', title: 'Defining the Problem Statement', body: 'Einstein allegedly said: "If I had an hour to solve a problem, I would spend 55 minutes thinking about the problem and 5 minutes thinking about solutions." Most failed projects do not fail because of bad solutions — they fail because they solved the wrong problem. A clear problem statement is the foundation of everything that follows. Get this right and the rest flows naturally. Get it wrong and no amount of brilliant coding will save you.' },
    { type: 'concept', title: 'Anatomy of a Problem Statement', body: 'A strong problem statement is specific, measurable, and focused on the problem — not the solution. It answers who is affected, what the problem is, and why it matters.', bullets: ['Who: Identify the specific group affected — "Year 12 students" not "people"', 'What: Describe the problem precisely — "struggle to find relevant revision resources" not "have trouble revising"', 'Why it matters: Quantify the impact if possible — "leading to 15% lower average grades in mock exams"', 'Scope boundary: What is included and excluded — "this project focuses on biology A-Level, not all subjects"', 'Do NOT include the solution in your problem statement — that comes later'], callout: 'Weak: "Students need better AI tools." Strong: "Year 12 biology students at UK state schools spend an average of 3 hours per week searching for revision resources, with 60% reporting they cannot find materials matched to their exam board."' },
    { type: 'concept', title: 'Validating Your Problem', body: 'A problem statement is only as good as the evidence behind it. Before committing to a project, you need to validate that the problem is real, significant, and solvable.', bullets: ['Primary research: Survey or interview at least 5 people who experience the problem', 'Secondary research: Find statistics, studies, or reports that confirm the problem exists at scale', 'Competitor analysis: What solutions already exist? Why are they insufficient?', 'Feasibility check: Can you realistically address this problem with available tools and time?', 'The "so what" test: If you solved this problem, would anyone notice? Would anyone care?'], callout: 'If you cannot find anyone who cares about your problem, it is probably not the right problem to solve. Validation saves weeks of wasted effort.' },
    { type: 'activity', title: 'Write Your Problem Statement', instructions: 'Craft your capstone problem statement using the Capstone Project Brief Template from Resources.', steps: ['Open the Capstone Project Brief Template', 'Write a first draft of your problem statement using the Who-What-Why framework', 'Apply the "so what" test — does your problem matter enough to spend 16 lessons on?', 'Identify 3 pieces of evidence that validate your problem (survey your classmates if needed)', 'Revise your problem statement based on the evidence', 'Read it to a partner — can they explain the problem back to you clearly?'] },
    { type: 'discussion', title: 'Problem Framing', questions: [{ num: 1, text: 'How does the way you frame a problem influence the solutions you consider? Can framing introduce bias?' }, { num: 2, text: 'What is the risk of falling in love with a solution before properly defining the problem?' }, { num: 3, text: 'How would you validate a problem that affects a group you do not personally belong to?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎯', label: 'Problem first', text: 'A clear problem statement is the foundation — spend 55 minutes on the problem, 5 on the solution' }, { icon: '📊', label: 'Validate with evidence', text: 'Survey users, find data, check competitors — never assume a problem exists without proof' }, { icon: '✍️', label: 'Who-What-Why', text: 'Specific audience, precise problem, measurable impact, clear scope boundary' }] }
  ],

  23: [
    { type: 'hook', title: 'Ethics by Design', body: 'In 2023, a university student built an AI study companion for their capstone. It worked brilliantly — until they realised it was storing every question students asked, including personal struggles with mental health, without any consent mechanism. The student had not considered ethics until after building the tool. Ethics by design means building ethical considerations into your project from day one — not bolting them on as an afterthought.' },
    { type: 'concept', title: 'Ethics by Design Principles', body: 'Ethics by design is a proactive approach that embeds ethical thinking into every stage of project development, from conception to deployment.', bullets: ['Privacy by default: Collect the minimum data necessary. If you do not need it, do not collect it', 'Transparency: Users should understand what your system does, how it works, and what data it uses', 'Fairness: Test your system with diverse users and inputs to identify bias before deployment', 'Accountability: Define who is responsible when things go wrong. Document decisions and reasoning', 'Consent: Users must actively opt in to data collection and understand what they are agreeing to', 'Reversibility: Can users undo actions, delete their data, and withdraw from your system?'], callout: 'It is 100x cheaper to build ethics in from the start than to retrofit it after launch. The student with the study companion had to rebuild the entire data layer.' },
    { type: 'concept', title: 'Identifying Potential Harms', body: 'Every AI project carries potential for unintended harm. A systematic approach to harm identification helps you anticipate and prevent problems.', bullets: ['Direct harm: Could your system give wrong advice, discriminate, or invade privacy?', 'Indirect harm: Could your system be misused for purposes you did not intend?', 'Exclusion harm: Does your system work equally well for all users, or does it exclude some groups?', 'Dependency harm: Could users become unhealthily dependent on your system?', 'Environmental harm: What is the computational cost of running your system?'], callout: 'The Ethics Audit Checklist from Resources provides a structured framework for identifying harms. Use it now, not after your project is built.' },
    { type: 'activity', title: 'Ethical Impact Assessment', instructions: 'Conduct a pre-build ethical impact assessment for your capstone project using the Ethics Audit Checklist.', steps: ['Open the Ethics Audit Checklist from Resources', 'For your capstone project, work through each section: Data Privacy, Bias, Transparency, Accountability, Environment, Accessibility, Misinformation', 'For each potential harm identified, write: The risk, the likelihood (High/Medium/Low), and your mitigation strategy', 'Identify the single biggest ethical risk in your project', 'Design at least one safeguard that is built into the system by default', 'Share your assessment with a partner for feedback'] },
    { type: 'discussion', title: 'Ethics and Innovation', questions: [{ num: 1, text: 'Does embedding ethics slow down innovation? Is that an acceptable trade-off?' }, { num: 2, text: 'Who should be responsible for the ethical impact of a student project — the student, the teacher, or the school?' }, { num: 3, text: 'Can you think of a product you use daily that clearly did NOT consider ethics by design? What went wrong?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🛡️', label: 'Build it in', text: 'Ethics by design is 100x cheaper than retrofitting — embed ethical thinking from day one' }, { icon: '⚠️', label: 'Anticipate harms', text: 'Direct, indirect, exclusion, dependency, and environmental harms must all be considered' }, { icon: '📋', label: 'Use the checklist', text: 'The Ethics Audit Checklist provides a systematic framework for pre-build harm identification' }] }
  ],

  24: [
    { type: 'hook', title: 'Project Planning & Architecture', body: 'Software projects that skip planning are 3x more likely to fail, take 2x longer, and cost 4x more to fix. Yet most student projects jump straight to building. Today you will create a structured project plan with sprints, milestones, and a technical architecture that will keep you on track across the next 12 build sessions. The plan is not a bureaucratic exercise — it is your map through the wilderness.' },
    { type: 'concept', title: 'Sprint-Based Planning', body: 'Agile sprint methodology breaks large projects into small, manageable chunks — typically 1-2 week cycles. Each sprint has a clear goal, defined tasks, and a deliverable.', bullets: ['Sprint 0 (Foundation): Set up infrastructure, core functionality, testing approach', 'Sprint 1 (Core features): Build the minimum viable product (MVP)', 'Sprint 2 (Refinement): Integrate feedback, fix issues, add secondary features', 'Sprint 3 (Polish): User experience, testing, documentation, audit preparation', 'Each sprint ends with a review: What was completed? What blocked progress? What changes for next sprint?', 'Use the Sprint Diary Template from Resources to track daily and weekly progress'], callout: 'The most common student mistake is trying to build everything in Sprint 0. An MVP that works is better than a full-featured project that crashes.' },
    { type: 'concept', title: 'Technical Architecture', body: 'Before writing a line of code or crafting a single prompt, map out how the pieces of your project fit together. This is your technical architecture.', bullets: ['Inputs: What goes into your system? User text, uploaded files, API data, sensor readings?', 'Processing: What does your system do with the inputs? AI analysis, prompt chains, data transformation?', 'Outputs: What does the user receive? Text, visuals, recommendations, reports?', 'Data flow: How does information move through your system from input to output?', 'Dependencies: What external services, APIs, or tools does your project rely on?', 'Draw it out: A simple boxes-and-arrows diagram is worth a thousand words of description'], callout: 'If you cannot draw your system on a whiteboard in 2 minutes, it is too complicated. Simplify until you can.' },
    { type: 'activity', title: 'Build Your Project Plan', instructions: 'Create a sprint-based project plan and technical architecture diagram for your capstone.', steps: ['Open the Capstone Project Brief Template and Sprint Diary Template from Resources', 'Define your MVP — the simplest version of your project that demonstrates the core idea', 'Break the MVP into tasks and assign them to Sprint 0 (Foundation) and Sprint 1 (Core)', 'List Sprint 2 and Sprint 3 goals (these may change as you learn more)', 'Draw your technical architecture: Inputs, Processing, Outputs, Dependencies', 'Set 3 measurable milestones with dates — how will you know if you are on track?'] },
    { type: 'discussion', title: 'Planning and Reality', questions: [{ num: 1, text: 'Why do so many projects skip the planning phase? What makes jumping to building so tempting?' }, { num: 2, text: 'How detailed should a plan be? At what point does planning become procrastination?' }, { num: 3, text: 'What will you do when your plan inevitably meets reality and something does not work as expected?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📅', label: 'Sprint methodology', text: 'Break your project into 4 sprints with clear goals — Foundation, Core, Refinement, Polish' }, { icon: '🏗️', label: 'Architecture first', text: 'Map inputs, processing, outputs, and dependencies before you build anything' }, { icon: '🎯', label: 'MVP mindset', text: 'Build the simplest version that works first, then iterate — perfection is the enemy of progress' }] }
  ],

  25: [
    { type: 'hook', title: 'Applying Prompt Architecture', body: 'A single well-designed prompt can transform a chatbot from a generic question-answerer into a specialised expert tutor, medical triage assistant, or legal research tool. The PTFC framework you learned in Lesson 9 was training wheels. Today, you apply it at production scale — designing prompt systems that are reliable, consistent, and robust enough for real users to depend on.' },
    { type: 'concept', title: 'From Single Prompts to Prompt Systems', body: 'Production AI systems rarely rely on a single prompt. They use chains, templates, and dynamic prompts that work together as a system.', bullets: ['System prompts: Define the AI\'s role, personality, and constraints — persist across the conversation', 'User prompt templates: Structured templates that insert user input into a well-designed prompt', 'Prompt chains: Multiple prompts in sequence — output of one becomes input to the next', 'Guardrails: Instructions that prevent the AI from going off-topic, generating harmful content, or hallucinating', 'Few-shot examples: Including example inputs and desired outputs in the prompt to guide the model'], callout: 'ChatGPT\'s custom instructions are a system prompt. When you create a custom GPT, you are designing a prompt system. This is what professionals do.' },
    { type: 'concept', title: 'Testing Prompts Systematically', body: 'Production prompts must be tested like software. A prompt that works for one input might fail catastrophically for another.', bullets: ['Happy path testing: Does the prompt work with typical, expected inputs?', 'Edge case testing: What happens with unusual, extreme, or ambiguous inputs?', 'Adversarial testing: Can a user deliberately make the system produce harmful or wrong output?', 'Consistency testing: Does the same input produce similar quality output across multiple runs?', 'Regression testing: When you change one prompt, do other prompts in the chain still work?'], callout: 'Keep a Prompt Iteration Log (from Resources) for every prompt in your system. Record the version, what changed, and the test results. This documentation is gold during your viva.' },
    { type: 'activity', title: 'Design Your Prompt System', instructions: 'Design the prompt architecture for your capstone project. Create, test, and document at least 3 prompts.', steps: ['Identify every point in your project where AI is used — list each as a "prompt slot"', 'For each slot, write a PTFC prompt including system-level instructions', 'Design at least one prompt chain where output feeds into the next prompt', 'Test each prompt with 3 different inputs: typical, edge case, and adversarial', 'Record all prompts and test results in your Prompt Iteration Log', 'Refine any prompt that fails edge case or adversarial testing'] },
    { type: 'discussion', title: 'Prompt Engineering as a Profession', questions: [{ num: 1, text: 'Is prompt engineering a genuine professional skill or a temporary novelty that will disappear as AI improves?' }, { num: 2, text: 'How do you ensure prompt-based systems are reliable enough for real users to depend on?' }, { num: 3, text: 'What ethical responsibilities come with designing prompts that shape how AI interacts with people?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '⛓️', label: 'Prompt systems', text: 'Production AI uses chains, templates, and guardrails — not isolated single prompts' }, { icon: '🧪', label: 'Test systematically', text: 'Happy path, edge case, adversarial, consistency, and regression testing for every prompt' }, { icon: '📝', label: 'Document everything', text: 'A prompt iteration log is essential for tracking what works and defending your design choices' }] }
  ]

};
