/* ── Curated Slide Content: Units 3 & 4 (Lessons 13-20) ── */

var SLIDES_U3U4 = {

  13: [
    { type: 'hook', title: 'Deepfakes and Disinformation', body: 'In 2024, a deepfake video of a multinational CEO announcing fake earnings wiped $25 billion from the company\'s stock price in 12 minutes before it was identified as synthetic. In the same year, AI-generated audio of a political leader was shared 50 million times before fact-checkers could respond. Deepfake technology has advanced from obvious fakes to near-perfect synthetic media — and detection is losing the arms race against generation.' },
    { type: 'concept', title: 'How Deepfakes Work', body: 'Deepfakes use deep learning — specifically generative adversarial networks (GANs) and diffusion models — to create synthetic media that is increasingly indistinguishable from authentic content.', bullets: ['GANs pit two neural networks against each other: a generator creates fakes, a discriminator tries to detect them', 'Each iteration improves both — the generator makes better fakes and the discriminator gets sharper', 'Face-swapping: Maps one person\'s facial expressions onto another\'s face in video', 'Voice cloning: Models can now clone a voice from as little as 3 seconds of audio', 'Text-to-video: Tools like Sora can generate photorealistic video from text descriptions'], callout: 'In 2019, creating a convincing deepfake required hours of footage and expensive hardware. Today, free apps can do it from a single photo in minutes.' },
    { type: 'concept', title: 'Detection and Defence', body: 'As deepfakes improve, detection methods struggle to keep pace. A multi-layered approach combining technology and media literacy is essential.', bullets: ['Technical detection: AI models trained to spot artefacts — blinking patterns, skin texture inconsistencies, lighting anomalies', 'Provenance tracking: C2PA standard embeds cryptographic metadata proving where and when content was captured', 'Watermarking: Invisible digital watermarks embedded in AI-generated content (Google SynthID, OpenAI metadata)', 'Media literacy: Teaching people to question source, context, and plausibility before sharing', 'The arms race problem: Every detection method becomes training data for better deepfakes'], callout: 'Current deepfake detectors achieve about 65-85% accuracy on the latest generation models — barely better than a coin flip on the most sophisticated fakes.' },
    { type: 'activity', title: 'Spot the Fake', instructions: 'Use the Deepfake Detection Checklist from Resources to analyse a set of real and synthetic media samples.', steps: ['Your teacher will provide 6 media samples — some real, some AI-generated', 'For each sample, work through the Deepfake Detection Checklist systematically', 'Look for: unnatural blinking, inconsistent lighting, warped edges, audio-lip sync issues', 'Record your verdict for each: Real, Fake, or Unsure', 'Compare results with the class — what was your accuracy rate?', 'Discuss: Which fakes were hardest to detect and why?'] },
    { type: 'discussion', title: 'Truth in a Post-Truth World', questions: [{ num: 1, text: 'If anyone can create convincing fake video of anyone saying anything, what happens to the concept of evidence?' }, { num: 2, text: 'Should creating deepfakes be illegal, or only sharing them? How would you enforce such a law?' }, { num: 3, text: 'The "liar\'s dividend": Now that deepfakes exist, real video can be dismissed as fake. How do we combat this?' }] },
    { type: 'quiz', question: 'What is the minimum a deepfake typically requires to convincingly replicate someone\'s face?', options: ['Thousands of hours of video footage', 'A full 3D scan of the person\'s face', 'A relatively small amount of source images or video', 'The person\'s explicit consent and cooperation'], correct: 2, explanation: 'Modern deepfake technology can produce convincing results with minimal source material — even a few photos or short video clips can be enough. This accessibility is what makes deepfakes such a significant societal risk.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎭', label: 'Technology is advancing fast', text: 'Deepfakes now require minimal source material and can be created with free tools in minutes' }, { icon: '🔍', label: 'Detection is struggling', text: 'AI detectors achieve 65-85% accuracy — provenance standards and media literacy are essential complements' }, { icon: '⚠️', label: 'Societal risk', text: 'Deepfakes threaten elections, financial markets, personal reputations, and the very concept of evidence' }] }
  ],

  14: [
    { type: 'hook', title: 'Surveillance and Facial Recognition', body: 'London has over 940,000 CCTV cameras — one for every 10 residents. China\'s SkyNet system covers over 600 million cameras with real-time facial recognition. In 2020, Robert Williams, a Black man in Detroit, was wrongfully arrested after facial recognition software misidentified him. He spent 30 hours in custody for a crime he did not commit. The technology promises safety but delivers a complex trade-off between security and civil liberties.' },
    { type: 'concept', title: 'How Facial Recognition Works', body: 'Facial recognition systems convert faces into mathematical representations (faceprints) and compare them against databases. The technology has improved dramatically but remains deeply flawed.', bullets: ['Detection: Identifies that a face exists in an image or video frame', 'Alignment: Normalises the face to a standard position and size', 'Feature extraction: Maps facial geometry — distance between eyes, jaw shape, nose bridge — into a numeric vector', 'Matching: Compares the faceprint against a database of known faces', 'Accuracy varies dramatically: 99.7% for white males, 65.3% for dark-skinned females (NIST 2019 study)'], callout: 'The performance gap is not a bug — it reflects training data that is overwhelmingly composed of lighter-skinned faces. Bias is baked into the technology.' },
    { type: 'concept', title: 'The Surveillance Debate', body: 'Facial recognition in public spaces creates a fundamental tension between collective security and individual privacy. Both sides make compelling arguments.', bullets: ['For surveillance: Prevents terrorism, finds missing persons, reduces crime, catches wanted criminals faster', 'Against surveillance: Creates chilling effects on free expression, protest, and movement', 'Function creep: Technology deployed for one purpose (e.g. counter-terrorism) inevitably expands to others', 'Disproportionate impact: Marginalised communities face higher false positive rates and heavier surveillance', 'Democratic accountability: Most surveillance systems are deployed without public consultation or consent'], callout: 'San Francisco banned government use of facial recognition in 2019. The EU AI Act classifies real-time facial recognition in public spaces as "high risk." The UK has no equivalent restriction.' },
    { type: 'activity', title: 'Surveillance Policy Design', instructions: 'Your group represents a city council deciding whether to deploy facial recognition cameras in your city centre. Use the Surveillance Debate Pack from Resources.', steps: ['Split into three teams: Security advocates, Civil liberties advocates, and the Council', 'Security team: Prepare a 3-minute case for deploying facial recognition with specific safeguards', 'Civil liberties team: Prepare a 3-minute case against deployment with alternative safety proposals', 'Both teams present to the Council', 'Council asks questions and deliberates', 'Council votes and announces their decision with reasoning'] },
    { type: 'discussion', title: 'Where Do You Draw the Line?', questions: [{ num: 1, text: 'Would you accept facial recognition in your school if it made the building safer? What about your neighbourhood?' }, { num: 2, text: 'If the accuracy gap between demographic groups cannot be fully closed, should the technology be deployed at all?' }, { num: 3, text: 'China uses facial recognition to monitor ethnic minorities in Xinjiang. At what point does surveillance become oppression?' }] },
    { type: 'quiz', question: 'According to NIST studies, facial recognition error rates for dark-skinned women can be up to how many times higher than for light-skinned men?', options: ['5 times higher', '10 times higher', '50 times higher', '100 times higher'], correct: 3, explanation: 'NIST studies found error rates up to 100 times higher for dark-skinned women than white men in some commercial systems — a disparity that has led to wrongful arrests and calls for moratoriums on the technology.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📷', label: 'Unequal accuracy', text: 'Facial recognition error rates are up to 100x higher for dark-skinned women than light-skinned men' }, { icon: '⚖️', label: 'Security vs. liberty', text: 'Surveillance creates genuine safety benefits but risks chilling effects on protest, expression, and movement' }, { icon: '🏛️', label: 'Regulation varies wildly', text: 'From San Francisco\'s ban to China\'s mass deployment — no global consensus exists' }] }
  ],

  15: [
    { type: 'hook', title: 'The Environmental Cost', body: 'Training GPT-4 is estimated to have consumed as much electricity as 120 US homes use in an entire year. A single ChatGPT query uses roughly 10 times the energy of a Google search. By 2027, AI data centres could consume as much electricity as the Netherlands. At the same time, AI is being used to optimise energy grids, accelerate climate research, and design more efficient materials. Is AI a climate villain or a climate hero? The answer is: both.' },
    { type: 'concept', title: 'The Carbon Cost of AI', body: 'AI\'s environmental footprint comes from three sources: training models, running inference, and the hardware lifecycle. Each contributes significantly to carbon emissions.', bullets: ['Training: GPT-3 training emitted approximately 552 tonnes of CO2 — equivalent to 120 cars driving for a year', 'Inference: Running the model for users. ChatGPT serving 100 million users daily consumes enormous energy', 'Hardware: Manufacturing GPUs requires rare earth minerals, water, and energy-intensive fabrication', 'Data centres: Require massive cooling systems, often using millions of litres of water daily', 'The trend is accelerating: Each new generation of models is 5-10x larger than the last'], callout: 'Google\'s total carbon emissions rose 48% from 2019 to 2023, largely driven by AI infrastructure expansion.' },
    { type: 'concept', title: 'AI as Climate Solution', body: 'Despite its footprint, AI offers transformative potential for environmental sustainability. The question is whether the benefits outweigh the costs.', bullets: ['Energy grid optimisation: DeepMind reduced Google data centre cooling energy by 40% using AI', 'Climate modelling: AI can run climate simulations 100,000x faster than traditional methods', 'Materials science: AI accelerates discovery of better batteries, solar cells, and carbon capture materials', 'Agriculture: Precision farming using AI reduces water use by 30% and pesticide use by 50%', 'Deforestation monitoring: AI satellite analysis detects illegal logging in near real-time'], callout: 'The net equation: If AI\'s climate solutions save more emissions than AI itself produces, the technology is net-positive. But this is not guaranteed — it depends on how we deploy it.' },
    { type: 'activity', title: 'Carbon Calculator', instructions: 'Estimate the environmental impact of your personal AI use and propose a sustainability strategy. Use the AI Environmental Impact Factsheet from Resources.', steps: ['List every AI service you use regularly (ChatGPT, Copilot, Midjourney, etc.)', 'Using the Factsheet, estimate the energy per query for each service', 'Estimate your total queries per week and calculate your monthly AI carbon footprint', 'Research: What is your AI provider doing about sustainability?', 'Propose 3 changes you could make to reduce your AI environmental impact', 'Design a one-page "Sustainable AI Use" policy for your school'] },
    { type: 'discussion', title: 'The Green AI Dilemma', questions: [{ num: 1, text: 'Should AI companies be required to disclose the carbon footprint of their models? Should users see a "carbon cost" per query?' }, { num: 2, text: 'Is it ethical to train ever-larger models when smaller, more efficient models might be good enough?' }, { num: 3, text: 'If AI can solve climate change faster, does its own carbon cost become an acceptable trade-off?' }] },
    { type: 'quiz', question: 'Roughly how much more energy does a single ChatGPT query use compared to a standard Google search?', options: ['About the same', 'About 3 times more', 'About 10 times more', 'About 100 times more'], correct: 2, explanation: 'A single ChatGPT query uses approximately 10 times the energy of a standard Google search. At scale — with 100+ million daily users — this translates to enormous aggregate energy consumption.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '⚡', label: 'Massive energy use', text: 'AI training and inference consume enormous energy — GPT-4 training used as much as 120 homes for a year' }, { icon: '🌱', label: 'Climate solution potential', text: 'AI can optimise energy grids, accelerate materials discovery, and improve agriculture sustainability' }, { icon: '📊', label: 'Net impact uncertain', text: 'Whether AI helps or hurts the climate depends entirely on how we choose to deploy it' }] }
  ],

  16: [
    { type: 'hook', title: 'Global Regulation', body: 'The EU AI Act classifies AI systems by risk level and imposes strict requirements. The US takes a sector-by-sector approach with minimal federal legislation. The UK promotes a "pro-innovation" framework with voluntary guidelines. China requires algorithmic transparency and content labelling but uses AI extensively for state surveillance. Four major powers, four fundamentally different approaches. The rules governing AI depend entirely on where you live — and companies operating globally must navigate all of them.' },
    { type: 'concept', title: 'Four Regulatory Models', body: 'Understanding the major global approaches reveals fundamentally different philosophies about the role of government in technology governance.', bullets: ['EU AI Act (2024): Risk-based framework. Bans "unacceptable risk" uses (social scoring, real-time biometric surveillance). Requires transparency and human oversight for "high risk" systems', 'US approach: Sector-specific. No comprehensive federal AI law. Executive orders provide guidance. Industry self-regulation is the default', 'UK approach: Context-based, pro-innovation. No new AI-specific laws. Existing regulators (Ofcom, FCA, ICO) apply AI principles within their domains', 'China approach: Algorithmic regulation requires companies to register algorithms with the government. Content generated by AI must be labelled. Strong state control combined with aggressive AI development'], callout: 'The EU regulates to protect citizens. The US regulates to protect markets. The UK regulates to encourage innovation. China regulates to maintain state control.' },
    { type: 'concept', title: 'The Regulation Dilemma', body: 'Every regulatory approach involves trade-offs. Too little regulation risks harm; too much risks stifling innovation and falling behind competitors.', bullets: ['The Brussels Effect: EU regulations often become global standards because companies find it easier to comply everywhere than to maintain separate systems', 'Innovation vs. safety: Strict regulation may drive AI companies to relocate to less regulated jurisdictions', 'Speed mismatch: AI evolves in months; legislation takes years. Regulation is always playing catch-up', 'Enforcement challenge: How do you audit an algorithm? Who checks compliance? What are the penalties?', 'International coordination: Without global standards, companies can regulatory-shop for the friendliest jurisdiction'], callout: 'The EU AI Act took 3 years to negotiate. In that time, ChatGPT launched, AI art generators emerged, and deepfakes became mainstream. Regulation is always behind.' },
    { type: 'activity', title: 'Regulation Jigsaw', instructions: 'Using the Regulation Jigsaw Cards from Resources, become an expert on one regulatory approach and teach it to your group.', steps: ['Form groups of 4. Each person takes one jurisdiction: EU, US, UK, or China', 'Using the Jigsaw Cards, become an expert on your jurisdiction (10 minutes)', 'Return to your group and teach the others about your approach (3 minutes each)', 'As a group, create a comparison table: Strengths, Weaknesses, and Key Differences', 'Vote: Which approach would you adopt for a new country? Justify your choice', 'Present your group\'s recommendation to the class'] },
    { type: 'discussion', title: 'Governing the Ungovernable?', questions: [{ num: 1, text: 'Should there be a single global AI regulatory framework, similar to international aviation rules? Is this realistic?' }, { num: 2, text: 'The UK\'s pro-innovation approach means less protection but potentially more AI investment. Is this a good trade-off?' }, { num: 3, text: 'If you were designing AI regulation for the UK from scratch, what three rules would you prioritise?' }] },
    { type: 'quiz', question: 'What approach does the EU AI Act take to regulating artificial intelligence?', options: ['A complete ban on AI in public services', 'A risk-based classification system (unacceptable, high, limited, minimal)', 'Voluntary guidelines with no enforcement', 'Regulation only of military AI applications'], correct: 1, explanation: 'The EU AI Act classifies AI systems by risk level: unacceptable uses are banned (e.g. social scoring), high-risk systems face strict requirements, limited-risk needs transparency, and minimal-risk is unregulated.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🇪🇺', label: 'Four models', text: 'EU (risk-based), US (sector-specific), UK (pro-innovation), China (state-controlled) — fundamentally different philosophies' }, { icon: '⏱️', label: 'Speed mismatch', text: 'Technology evolves in months while legislation takes years — regulation is always catching up' }, { icon: '🌍', label: 'No global standard', text: 'Without international coordination, companies can choose the most permissive jurisdiction' }] }
  ],

  17: [
    { type: 'hook', title: 'Analysing the Status Quo', body: 'A 2024 survey found that 89% of UK universities now have an AI policy — but only 23% of students had actually read it. Meanwhile, 67% of students admitted to using AI tools regularly for coursework. The gap between policy and practice is enormous. Before you can write better policy, you need to understand what already exists, what works, and what fails. Today, you become policy auditors.' },
    { type: 'concept', title: 'Policy Audit Framework', body: 'Evaluating AI policies requires a structured approach. A good audit examines not just what a policy says, but how practical, enforceable, and fair it is.', bullets: ['Scope: What does the policy cover? Does it address all relevant AI tools or just some?', 'Clarity: Can a typical student or staff member understand the rules without legal training?', 'Enforceability: How are violations detected? What are the consequences? Are they proportionate?', 'Fairness: Does the policy affect all students equally, or does it disadvantage some groups?', 'Currency: When was it last updated? Does it cover tools that exist today?'], callout: 'Many school AI policies were written before ChatGPT launched in November 2022. A policy that does not mention generative AI is already outdated.' },
    { type: 'concept', title: 'Common Policy Gaps', body: 'Research reveals recurring weaknesses in existing AI policies across education. Identifying these patterns helps you build better alternatives.', bullets: ['Binary thinking: Policies that simply ban or allow AI, with no nuance for different use cases', 'Tool-specific rules: Banning ChatGPT by name rather than addressing the category of generative AI', 'No guidance on disclosure: Students do not know when or how to declare AI use', 'Assessment disconnect: Policies do not explain how AI use affects marking or academic integrity', 'Staff training gap: Policies for students but no guidance for teachers using AI in their work'], callout: 'The best policies focus on principles (transparency, academic integrity, critical thinking) rather than specific tools, because tools change faster than policies.' },
    { type: 'activity', title: 'Policy Audit Workshop', instructions: 'Audit a real university or school AI policy using the University AI Policy Comparison resource and the audit framework above.', steps: ['Your teacher will provide 2-3 real AI policies from UK universities or schools', 'Using the audit framework, score each policy on: Scope, Clarity, Enforceability, Fairness, and Currency', 'Rate each criterion from 1 (poor) to 5 (excellent) with written justification', 'Identify the top 3 strengths and top 3 weaknesses across all policies', 'Write 3 specific recommendations for improvement', 'Compare findings with another pair — did you identify the same issues?'] },
    { type: 'discussion', title: 'Policy in Practice', questions: [{ num: 1, text: 'Why do you think most students have not read their institution\'s AI policy? How could this be fixed?' }, { num: 2, text: 'Should AI policies be written by administrators, teachers, students, or all three? Why?' }, { num: 3, text: 'Is it possible to write an AI policy that is both strict enough to maintain academic integrity and flexible enough to encourage learning with AI?' }] },
    { type: 'quiz', question: 'What is the most common weakness found when auditing existing school AI policies?', options: ['They are too long and detailed', 'They focus on principles rather than tools', 'They use binary thinking — blanket bans or no rules at all', 'They update too frequently'], correct: 2, explanation: 'Many school AI policies fall into binary thinking — either banning AI entirely or having no restrictions. Effective policies address the spectrum of AI use and focus on transferable principles rather than specific tool names.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📋', label: 'Audit before you build', text: 'Understanding what exists — and what fails — is essential before writing new policy' }, { icon: '🔍', label: 'Common gaps', text: 'Binary thinking, tool-specific bans, and missing disclosure guidance are recurring weaknesses' }, { icon: '🎯', label: 'Principles over tools', text: 'The best policies focus on values like transparency and integrity, not specific app names' }] }
  ],

  18: [
    { type: 'hook', title: 'Defining Acceptable Use', body: 'A student uses ChatGPT to brainstorm essay ideas. Acceptable? Most say yes. A student uses ChatGPT to write their entire essay. Unacceptable? Most say yes. But what about using AI to improve grammar? To restructure paragraphs? To generate a first draft that they then rewrite? The line between acceptable and unacceptable AI use is not a line at all — it is a spectrum. Today, your class will collaboratively define where the boundaries should be.' },
    { type: 'concept', title: 'The Spectrum of AI Use', body: 'AI use in education exists on a spectrum from fully independent work to fully AI-generated work. Defining acceptable use requires mapping this spectrum and deciding where to draw boundaries.', bullets: ['Level 0: No AI used — entirely human work', 'Level 1: AI as inspiration — brainstorming ideas, exploring topics, checking understanding', 'Level 2: AI as editor — grammar checking, proofreading, structural suggestions', 'Level 3: AI as collaborator — generating drafts that the student substantially rewrites', 'Level 4: AI as author — submitting AI-generated work with minimal human editing'], callout: 'Most educators agree Level 0-2 is acceptable and Level 4 is not. The real debate is about Level 3 — and this is where your policy must be clear.' },
    { type: 'concept', title: 'Balancing Innovation and Integrity', body: 'An effective acceptable use policy must balance two competing goals: encouraging students to develop AI skills they will need professionally, while maintaining academic integrity.', bullets: ['The skills argument: Students who cannot use AI effectively will be disadvantaged in the workplace', 'The integrity argument: If AI does the thinking, students do not develop critical skills', 'The equity argument: Not all students have equal access to AI tools — policies must account for this', 'The transparency principle: Whatever the rules, students must always disclose AI use', 'The assessment redesign approach: Instead of banning AI, redesign assessments so AI use demonstrates learning rather than replacing it'], callout: 'The International Baccalaureate now allows AI use with disclosure, treating it like any other research tool. This is a significant shift in educational policy.' },
    { type: 'activity', title: 'Acceptable Use Workshop', instructions: 'Collaboratively define acceptable use criteria for your school. Work through specific scenarios to build consensus.', steps: ['In groups of 4, discuss: What should students be allowed to use AI for?', 'Work through 8 scenarios your teacher provides — classify each as Acceptable, Unacceptable, or Depends', 'For each "Depends" scenario, define what conditions would make it acceptable', 'Draft 5 core principles of acceptable AI use in education', 'Share your principles with another group and negotiate any disagreements', 'As a class, vote on the final set of principles'] },
    { type: 'discussion', title: 'Drawing the Line', questions: [{ num: 1, text: 'If a student uses AI to generate ideas but writes everything themselves, should they still have to disclose AI use?' }, { num: 2, text: 'How should schools handle the fact that some students have access to paid AI tools (GPT-4) while others only have free versions?' }, { num: 3, text: 'A teacher uses AI to generate lesson plans and worksheets. Should the same rules that apply to students apply to teachers?' }] },
    { type: 'quiz', question: 'Why is transparency (disclosure of AI use) considered a "non-negotiable" principle across most AI policies?', options: ['It makes AI tools easier to use', 'It ensures AI tools are more accurate', 'It allows honest assessment of human vs. AI contribution', 'It prevents all forms of academic misconduct'], correct: 2, explanation: 'Regardless of where an institution draws the line on acceptable AI use, disclosure is essential because it allows fair assessment of what a student actually contributed versus what AI produced.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📊', label: 'It is a spectrum', text: 'AI use ranges from inspiration to authorship — acceptable use policies must address the middle ground' }, { icon: '⚖️', label: 'Balance is key', text: 'Good policy encourages AI literacy while maintaining academic integrity and equity' }, { icon: '📢', label: 'Transparency always', text: 'Regardless of where you draw the line, disclosure of AI use should be a non-negotiable principle' }] }
  ],

  19: [
    { type: 'hook', title: 'Drafting the Document', body: 'The UK Government\'s AI Safety Institute was established in November 2023 with a 12-page founding document. The EU AI Act runs to 459 pages. OpenAI\'s usage policy is 3 pages. The length, language, and structure of a policy document directly affects whether people actually read and follow it. Today, you will learn professional drafting techniques and write a formal AI acceptable use policy that is clear enough to follow and rigorous enough to enforce.' },
    { type: 'concept', title: 'Policy Document Structure', body: 'Professional policy documents follow established conventions that make them clear, authoritative, and enforceable. Understanding these conventions is a transferable skill.', bullets: ['Title and version number: Identifies the document and tracks updates', 'Purpose statement: One paragraph explaining why the policy exists', 'Scope: Who does this policy apply to? In what contexts?', 'Definitions: Define key terms (e.g. "generative AI", "AI-assisted work", "disclosure")', 'Rules and principles: The core requirements, numbered and unambiguous', 'Enforcement: What happens when rules are broken? Who decides? What is the appeals process?', 'Review date: When will the policy be updated?'], callout: 'The golden rule of policy writing: If a reasonable person could interpret a rule two different ways, the rule is not clear enough.' },
    { type: 'concept', title: 'Writing Effective Policy Language', body: 'Policy language must be precise without being impenetrable. The best policies are written in plain English with specific, actionable requirements.', bullets: ['Use "must" for mandatory requirements and "should" for recommendations', 'Avoid vague terms like "appropriate", "reasonable", or "excessive" without defining them', 'Include examples to illustrate rules — "For example, using AI to check grammar is permitted"', 'Use numbered sections and sub-sections for easy reference', 'Keep sentences under 25 words where possible', 'Test readability: If a Year 10 student cannot understand a rule, rewrite it'], callout: 'Bad: "Students should use AI responsibly." Good: "Students must disclose all AI tool use by including an AI Use Statement at the end of submitted work, specifying which tools were used and for what purpose."' },
    { type: 'activity', title: 'Draft Your Policy', instructions: 'Using the AI Policy Drafting Template from Resources, write a formal AI acceptable use policy for your school.', steps: ['Open the AI Policy Drafting Template resource', 'Write the Purpose statement (2-3 sentences)', 'Define the Scope (who, what, when)', 'Write Definitions for at least 5 key terms', 'Draft at least 8 numbered rules covering the spectrum of AI use', 'Write an Enforcement section with at least 3 levels of consequence', 'Set a Review Date and explain the review process', 'Peer review: Swap with a partner and identify any ambiguous language'] },
    { type: 'discussion', title: 'Language and Power', questions: [{ num: 1, text: 'Why is precise language so important in policy documents? What happens when rules are ambiguous?' }, { num: 2, text: 'Should policies be written in formal or informal language? What are the trade-offs of each?' }, { num: 3, text: 'How can you make a policy document that people actually read, rather than one that sits in a drawer?' }] },
    { type: 'quiz', question: 'In professional policy drafting, what is the difference between "must" and "should"?', options: ['They mean the same thing', '"Must" is mandatory; "should" is recommended but not required', '"Should" is stronger than "must"', '"Must" is only used in legal documents'], correct: 1, explanation: 'In policy language, "must" creates a mandatory obligation, while "should" indicates a recommendation. This distinction is critical — ambiguity in policy language leads to inconsistent enforcement.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📝', label: 'Structure matters', text: 'Professional policies follow conventions: purpose, scope, definitions, rules, enforcement, review date' }, { icon: '✍️', label: 'Precision is essential', text: 'Use "must" vs "should", define key terms, avoid ambiguity, include examples' }, { icon: '👥', label: 'Readability counts', text: 'A policy nobody reads is a policy nobody follows — plain language and clear formatting are critical' }] }
  ],

  20: [
    { type: 'hook', title: 'Ratification', body: 'In 2024, the European Parliament voted 523 to 46 to adopt the AI Act — the world\'s first comprehensive AI law. But before that vote, the act went through 18 months of committee debates, 3,000 proposed amendments, and intense lobbying from tech companies. Democracy is messy, slow, and full of compromise. Today, your class will experience that process firsthand as you present, debate, and vote on your AI policies in a simulated governance process.' },
    { type: 'concept', title: 'The Democratic Process', body: 'Policy ratification in democratic systems involves structured debate, amendment, and voting. Understanding this process is essential civic literacy.', bullets: ['Presentation: Policy authors present their proposal with evidence and reasoning', 'Committee review: A smaller group examines the proposal in detail and suggests amendments', 'Debate: Open discussion where all stakeholders can support, oppose, or propose changes', 'Amendment: Formal process for modifying specific clauses before the final vote', 'Vote: Democratic decision — majority, supermajority, or consensus depending on the rules', 'Implementation: The adopted policy is published, communicated, and enforced'], callout: 'Real policy is rarely adopted as first drafted. The amendment process is where policies become practical, balanced, and widely supported.' },
    { type: 'concept', title: 'Effective Persuasion', body: 'Presenting a policy proposal requires combining logical argument, evidence, and rhetorical skill. The goal is not to win a debate but to build consensus.', bullets: ['Lead with the problem: Why does this policy need to exist? What harm does it prevent?', 'Present evidence: Data, case studies, and expert opinions strengthen your case', 'Anticipate objections: Address counter-arguments before your opponents raise them', 'Propose, do not impose: Frame your policy as a collaborative solution, not a diktat', 'Concede gracefully: Accepting reasonable amendments builds credibility and support'], callout: 'The most persuasive speakers acknowledge the strongest argument against their position and explain why, on balance, their proposal is still the right choice.' },
    { type: 'activity', title: 'The Ratification Session', instructions: 'Present your group\'s AI policy to the class, debate amendments, and vote to ratify.', steps: ['Each group has 5 minutes to present their AI policy draft', 'After each presentation, the class has 5 minutes for questions and proposed amendments', 'Amendments are written on the board — each requires a seconder', 'The presenting group can accept or reject each amendment (with reasoning)', 'After all presentations, the class votes on which policy to adopt (or combines the best elements)', 'The ratified policy is finalised and the class signs it as a collective agreement'] },
    { type: 'discussion', title: 'Democracy and Technology', questions: [{ num: 1, text: 'Is democratic policy-making too slow for fast-moving technology? Should we give experts more power to decide?' }, { num: 2, text: 'How did the debate and amendment process change your original policy? Was it improved?' }, { num: 3, text: 'Should students have a genuine say in their school\'s AI policy, or should this be decided by leadership?' }] },
    { type: 'quiz', question: 'Why is democratic involvement in policy creation important, beyond fairness?', options: ['It makes the process faster', 'People follow policies they helped create — it builds compliance', 'It eliminates the need for enforcement', 'It guarantees the best policy outcome'], correct: 1, explanation: 'Research shows that people are significantly more likely to follow policies they had a voice in creating. Democratic involvement builds ownership, understanding, and buy-in — not just legitimacy.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🗳️', label: 'Democracy is messy', text: 'Policy ratification involves presentation, debate, amendment, and compromise — not just voting' }, { icon: '🎤', label: 'Persuasion matters', text: 'Effective policy advocacy combines evidence, logic, and the ability to build consensus' }, { icon: '📜', label: 'Ownership through process', text: 'People follow policies they helped create — democratic involvement builds buy-in and compliance' }] }
  ]

};
