/* ── Curated Slide Content: Units 5 & 6 (Lessons 21-44) ── */

var SLIDES_U5U6 = {

  21: [
    { type: 'hook', title: 'From Consumer to Co-Creator', body: 'Until now, you have been consumers of AI — using ChatGPT, generating images, running searches. From today, you become co-creators. Your capstone project is your opportunity to build something original with AI: a tool, a system, or a solution that addresses a real problem. The best capstone projects from previous cohorts have included AI-powered revision tools, ethical audit frameworks, and community information systems. What will you create?' },
    { type: 'concept', title: 'The Capstone Brief', body: 'Your capstone project is the centrepiece of this course. Understanding the requirements now will set you up for success across the next 16 lessons.', bullets: ['Choose a real problem that AI can help solve — it must matter to someone', 'Build a working prototype or detailed design that demonstrates your solution', 'Apply ethical considerations from the ground up — not as an afterthought', 'Document your process in a sprint diary — decisions, blockers, and reflections', 'Present your work in a pitch-style presentation with Q&A', 'Complete a reflective essay connecting your project to course themes'], callout: 'The capstone is assessed on process as much as product. A well-documented failed experiment can score higher than an undocumented success.' },
    { type: 'concept', title: 'Shifting Your Mindset', body: 'Moving from consumer to creator requires a fundamental shift in how you think about AI. Creators ask different questions than consumers.', bullets: ['Consumer mindset: "What can AI do for me?" Creator mindset: "What can I build with AI?"', 'Consumers accept default outputs. Creators design systems that produce specific, reliable results', 'Consumers use one tool. Creators combine tools, APIs, and custom prompts into workflows', 'Consumers focus on single interactions. Creators think about user experience, edge cases, and failure modes', 'Every professional field increasingly needs people who can design AI-enhanced workflows — this is that skill'], callout: 'You do not need to be a programmer to be an AI creator. Prompt engineering, workflow design, and ethical analysis are all creation skills.' },
    { type: 'activity', title: 'Project Brainstorm', instructions: 'Generate at least 10 potential capstone project ideas using structured brainstorming techniques.', steps: ['Solo brainstorm (5 min): Write down every problem you encounter in daily life that AI could help solve', 'Category scan: Consider problems in education, health, environment, accessibility, community, and creative arts', 'Pair share: Discuss your ideas with a partner — add to each other\'s lists', 'Feasibility filter: For each idea, rate Feasibility (1-5) and Impact (1-5)', 'Shortlist your top 3 ideas based on combined feasibility and impact scores', 'Share your top idea with the class for initial feedback'] },
    { type: 'discussion', title: 'What Makes a Great Project?', questions: [{ num: 1, text: 'What is the difference between a project that uses AI and a project that needs AI? Which should your capstone be?' }, { num: 2, text: 'Should you choose a project you are passionate about or one that is technically impressive? Can you have both?' }, { num: 3, text: 'How will you balance ambition with feasibility given the time constraints?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🚀', label: 'Creator mindset', text: 'Shift from asking what AI can do for you to asking what you can build with AI' }, { icon: '📋', label: 'Process matters', text: 'Your capstone is assessed on documentation and reflection, not just the final product' }, { icon: '💡', label: 'Start with the problem', text: 'The best projects solve real problems for real people — technology comes second' }] }
  ],

  22: [
    { type: 'hook', title: 'Defining the Problem Statement', body: 'Einstein allegedly said: "If I had an hour to solve a problem, I would spend 55 minutes thinking about the problem and 5 minutes thinking about solutions." Most failed projects do not fail because of bad solutions — they fail because they solved the wrong problem. A clear problem statement is the foundation of everything that follows. Get this right and the rest flows naturally. Get it wrong and no amount of brilliant coding will save you.' },
    { type: 'concept', title: 'Anatomy of a Problem Statement', body: 'A strong problem statement is specific, measurable, and focused on the problem — not the solution. It answers who is affected, what the problem is, and why it matters.', bullets: ['Who: Identify the specific group affected — "Year 12 students" not "people"', 'What: Describe the problem precisely — "struggle to find relevant revision resources" not "have trouble revising"', 'Why it matters: Quantify the impact if possible — "leading to 15% lower average grades in mock exams"', 'Scope boundary: What is included and excluded — "this project focuses on biology A-Level, not all subjects"', 'Do NOT include the solution in your problem statement — that comes later'], callout: 'Weak: "Students need better AI tools." Strong: "Year 12 biology students at UK state schools spend an average of 3 hours per week searching for revision resources, with 60% reporting they cannot find materials matched to their exam board."' },
    { type: 'concept', title: 'Validating Your Problem', body: 'A problem statement is only as good as the evidence behind it. Before committing to a project, you need to validate that the problem is real, significant, and solvable.', bullets: ['Primary research: Survey or interview at least 5 people who experience the problem', 'Secondary research: Find statistics, studies, or reports that confirm the problem exists at scale', 'Competitor analysis: What solutions already exist? Why are they insufficient?', 'Feasibility check: Can you realistically address this problem with available tools and time?', 'The "so what" test: If you solved this problem, would anyone notice? Would anyone care?'], callout: 'If you cannot find anyone who cares about your problem, it is probably not the right problem to solve. Validation saves weeks of wasted effort.' },
    { type: 'activity', title: 'Write Your Problem Statement', instructions: 'Craft your capstone problem statement using the Capstone Project Brief Template from Resources.', steps: ['Open the Capstone Project Brief Template', 'Write a first draft of your problem statement using the Who-What-Why framework', 'Apply the "so what" test — does your problem matter enough to spend 16 lessons on?', 'Identify 3 pieces of evidence that validate your problem (survey your classmates if needed)', 'Revise your problem statement based on the evidence', 'Read it to a partner — can they explain the problem back to you clearly?'] },
    { type: 'discussion', title: 'Problem Framing', questions: [{ num: 1, text: 'How does the way you frame a problem influence the solutions you consider? Can framing introduce bias?' }, { num: 2, text: 'What is the risk of falling in love with a solution before properly defining the problem?' }, { num: 3, text: 'How would you validate a problem that affects a group you do not personally belong to?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎯', label: 'Problem first', text: 'A clear problem statement is the foundation — spend 55 minutes on the problem, 5 on the solution' }, { icon: '📊', label: 'Validate with evidence', text: 'Survey users, find data, check competitors — never assume a problem exists without proof' }, { icon: '✍️', label: 'Who-What-Why', text: 'Specific audience, precise problem, measurable impact, clear scope boundary' }] }
  ],

  23: [
    { type: 'hook', title: 'Ethics by Design', body: 'In 2023, a university student built an AI study companion for their capstone. It worked brilliantly — until they realised it was storing every question students asked, including personal struggles with mental health, without any consent mechanism. The student had not considered ethics until after building the tool. Ethics by design means building ethical considerations into your project from day one — not bolting them on as an afterthought.' },
    { type: 'concept', title: 'Ethics by Design Principles', body: 'Ethics by design is a proactive approach that embeds ethical thinking into every stage of project development, from conception to deployment.', bullets: ['Privacy by default: Collect the minimum data necessary. If you do not need it, do not collect it', 'Transparency: Users should understand what your system does, how it works, and what data it uses', 'Fairness: Test your system with diverse users and inputs to identify bias before deployment', 'Accountability: Define who is responsible when things go wrong. Document decisions and reasoning', 'Consent: Users must actively opt in to data collection and understand what they are agreeing to', 'Reversibility: Can users undo actions, delete their data, and withdraw from your system?'], callout: 'It is 100x cheaper to build ethics in from the start than to retrofit it after launch. The student with the study companion had to rebuild the entire data layer.' },
    { type: 'concept', title: 'Identifying Potential Harms', body: 'Every AI project carries potential for unintended harm. A systematic approach to harm identification helps you anticipate and prevent problems.', bullets: ['Direct harm: Could your system give wrong advice, discriminate, or invade privacy?', 'Indirect harm: Could your system be misused for purposes you did not intend?', 'Exclusion harm: Does your system work equally well for all users, or does it exclude some groups?', 'Dependency harm: Could users become unhealthily dependent on your system?', 'Environmental harm: What is the computational cost of running your system?'], callout: 'The Ethics Audit Checklist from Resources provides a structured framework for identifying harms. Use it now, not after your project is built.' },
    { type: 'activity', title: 'Ethical Impact Assessment', instructions: 'Conduct a pre-build ethical impact assessment for your capstone project using the Ethics Audit Checklist.', steps: ['Open the Ethics Audit Checklist from Resources', 'For your capstone project, work through each section: Data Privacy, Bias, Transparency, Accountability, Environment, Accessibility, Misinformation', 'For each potential harm identified, write: The risk, the likelihood (High/Medium/Low), and your mitigation strategy', 'Identify the single biggest ethical risk in your project', 'Design at least one safeguard that is built into the system by default', 'Share your assessment with a partner for feedback'] },
    { type: 'discussion', title: 'Ethics and Innovation', questions: [{ num: 1, text: 'Does embedding ethics slow down innovation? Is that an acceptable trade-off?' }, { num: 2, text: 'Who should be responsible for the ethical impact of a student project — the student, the teacher, or the school?' }, { num: 3, text: 'Can you think of a product you use daily that clearly did NOT consider ethics by design? What went wrong?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🛡️', label: 'Build it in', text: 'Ethics by design is 100x cheaper than retrofitting — embed ethical thinking from day one' }, { icon: '⚠️', label: 'Anticipate harms', text: 'Direct, indirect, exclusion, dependency, and environmental harms must all be considered' }, { icon: '📋', label: 'Use the checklist', text: 'The Ethics Audit Checklist provides a systematic framework for pre-build harm identification' }] }
  ],

  24: [
    { type: 'hook', title: 'Project Planning & Architecture', body: 'Software projects that skip planning are 3x more likely to fail, take 2x longer, and cost 4x more to fix. Yet most student projects jump straight to building. Today you will create a structured project plan with sprints, milestones, and a technical architecture that will keep you on track across the next 12 build sessions. The plan is not a bureaucratic exercise — it is your map through the wilderness.' },
    { type: 'concept', title: 'Sprint-Based Planning', body: 'Agile sprint methodology breaks large projects into small, manageable chunks — typically 1-2 week cycles. Each sprint has a clear goal, defined tasks, and a deliverable.', bullets: ['Sprint 0 (Foundation): Set up infrastructure, core functionality, testing approach', 'Sprint 1 (Core features): Build the minimum viable product (MVP)', 'Sprint 2 (Refinement): Integrate feedback, fix issues, add secondary features', 'Sprint 3 (Polish): User experience, testing, documentation, audit preparation', 'Each sprint ends with a review: What was completed? What blocked progress? What changes for next sprint?', 'Use the Sprint Diary Template from Resources to track daily and weekly progress'], callout: 'The most common student mistake is trying to build everything in Sprint 0. An MVP that works is better than a full-featured project that crashes.' },
    { type: 'concept', title: 'Technical Architecture', body: 'Before writing a line of code or crafting a single prompt, map out how the pieces of your project fit together. This is your technical architecture.', bullets: ['Inputs: What goes into your system? User text, uploaded files, API data, sensor readings?', 'Processing: What does your system do with the inputs? AI analysis, prompt chains, data transformation?', 'Outputs: What does the user receive? Text, visuals, recommendations, reports?', 'Data flow: How does information move through your system from input to output?', 'Dependencies: What external services, APIs, or tools does your project rely on?', 'Draw it out: A simple boxes-and-arrows diagram is worth a thousand words of description'], callout: 'If you cannot draw your system on a whiteboard in 2 minutes, it is too complicated. Simplify until you can.' },
    { type: 'activity', title: 'Build Your Project Plan', instructions: 'Create a sprint-based project plan and technical architecture diagram for your capstone.', steps: ['Open the Capstone Project Brief Template and Sprint Diary Template from Resources', 'Define your MVP — the simplest version of your project that demonstrates the core idea', 'Break the MVP into tasks and assign them to Sprint 0 (Foundation) and Sprint 1 (Core)', 'List Sprint 2 and Sprint 3 goals (these may change as you learn more)', 'Draw your technical architecture: Inputs, Processing, Outputs, Dependencies', 'Set 3 measurable milestones with dates — how will you know if you are on track?'] },
    { type: 'discussion', title: 'Planning and Reality', questions: [{ num: 1, text: 'Why do so many projects skip the planning phase? What makes jumping to building so tempting?' }, { num: 2, text: 'How detailed should a plan be? At what point does planning become procrastination?' }, { num: 3, text: 'What will you do when your plan inevitably meets reality and something does not work as expected?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📅', label: 'Sprint methodology', text: 'Break your project into 4 sprints with clear goals — Foundation, Core, Refinement, Polish' }, { icon: '🏗️', label: 'Architecture first', text: 'Map inputs, processing, outputs, and dependencies before you build anything' }, { icon: '🎯', label: 'MVP mindset', text: 'Build the simplest version that works first, then iterate — perfection is the enemy of progress' }] }
  ],

  25: [
    { type: 'hook', title: 'Applying Prompt Architecture', body: 'A single well-designed prompt can transform a chatbot from a generic question-answerer into a specialised expert tutor, medical triage assistant, or legal research tool. The PTFC framework you learned in Lesson 9 was training wheels. Today, you apply it at production scale — designing prompt systems that are reliable, consistent, and robust enough for real users to depend on.' },
    { type: 'concept', title: 'From Single Prompts to Prompt Systems', body: 'Production AI systems rarely rely on a single prompt. They use chains, templates, and dynamic prompts that work together as a system.', bullets: ['System prompts: Define the AI\'s role, personality, and constraints — persist across the conversation', 'User prompt templates: Structured templates that insert user input into a well-designed prompt', 'Prompt chains: Multiple prompts in sequence — output of one becomes input to the next', 'Guardrails: Instructions that prevent the AI from going off-topic, generating harmful content, or hallucinating', 'Few-shot examples: Including example inputs and desired outputs in the prompt to guide the model'], callout: 'ChatGPT\'s custom instructions are a system prompt. When you create a custom GPT, you are designing a prompt system. This is what professionals do.' },
    { type: 'concept', title: 'Testing Prompts Systematically', body: 'Production prompts must be tested like software. A prompt that works for one input might fail catastrophically for another.', bullets: ['Happy path testing: Does the prompt work with typical, expected inputs?', 'Edge case testing: What happens with unusual, extreme, or ambiguous inputs?', 'Adversarial testing: Can a user deliberately make the system produce harmful or wrong output?', 'Consistency testing: Does the same input produce similar quality output across multiple runs?', 'Regression testing: When you change one prompt, do other prompts in the chain still work?'], callout: 'Keep a Prompt Iteration Log (from Resources) for every prompt in your system. Record the version, what changed, and the test results. This documentation is gold during your viva.' },
    { type: 'activity', title: 'Design Your Prompt System', instructions: 'Design the prompt architecture for your capstone project. Create, test, and document at least 3 prompts.', steps: ['Identify every point in your project where AI is used — list each as a "prompt slot"', 'For each slot, write a PTFC prompt including system-level instructions', 'Design at least one prompt chain where output feeds into the next prompt', 'Test each prompt with 3 different inputs: typical, edge case, and adversarial', 'Record all prompts and test results in your Prompt Iteration Log', 'Refine any prompt that fails edge case or adversarial testing'] },
    { type: 'discussion', title: 'Prompt Engineering as a Profession', questions: [{ num: 1, text: 'Is prompt engineering a genuine professional skill or a temporary novelty that will disappear as AI improves?' }, { num: 2, text: 'How do you ensure prompt-based systems are reliable enough for real users to depend on?' }, { num: 3, text: 'What ethical responsibilities come with designing prompts that shape how AI interacts with people?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '⛓️', label: 'Prompt systems', text: 'Production AI uses chains, templates, and guardrails — not isolated single prompts' }, { icon: '🧪', label: 'Test systematically', text: 'Happy path, edge case, adversarial, consistency, and regression testing for every prompt' }, { icon: '📝', label: 'Document everything', text: 'A prompt iteration log is essential for tracking what works and defending your design choices' }] }
  ],

  26: [
    { type: 'hook', title: 'Logic Flows & Edge Cases', body: 'In 2014, a self-driving car encountered a cyclist balancing on one wheel at an intersection. The car\'s logic had no rule for this — it froze, unable to decide if the cyclist was moving or stationary. Edge cases like this are not rare exceptions; they are the reason most AI projects fail in the real world. Today, you will map the logic flows of your capstone and hunt for the edge cases that could break it.' },
    { type: 'concept', title: 'Logic Flow Design', body: 'A logic flow diagram maps every decision point in your system, showing what happens at each step and which paths the system can take.', bullets: ['Start with the user\'s entry point — what is the first thing they do?', 'Map every decision: If X then Y, else Z', 'Include error paths — what happens when something goes wrong?', 'Identify loops — can the user get stuck in a cycle?', 'Mark exit points — how does the user finish or leave the system?', 'Use standard flowchart symbols: rectangles for processes, diamonds for decisions, arrows for flow'], callout: 'If your logic flow has more than 15 steps, your system is too complex. Simplify until each path is clear and testable.' },
    { type: 'concept', title: 'Hunting Edge Cases', body: 'Edge cases are unusual inputs or situations that your system was not explicitly designed to handle. They are where most real-world failures occur.', bullets: ['Empty input: What happens if the user submits nothing?', 'Extreme input: Very long text, special characters, numbers where text is expected', 'Ambiguous input: Queries your system could interpret multiple ways', 'Adversarial input: Users deliberately trying to break or trick your system', 'Context mismatch: Users using your system for a purpose you did not intend', 'Failure cascades: What happens if an external API your system depends on goes down?'], callout: 'Professional developers spend 40% of their time on edge cases. Students typically spend 5%. This is the single biggest quality gap between amateur and professional work.' },
    { type: 'activity', title: 'Map and Break', instructions: 'Draw the logic flow of your capstone project, then systematically try to break it by finding edge cases.', steps: ['Draw the complete logic flow of your project on paper or a whiteboard', 'Trace through 3 typical user journeys — does the flow work for each?', 'List 10 edge cases specific to your project (use the categories above)', 'For each edge case, determine: Does your system handle it? How?', 'Identify the 3 most critical edge cases — the ones most likely to occur', 'Design a handling strategy for each: graceful error message, default behaviour, or prevention'] },
    { type: 'discussion', title: 'Designing for Failure', questions: [{ num: 1, text: 'Is it better to have a system that handles edge cases gracefully or one that prevents them from occurring? Can you do both?' }, { num: 2, text: 'How do you decide which edge cases are worth handling and which are too unlikely to worry about?' }, { num: 3, text: 'What is the difference between a system that fails silently and one that fails loudly? Which is more dangerous?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔀', label: 'Map every path', text: 'Logic flow diagrams reveal decision points, error paths, and loops before you build' }, { icon: '🔨', label: 'Break it first', text: 'Hunting edge cases before building saves enormous time and prevents embarrassing failures' }, { icon: '⚡', label: 'Handle failures gracefully', text: 'Every system fails — the question is whether it fails in a way the user can recover from' }] }
  ],

  27: [
    { type: 'hook', title: 'Sprint 0 — The Foundation', body: 'Every skyscraper starts with foundations. You cannot see them from the street, but they determine whether the building stands or falls. Sprint 0 is your foundation: the infrastructure, core functionality, and testing approach that everything else depends on. Today you start building. The goal is not a finished product — it is a solid base that you can build on confidently.' },
    { type: 'concept', title: 'Sprint 0 Goals', body: 'Sprint 0 is about establishing the foundations. Do not try to build features — focus on the infrastructure that makes features possible.', bullets: ['Set up your development environment and tools', 'Implement the absolute core functionality — the one thing your project must do', 'Establish a testing approach: How will you know if something works?', 'Create your project structure and file organisation', 'Set up version control or a backup system for your work', 'Begin your Sprint Diary — document every decision and the reasoning behind it'], callout: 'Sprint 0 success metric: By the end of today, your project should do one thing — however simple — and you should be able to demonstrate it.' },
    { type: 'concept', title: 'Working Effectively', body: 'Build sessions are most productive when you work with structure and discipline. These habits separate productive builders from frustrated ones.', bullets: ['Start with a 5-minute plan: Write down exactly what you will accomplish this session', 'Work in 25-minute focused blocks (Pomodoro technique) with 5-minute breaks', 'When stuck for more than 10 minutes, ask for help — do not burn time being stuck', 'Document as you go — notes written now save hours of confusion later', 'Test frequently — every 15-20 minutes, check that what you built still works', 'End with a 5-minute review: What did you accomplish? What will you do next session?'], callout: 'Write in your Sprint Diary at the end of every session. Future-you will thank present-you when it comes time for the reflective essay and viva.' },
    { type: 'activity', title: 'Build Session', instructions: 'Your first structured build session. Set up your project foundations and implement core functionality.', steps: ['5-min plan: Write down your 3 goals for this session', 'Set up your project environment (files, tools, accounts)', 'Implement your core functionality — the simplest possible version', 'Test it: Does it work? Document the result', 'If it works: Push further. If not: Debug, document the issue, ask for help if stuck', 'End-of-session review: Update your Sprint Diary with what you did, learned, and plan next'] },
    { type: 'discussion', title: 'Building Habits', questions: [{ num: 1, text: 'What was the hardest part of today\'s build session? How could you make it easier next time?' }, { num: 2, text: 'Did you write in your Sprint Diary? If not, what stopped you? How will you build this habit?' }, { num: 3, text: 'What is the current biggest risk to your project succeeding?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🏗️', label: 'Foundations first', text: 'Sprint 0 is about infrastructure and core functionality, not features' }, { icon: '📓', label: 'Document everything', text: 'Sprint Diary entries now save hours of confusion later and strengthen your reflective essay' }, { icon: '⏱️', label: 'Work with structure', text: 'Plan, build in focused blocks, test frequently, review at the end' }] }
  ],

  28: [
    { type: 'hook', title: 'Initial Peer Review', body: 'The most effective teams at companies like Google, Pixar, and SpaceX have one thing in common: a culture of candid feedback. Research shows that projects receiving structured peer feedback in early stages are 60% more likely to succeed. Today, you will give and receive honest, constructive feedback on your Sprint 0 work. This is not about being nice — it is about making each other\'s projects better.' },
    { type: 'concept', title: 'Giving Effective Feedback', body: 'Good feedback is specific, actionable, and balanced. It focuses on the work, not the person, and provides a clear path to improvement.', bullets: ['Be specific: "The input validation is missing" not "It needs work"', 'Be actionable: Every criticism should come with a suggestion for improvement', 'Balance: Start with what works well, then address what needs improvement', 'Focus on impact: How does the issue affect the user experience or project goals?', 'Ask questions: "Have you considered...?" is often more useful than "You should..."', 'Use the Peer Review Feedback Form from Resources for structure'], callout: 'The most valuable feedback is the hardest to give and hear. "This is great" is pleasant but useless. "Your error handling does not cover empty inputs, which could crash the system" is uncomfortable but invaluable.' },
    { type: 'concept', title: 'Receiving and Processing Feedback', body: 'How you receive feedback determines whether it improves your project. Defensiveness is natural but counterproductive.', bullets: ['Listen fully before responding — do not formulate rebuttals while the other person is talking', 'Ask clarifying questions: "Can you give me an example of what you mean?"', 'Take notes — you will not remember specific feedback an hour later', 'Separate your ego from your project — criticism of your work is not criticism of you', 'Triage: Not all feedback is equally important. Identify what to act on now, later, or never', 'Thank the reviewer — they invested time and thought in helping you improve'], callout: 'You do not have to implement every piece of feedback. But you should be able to explain why you chose not to act on a specific suggestion.' },
    { type: 'activity', title: 'Peer Review Session', instructions: 'Give and receive structured feedback on Sprint 0 deliverables using the Peer Review Feedback Form.', steps: ['Pair up with someone working on a different project', 'Demo your project (5 minutes): Show what you built, explain your architecture, and identify known issues', 'Your reviewer completes the Peer Review Feedback Form (10 minutes)', 'Discuss the feedback together (5 minutes) — ask clarifying questions', 'Swap roles and repeat', 'Write an action plan: Top 3 changes based on feedback, with priority order'] },
    { type: 'discussion', title: 'Feedback Culture', questions: [{ num: 1, text: 'Was it harder to give honest feedback or receive it? Why?' }, { num: 2, text: 'Did any feedback surprise you — something you had not noticed about your own project?' }, { num: 3, text: 'How can you build a habit of seeking feedback regularly rather than waiting for formal review sessions?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '💬', label: 'Specific and actionable', text: 'Good feedback names the issue, explains its impact, and suggests a solution' }, { icon: '👂', label: 'Listen before reacting', text: 'Separate ego from work — feedback on your project is not feedback on your worth' }, { icon: '📋', label: 'Triage and act', text: 'Not all feedback is equal — prioritise what to address now, later, or not at all' }] }
  ],

  29: [
    { type: 'hook', title: 'Deep Work Session 1', body: 'Cal Newport defines deep work as "professional activities performed in a state of distraction-free concentration that push your cognitive capabilities to their limit." Research shows that it takes an average of 23 minutes to regain focus after a distraction. In a 60-minute session, a single phone notification could cost you 40% of your productive time. Today, commit to deep work.' },
    { type: 'concept', title: 'Session Focus: Building Core Features', body: 'This is your first extended build session. The focus is making meaningful progress on your capstone while maintaining documentation discipline.', bullets: ['Review your Sprint Diary from last session — what did you plan to do today?', 'Set 2-3 specific, achievable goals for this session', 'Integrate the top priority feedback from your peer review', 'Test as you build — do not wait until the end to discover something is broken', 'If you hit a blocker, document it and move to a different task — do not lose momentum', 'Update your Sprint Diary before the session ends'], callout: 'Progress is rarely linear. Some sessions you will accomplish twice what you planned. Others you will spend the entire time debugging one issue. Both are normal.' },
    { type: 'activity', title: 'Deep Work Build', instructions: 'Extended build session with structured check-ins.', steps: ['5-min plan: Review Sprint Diary, set today\'s goals, identify potential blockers', '20-min build block 1: Work on your highest priority task', 'Quick check-in: Are you on track? Need help? Adjust if needed', '20-min build block 2: Continue building or move to next task', 'Quick check-in: Test what you have built so far', '10-min close: Update Sprint Diary with progress, blockers, and next steps'] },
    { type: 'discussion', title: 'Progress Check', questions: [{ num: 1, text: 'What did you accomplish today that you are most proud of?' }, { num: 2, text: 'What was your biggest blocker and how did you handle it?' }, { num: 3, text: 'On a scale of 1-10, how confident are you that your project will be ready on time?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎯', label: 'Goals and focus', text: 'Set specific goals, work in focused blocks, and eliminate distractions' }, { icon: '📓', label: 'Document as you go', text: 'Sprint Diary entries are evidence for your reflective essay and viva' }, { icon: '🔄', label: 'Adapt and continue', text: 'Hit a blocker? Document it, move to another task, and come back later' }] }
  ],

  30: [
    { type: 'hook', title: 'Deep Work Session 2', body: 'Feedback is only valuable if you act on it. Studies show that teams who integrate feedback within 48 hours see 3x the improvement compared to those who wait a week. Today\'s focus is integrating the feedback from your peer review and resolving any issues identified. Your project should visibly improve by the end of this session.' },
    { type: 'concept', title: 'Session Focus: Integrating Feedback', body: 'Today\'s priority is acting on the peer review feedback and resolving identified issues. This is where good projects become great.', bullets: ['Review your peer review action plan — what were your top 3 priorities?', 'Start with the highest-impact change that is achievable in this session', 'Test each change after implementing it — does it actually solve the issue?', 'If a suggested change conflicts with your design, document why you chose not to implement it', 'Look for patterns in the feedback — if multiple reviewers flagged the same issue, prioritise it', 'Update your Sprint Diary with what you changed and why'], callout: 'Being able to explain why you accepted or rejected specific feedback demonstrates critical thinking — this is exactly what your viva will assess.' },
    { type: 'activity', title: 'Feedback Integration Build', instructions: 'Focused build session on integrating peer review feedback and advancing core features.', steps: ['5-min plan: Review peer review action plan and prioritise changes', '20-min build block 1: Implement highest priority feedback change', 'Quick test: Does the change work? Does it break anything else?', '20-min build block 2: Continue with next priority or advance core features', 'Quick test: Run through your main user journey — does everything still work?', '10-min close: Update Sprint Diary — note what feedback was implemented and any decisions made'] },
    { type: 'discussion', title: 'Feedback in Action', questions: [{ num: 1, text: 'Which piece of feedback had the biggest positive impact on your project?' }, { num: 2, text: 'Did you choose not to implement any feedback? What was your reasoning?' }, { num: 3, text: 'What would you ask your next reviewer to focus on?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔧', label: 'Act on feedback quickly', text: 'Teams who integrate feedback within 48 hours see 3x the improvement' }, { icon: '🧠', label: 'Think critically', text: 'Accept, reject, or adapt feedback — but always document your reasoning' }, { icon: '✅', label: 'Test after every change', text: 'Every modification should be tested to ensure it solves the issue without creating new ones' }] }
  ]

};
