/* ── Curated Slide Content: Units 3 & 4 (Lessons 13-20) ── */

var SLIDES_U3U4 = {

  13: [
    { type: 'hook', title: 'Deepfakes and Disinformation', body: 'In 2024, a deepfake video of a multinational CEO announcing fake earnings wiped $25 billion from the company\'s stock price in 12 minutes before it was identified as synthetic. In the same year, AI-generated audio of a political leader was shared 50 million times before fact-checkers could respond. Deepfake technology has advanced from obvious fakes to near-perfect synthetic media — and detection is losing the arms race against generation.' },
    { type: 'concept', title: 'How Deepfakes Work', body: 'Deepfakes use deep learning — specifically generative adversarial networks (GANs) and diffusion models — to create synthetic media that is increasingly indistinguishable from authentic content.', bullets: ['GANs pit two neural networks against each other: a generator creates fakes, a discriminator tries to detect them', 'Each iteration improves both — the generator makes better fakes and the discriminator gets sharper', 'Face-swapping: Maps one person\'s facial expressions onto another\'s face in video', 'Voice cloning: Models can now clone a voice from as little as 3 seconds of audio', 'Text-to-video: Tools like Sora can generate photorealistic video from text descriptions'], callout: 'In 2019, creating a convincing deepfake required hours of footage and expensive hardware. Today, free apps can do it from a single photo in minutes.' },
    { type: 'concept', title: 'Detection and Defence', body: 'As deepfakes improve, detection methods struggle to keep pace. A multi-layered approach combining technology and media literacy is essential.', bullets: ['Technical detection: AI models trained to spot artefacts — blinking patterns, skin texture inconsistencies, lighting anomalies', 'Provenance tracking: C2PA standard embeds cryptographic metadata proving where and when content was captured', 'Watermarking: Invisible digital watermarks embedded in AI-generated content (Google SynthID, OpenAI metadata)', 'Media literacy: Teaching people to question source, context, and plausibility before sharing', 'The arms race problem: Every detection method becomes training data for better deepfakes'], callout: 'Current deepfake detectors achieve about 65-85% accuracy on the latest generation models — barely better than a coin flip on the most sophisticated fakes.' },
    { type: 'activity', title: 'Spot the Fake', instructions: 'Use the Deepfake Detection Checklist from Resources to analyse a set of real and synthetic media samples.', steps: ['Your teacher will provide 6 media samples — some real, some AI-generated', 'For each sample, work through the Deepfake Detection Checklist systematically', 'Look for: unnatural blinking, inconsistent lighting, warped edges, audio-lip sync issues', 'Record your verdict for each: Real, Fake, or Unsure', 'Compare results with the class — what was your accuracy rate?', 'Discuss: Which fakes were hardest to detect and why?'] },
    { type: 'discussion', title: 'Truth in a Post-Truth World', questions: [{ num: 1, text: 'If anyone can create convincing fake video of anyone saying anything, what happens to the concept of evidence?' }, { num: 2, text: 'Should creating deepfakes be illegal, or only sharing them? How would you enforce such a law?' }, { num: 3, text: 'The "liar\'s dividend": Now that deepfakes exist, real video can be dismissed as fake. How do we combat this?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎭', label: 'Technology is advancing fast', text: 'Deepfakes now require minimal source material and can be created with free tools in minutes' }, { icon: '🔍', label: 'Detection is struggling', text: 'AI detectors achieve 65-85% accuracy — provenance standards and media literacy are essential complements' }, { icon: '⚠️', label: 'Societal risk', text: 'Deepfakes threaten elections, financial markets, personal reputations, and the very concept of evidence' }] }
  ],

  14: [
    { type: 'hook', title: 'Surveillance and Facial Recognition', body: 'London has over 940,000 CCTV cameras — one for every 10 residents. China\'s SkyNet system covers over 600 million cameras with real-time facial recognition. In 2020, Robert Williams, a Black man in Detroit, was wrongfully arrested after facial recognition software misidentified him. He spent 30 hours in custody for a crime he did not commit. The technology promises safety but delivers a complex trade-off between security and civil liberties.' },
    { type: 'concept', title: 'How Facial Recognition Works', body: 'Facial recognition systems convert faces into mathematical representations (faceprints) and compare them against databases. The technology has improved dramatically but remains deeply flawed.', bullets: ['Detection: Identifies that a face exists in an image or video frame', 'Alignment: Normalises the face to a standard position and size', 'Feature extraction: Maps facial geometry — distance between eyes, jaw shape, nose bridge — into a numeric vector', 'Matching: Compares the faceprint against a database of known faces', 'Accuracy varies dramatically: 99.7% for white males, 65.3% for dark-skinned females (NIST 2019 study)'], callout: 'The performance gap is not a bug — it reflects training data that is overwhelmingly composed of lighter-skinned faces. Bias is baked into the technology.' },
    { type: 'concept', title: 'The Surveillance Debate', body: 'Facial recognition in public spaces creates a fundamental tension between collective security and individual privacy. Both sides make compelling arguments.', bullets: ['For surveillance: Prevents terrorism, finds missing persons, reduces crime, catches wanted criminals faster', 'Against surveillance: Creates chilling effects on free expression, protest, and movement', 'Function creep: Technology deployed for one purpose (e.g. counter-terrorism) inevitably expands to others', 'Disproportionate impact: Marginalised communities face higher false positive rates and heavier surveillance', 'Democratic accountability: Most surveillance systems are deployed without public consultation or consent'], callout: 'San Francisco banned government use of facial recognition in 2019. The EU AI Act classifies real-time facial recognition in public spaces as "high risk." The UK has no equivalent restriction.' },
    { type: 'activity', title: 'Surveillance Policy Design', instructions: 'Your group represents a city council deciding whether to deploy facial recognition cameras in your city centre. Use the Surveillance Debate Pack from Resources.', steps: ['Split into three teams: Security advocates, Civil liberties advocates, and the Council', 'Security team: Prepare a 3-minute case for deploying facial recognition with specific safeguards', 'Civil liberties team: Prepare a 3-minute case against deployment with alternative safety proposals', 'Both teams present to the Council', 'Council asks questions and deliberates', 'Council votes and announces their decision with reasoning'] },
    { type: 'discussion', title: 'Where Do You Draw the Line?', questions: [{ num: 1, text: 'Would you accept facial recognition in your school if it made the building safer? What about your neighbourhood?' }, { num: 2, text: 'If the accuracy gap between demographic groups cannot be fully closed, should the technology be deployed at all?' }, { num: 3, text: 'China uses facial recognition to monitor ethnic minorities in Xinjiang. At what point does surveillance become oppression?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📷', label: 'Unequal accuracy', text: 'Facial recognition error rates are up to 100x higher for dark-skinned women than light-skinned men' }, { icon: '⚖️', label: 'Security vs. liberty', text: 'Surveillance creates genuine safety benefits but risks chilling effects on protest, expression, and movement' }, { icon: '🏛️', label: 'Regulation varies wildly', text: 'From San Francisco\'s ban to China\'s mass deployment — no global consensus exists' }] }
  ],

  15: [
    { type: 'hook', title: 'The Environmental Cost', body: 'Training GPT-4 is estimated to have consumed as much electricity as 120 US homes use in an entire year. A single ChatGPT query uses roughly 10 times the energy of a Google search. By 2027, AI data centres could consume as much electricity as the Netherlands. At the same time, AI is being used to optimise energy grids, accelerate climate research, and design more efficient materials. Is AI a climate villain or a climate hero? The answer is: both.' },
    { type: 'concept', title: 'The Carbon Cost of AI', body: 'AI\'s environmental footprint comes from three sources: training models, running inference, and the hardware lifecycle. Each contributes significantly to carbon emissions.', bullets: ['Training: GPT-3 training emitted approximately 552 tonnes of CO2 — equivalent to 120 cars driving for a year', 'Inference: Running the model for users. ChatGPT serving 100 million users daily consumes enormous energy', 'Hardware: Manufacturing GPUs requires rare earth minerals, water, and energy-intensive fabrication', 'Data centres: Require massive cooling systems, often using millions of litres of water daily', 'The trend is accelerating: Each new generation of models is 5-10x larger than the last'], callout: 'Google\'s total carbon emissions rose 48% from 2019 to 2023, largely driven by AI infrastructure expansion.' },
    { type: 'concept', title: 'AI as Climate Solution', body: 'Despite its footprint, AI offers transformative potential for environmental sustainability. The question is whether the benefits outweigh the costs.', bullets: ['Energy grid optimisation: DeepMind reduced Google data centre cooling energy by 40% using AI', 'Climate modelling: AI can run climate simulations 100,000x faster than traditional methods', 'Materials science: AI accelerates discovery of better batteries, solar cells, and carbon capture materials', 'Agriculture: Precision farming using AI reduces water use by 30% and pesticide use by 50%', 'Deforestation monitoring: AI satellite analysis detects illegal logging in near real-time'], callout: 'The net equation: If AI\'s climate solutions save more emissions than AI itself produces, the technology is net-positive. But this is not guaranteed — it depends on how we deploy it.' },
    { type: 'activity', title: 'Carbon Calculator', instructions: 'Estimate the environmental impact of your personal AI use and propose a sustainability strategy. Use the AI Environmental Impact Factsheet from Resources.', steps: ['List every AI service you use regularly (ChatGPT, Copilot, Midjourney, etc.)', 'Using the Factsheet, estimate the energy per query for each service', 'Estimate your total queries per week and calculate your monthly AI carbon footprint', 'Research: What is your AI provider doing about sustainability?', 'Propose 3 changes you could make to reduce your AI environmental impact', 'Design a one-page "Sustainable AI Use" policy for your school'] },
    { type: 'discussion', title: 'The Green AI Dilemma', questions: [{ num: 1, text: 'Should AI companies be required to disclose the carbon footprint of their models? Should users see a "carbon cost" per query?' }, { num: 2, text: 'Is it ethical to train ever-larger models when smaller, more efficient models might be good enough?' }, { num: 3, text: 'If AI can solve climate change faster, does its own carbon cost become an acceptable trade-off?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '⚡', label: 'Massive energy use', text: 'AI training and inference consume enormous energy — GPT-4 training used as much as 120 homes for a year' }, { icon: '🌱', label: 'Climate solution potential', text: 'AI can optimise energy grids, accelerate materials discovery, and improve agriculture sustainability' }, { icon: '📊', label: 'Net impact uncertain', text: 'Whether AI helps or hurts the climate depends entirely on how we choose to deploy it' }] }
  ],

  16: [
    { type: 'hook', title: 'Global Regulation', body: 'The EU AI Act classifies AI systems by risk level and imposes strict requirements. The US takes a sector-by-sector approach with minimal federal legislation. The UK promotes a "pro-innovation" framework with voluntary guidelines. China requires algorithmic transparency and content labelling but uses AI extensively for state surveillance. Four major powers, four fundamentally different approaches. The rules governing AI depend entirely on where you live — and companies operating globally must navigate all of them.' },
    { type: 'concept', title: 'Four Regulatory Models', body: 'Understanding the major global approaches reveals fundamentally different philosophies about the role of government in technology governance.', bullets: ['EU AI Act (2024): Risk-based framework. Bans "unacceptable risk" uses (social scoring, real-time biometric surveillance). Requires transparency and human oversight for "high risk" systems', 'US approach: Sector-specific. No comprehensive federal AI law. Executive orders provide guidance. Industry self-regulation is the default', 'UK approach: Context-based, pro-innovation. No new AI-specific laws. Existing regulators (Ofcom, FCA, ICO) apply AI principles within their domains', 'China approach: Algorithmic regulation requires companies to register algorithms with the government. Content generated by AI must be labelled. Strong state control combined with aggressive AI development'], callout: 'The EU regulates to protect citizens. The US regulates to protect markets. The UK regulates to encourage innovation. China regulates to maintain state control.' },
    { type: 'concept', title: 'The Regulation Dilemma', body: 'Every regulatory approach involves trade-offs. Too little regulation risks harm; too much risks stifling innovation and falling behind competitors.', bullets: ['The Brussels Effect: EU regulations often become global standards because companies find it easier to comply everywhere than to maintain separate systems', 'Innovation vs. safety: Strict regulation may drive AI companies to relocate to less regulated jurisdictions', 'Speed mismatch: AI evolves in months; legislation takes years. Regulation is always playing catch-up', 'Enforcement challenge: How do you audit an algorithm? Who checks compliance? What are the penalties?', 'International coordination: Without global standards, companies can regulatory-shop for the friendliest jurisdiction'], callout: 'The EU AI Act took 3 years to negotiate. In that time, ChatGPT launched, AI art generators emerged, and deepfakes became mainstream. Regulation is always behind.' },
    { type: 'activity', title: 'Regulation Jigsaw', instructions: 'Using the Regulation Jigsaw Cards from Resources, become an expert on one regulatory approach and teach it to your group.', steps: ['Form groups of 4. Each person takes one jurisdiction: EU, US, UK, or China', 'Using the Jigsaw Cards, become an expert on your jurisdiction (10 minutes)', 'Return to your group and teach the others about your approach (3 minutes each)', 'As a group, create a comparison table: Strengths, Weaknesses, and Key Differences', 'Vote: Which approach would you adopt for a new country? Justify your choice', 'Present your group\'s recommendation to the class'] },
    { type: 'discussion', title: 'Governing the Ungovernable?', questions: [{ num: 1, text: 'Should there be a single global AI regulatory framework, similar to international aviation rules? Is this realistic?' }, { num: 2, text: 'The UK\'s pro-innovation approach means less protection but potentially more AI investment. Is this a good trade-off?' }, { num: 3, text: 'If you were designing AI regulation for the UK from scratch, what three rules would you prioritise?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🇪🇺', label: 'Four models', text: 'EU (risk-based), US (sector-specific), UK (pro-innovation), China (state-controlled) — fundamentally different philosophies' }, { icon: '⏱️', label: 'Speed mismatch', text: 'Technology evolves in months while legislation takes years — regulation is always catching up' }, { icon: '🌍', label: 'No global standard', text: 'Without international coordination, companies can choose the most permissive jurisdiction' }] }
  ],

  17: [
    { type: 'hook', title: 'Analysing the Status Quo', body: 'A 2024 survey found that 89% of UK universities now have an AI policy — but only 23% of students had actually read it. Meanwhile, 67% of students admitted to using AI tools regularly for coursework. The gap between policy and practice is enormous. Before you can write better policy, you need to understand what already exists, what works, and what fails. Today, you become policy auditors.' },
    { type: 'concept', title: 'Policy Audit Framework', body: 'Evaluating AI policies requires a structured approach. A good audit examines not just what a policy says, but how practical, enforceable, and fair it is.', bullets: ['Scope: What does the policy cover? Does it address all relevant AI tools or just some?', 'Clarity: Can a typical student or staff member understand the rules without legal training?', 'Enforceability: How are violations detected? What are the consequences? Are they proportionate?', 'Fairness: Does the policy affect all students equally, or does it disadvantage some groups?', 'Currency: When was it last updated? Does it cover tools that exist today?'], callout: 'Many school AI policies were written before ChatGPT launched in November 2022. A policy that does not mention generative AI is already outdated.' },
    { type: 'concept', title: 'Common Policy Gaps', body: 'Research reveals recurring weaknesses in existing AI policies across education. Identifying these patterns helps you build better alternatives.', bullets: ['Binary thinking: Policies that simply ban or allow AI, with no nuance for different use cases', 'Tool-specific rules: Banning ChatGPT by name rather than addressing the category of generative AI', 'No guidance on disclosure: Students do not know when or how to declare AI use', 'Assessment disconnect: Policies do not explain how AI use affects marking or academic integrity', 'Staff training gap: Policies for students but no guidance for teachers using AI in their work'], callout: 'The best policies focus on principles (transparency, academic integrity, critical thinking) rather than specific tools, because tools change faster than policies.' },
    { type: 'activity', title: 'Policy Audit Workshop', instructions: 'Audit a real university or school AI policy using the University AI Policy Comparison resource and the audit framework above.', steps: ['Your teacher will provide 2-3 real AI policies from UK universities or schools', 'Using the audit framework, score each policy on: Scope, Clarity, Enforceability, Fairness, and Currency', 'Rate each criterion from 1 (poor) to 5 (excellent) with written justification', 'Identify the top 3 strengths and top 3 weaknesses across all policies', 'Write 3 specific recommendations for improvement', 'Compare findings with another pair — did you identify the same issues?'] },
    { type: 'discussion', title: 'Policy in Practice', questions: [{ num: 1, text: 'Why do you think most students have not read their institution\'s AI policy? How could this be fixed?' }, { num: 2, text: 'Should AI policies be written by administrators, teachers, students, or all three? Why?' }, { num: 3, text: 'Is it possible to write an AI policy that is both strict enough to maintain academic integrity and flexible enough to encourage learning with AI?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📋', label: 'Audit before you build', text: 'Understanding what exists — and what fails — is essential before writing new policy' }, { icon: '🔍', label: 'Common gaps', text: 'Binary thinking, tool-specific bans, and missing disclosure guidance are recurring weaknesses' }, { icon: '🎯', label: 'Principles over tools', text: 'The best policies focus on values like transparency and integrity, not specific app names' }] }
  ]

};
