/* ── Curated Slide Content: Units 1 & 2 (Lessons 1-12) ── */

var SLIDES_U1U2 = {

  1: [
    { type: 'hook', title: 'Your AI Footprint', body: 'Before you even left the house this morning, AI had already made dozens of decisions for you. Your alarm clock app optimised your wake time, your email sorted itself overnight, your news feed was curated by recommendation algorithms, and your smart speaker checked the weather using natural language processing. A 2024 study found the average person interacts with AI-powered systems over 100 times per day — most without realising it. Today, we map your personal AI ecosystem.' },
    { type: 'concept', title: 'What Counts as AI?', body: 'Artificial intelligence is a broad term covering any system that performs tasks normally requiring human intelligence. This includes narrow AI (designed for specific tasks) and the aspiration of general AI (human-level reasoning across domains).', bullets: ['Rule-based systems: spam filters, autocorrect, sat-nav routing', 'Machine learning: Netflix recommendations, Spotify Discover Weekly', 'Deep learning: facial recognition, voice assistants, ChatGPT', 'Robotics & automation: warehouse robots, self-driving features', 'Generative AI: image generators, code assistants, text summarisers'], callout: 'Most AI you encounter daily is narrow AI — brilliant at one task but incapable of anything outside its training.' },
    { type: 'concept', title: 'Mapping Your AI Ecosystem', body: 'An AI ecosystem map categorises every AI interaction in your life by domain — communication, entertainment, education, health, finance, transport, and home. This audit reveals how dependent you are on algorithmic decision-making.', bullets: ['Communication: autocomplete, grammar check, translation, email sorting', 'Entertainment: recommendation engines, auto-generated playlists, content moderation', 'Education: adaptive learning platforms, plagiarism detectors, AI tutors', 'Health: fitness trackers, symptom checkers, sleep analysis', 'Finance: fraud detection, credit scoring, contactless payment authorisation'], callout: 'Awareness is the first step. You cannot evaluate what you do not notice.' },
    { type: 'activity', title: 'AI Audit Challenge', instructions: 'You have 15 minutes to audit your AI footprint. Use your phone, laptop and memory to catalogue every AI system you interact with in a typical day.', steps: ['Open a blank document or use the Skills Audit Template from Resources', 'List every app and device you used in the last 24 hours', 'For each one, identify whether it uses AI (search online if unsure)', 'Categorise each into: Communication, Entertainment, Education, Health, Finance, Transport, Home, or Other', 'Count your total — can you beat the class average?', 'Star any that surprised you'] },
    { type: 'discussion', title: 'Reflect on Your Footprint', questions: [{ num: 1, text: 'Were you surprised by how many AI systems you interact with daily? Which ones were you unaware of?' }, { num: 2, text: 'Could you go a full day without any AI assistance? What would be the hardest thing to give up?' }, { num: 3, text: 'Is our growing dependence on AI a cause for concern, or simply the next stage of technological progress?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔍', label: 'AI is everywhere', text: 'The average person interacts with AI 100+ times daily, mostly without realising' }, { icon: '🗺️', label: 'Mapping matters', text: 'Auditing your AI ecosystem builds critical awareness of algorithmic influence' }, { icon: '⚖️', label: 'Dependence vs convenience', text: 'Understanding reliance is the first step to making informed choices about AI in your life' }] }
  ],

  2: [
    { type: 'hook', title: 'The Parrot vs. The Librarian', body: 'In 2023, a ChatGPT user asked the model to name a legal case supporting their argument. The AI confidently cited three cases — complete with dates, courts, and judges. None of them existed. The lawyer who submitted these to court was fined $5,000. This raises a fundamental question: do large language models actually understand what they are saying, or are they just extraordinarily sophisticated parrots?' },
    { type: 'concept', title: 'The Stochastic Parrot', body: 'In a landmark 2021 paper, researchers Emily Bender, Timnit Gebru and colleagues coined the term "stochastic parrot" to describe large language models. The argument: LLMs are statistical pattern-matchers that predict the most probable next token in a sequence, without any genuine understanding of meaning.', bullets: ['LLMs are trained on billions of text tokens scraped from the internet', 'They learn statistical relationships between words and phrases', 'Output is generated probabilistically — the model predicts what word is most likely to come next', 'They have no world model, sensory experience, or grounded understanding', 'Fluency is not the same as comprehension — a parrot can say "fire" without understanding heat'], callout: 'The "stochastic" part means random with probability. The model does not choose words through reasoning — it samples from a probability distribution.' },
    { type: 'concept', title: 'The Librarian Argument', body: 'Others argue that LLMs have developed emergent capabilities that go beyond mere pattern matching. As models scale up in size and training data, they demonstrate reasoning, analogy, and even creativity that was not explicitly programmed.', bullets: ['GPT-4 can pass the bar exam, medical licensing exams, and AP tests', 'LLMs can solve novel problems they were never explicitly trained on', 'They demonstrate chain-of-thought reasoning when prompted correctly', 'Some researchers argue that sufficiently complex pattern-matching becomes functionally equivalent to understanding', 'The Chinese Room argument (Searle, 1980) asks: can following rules ever equal understanding?'], callout: 'This is not a settled debate. Leading AI researchers genuinely disagree about whether understanding can emerge from statistics alone.' },
    { type: 'activity', title: 'Test the Parrot', instructions: 'Design three prompts that test whether an AI truly understands or is just pattern matching. Try them on ChatGPT or another LLM and analyse the results.', steps: ['Write a prompt requiring genuine logical reasoning (e.g. a novel riddle)', 'Write a prompt requiring common sense about the physical world', 'Write a prompt with deliberate misinformation to see if the AI pushes back or agrees', 'Record the AI responses and classify each as: genuine understanding, impressive pattern matching, or clear failure', 'Share your most interesting finding with the class'] },
    { type: 'discussion', title: 'Understanding or Imitation?', questions: [{ num: 1, text: 'If an AI produces the same output as a human who understands, does the distinction matter? Why or why not?' }, { num: 2, text: 'What would convince you that an AI truly understands language rather than just predicting tokens?' }, { num: 3, text: 'Should it matter whether AI understands, as long as it is useful? What are the risks of not caring?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🦜', label: 'Stochastic parrots', text: 'LLMs predict probable next tokens — fluency does not equal understanding' }, { icon: '📚', label: 'Emergent abilities', text: 'Scale appears to unlock capabilities like reasoning and analogy, but the mechanism is debated' }, { icon: '🧪', label: 'Test claims carefully', text: 'Designing adversarial prompts reveals the boundaries of AI capabilities' }] }
  ],

  3: [
    { type: 'hook', title: 'How a Machine Learns (Unplugged)', body: 'Imagine you have never seen a cat in your life. Someone shows you 10,000 photos labelled "cat" and 10,000 labelled "not cat." After studying them, you start spotting patterns — pointy ears, whiskers, fur. Now someone shows you a brand new photo. You guess "cat" and you are right 95% of the time. Congratulations — you just did what a supervised learning algorithm does. Today, we walk through this process with zero computers.' },
    { type: 'concept', title: 'Training, Validation & Test Sets', body: 'Supervised learning requires labelled data split into three sets. Each serves a different purpose in building a reliable model.', bullets: ['Training set (typically 70-80%): The model learns patterns from this data', 'Validation set (10-15%): Used during training to tune the model and prevent overfitting', 'Test set (10-15%): Held back until the very end — the final exam the model has never seen', 'If you test on training data, you get a misleadingly high score — like marking your own homework', 'Real-world performance is only as good as the test set score'], callout: 'A model that memorises training data but fails on new data has overfit. It learned the noise, not the signal.' },
    { type: 'concept', title: 'Overfitting vs. Generalisation', body: 'The core tension in machine learning is between fitting the training data closely (low training error) and performing well on unseen data (low test error). A model that generalises has learned the true underlying patterns.', bullets: ['Overfitting: The model memorises specific examples rather than learning general rules', 'Underfitting: The model is too simple to capture the patterns in the data', 'The sweet spot: Complex enough to capture real patterns, simple enough to generalise', 'Think of it like revision — memorising past papers word-for-word versus understanding the concepts', 'Techniques like regularisation, dropout, and early stopping help prevent overfitting'], callout: 'In the unplugged activity, if your rules only work for the exact cards you trained on, you have overfit.' },
    { type: 'activity', title: 'Unplugged Machine Learning', instructions: 'Using a deck of cards sorted into categories, your team will build a classification model without any technology.', steps: ['Your teacher will provide a set of cards with features (colour, shape, number, pattern)', 'Split the cards into training (16 cards), validation (4 cards), and test (4 cards)', 'Study the training cards and write rules that predict the label from the features', 'Test your rules on the validation set — adjust if accuracy is below 75%', 'When ready, apply your final rules to the test set and record your accuracy', 'Compare your accuracy with other groups — who generalised best?'] },
    { type: 'discussion', title: 'From Cards to Code', questions: [{ num: 1, text: 'What happened when your training rules did not work well on the validation set? How did you adjust?' }, { num: 2, text: 'How is this card activity similar to how real ML models like image classifiers work?' }, { num: 3, text: 'Why is it important that the test set is only used once, at the very end?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📊', label: 'Three data splits', text: 'Training, validation, and test sets each serve a crucial role in building reliable models' }, { icon: '🎯', label: 'Generalisation is the goal', text: 'A good model learns patterns, not specific examples — it works on data it has never seen' }, { icon: '🔗', label: 'Same principles at scale', text: 'From card sorting to GPT-4, the fundamentals of supervised learning are identical' }] }
  ],

  4: [
    { type: 'hook', title: 'The Black Box', body: 'In 2018, Amazon scrapped an AI recruitment tool after discovering it systematically downgraded CVs containing the word "women\'s" — as in "women\'s chess club captain." The engineers could not fully explain why the model had learned this bias because the system was a black box. When AI makes decisions about hiring, healthcare, criminal justice, and finance, the inability to explain why becomes a serious problem.' },
    { type: 'concept', title: 'What is Interpretability?', body: 'Model interpretability refers to how easily a human can understand the reasoning behind a model\'s predictions. Some models are inherently interpretable; others require special techniques to peek inside.', bullets: ['Decision trees: Fully transparent — you can trace every decision step', 'Linear regression: Weights tell you exactly how much each feature contributes', 'Deep neural networks: Millions of parameters make reasoning opaque', 'The accuracy-interpretability trade-off: More complex models are often more accurate but harder to explain', 'Explainable AI (XAI) is a growing field dedicated to making black boxes transparent'], callout: 'A doctor needs to know WHY an AI flagged a scan as cancerous before acting on it. "Trust me" is not good enough in high-stakes decisions.' },
    { type: 'concept', title: 'Consequences of Opacity', body: 'When AI systems make consequential decisions without explanation, real harm can follow. Several high-profile cases illustrate why black boxes are dangerous.', bullets: ['COMPAS recidivism tool: Used in US courts to predict reoffending — found to be biased against Black defendants, but the algorithm was proprietary', 'Credit scoring: Applicants denied loans with no explanation beyond "the model decided"', 'Healthcare: IBM Watson recommended unsafe cancer treatments that doctors could not verify', 'Self-driving cars: When accidents occur, investigators struggle to determine why the AI acted as it did', 'The EU AI Act now requires explanations for high-risk AI decisions — regulation is catching up'], callout: 'The right to explanation is becoming a legal principle. The EU GDPR already gives citizens the right to meaningful information about automated decisions.' },
    { type: 'activity', title: 'Explain That Decision', instructions: 'Work in pairs. One person plays the AI, the other plays a person affected by the decision. The AI must try to explain its reasoning.', steps: ['Choose a scenario: loan application, job screening, university admission, or medical diagnosis', 'The "AI" secretly writes down 3 rules they use to make the decision', 'The affected person asks questions trying to understand why they were accepted or rejected', 'The "AI" can only answer with vague responses like "based on your profile" or "multiple factors"', 'Swap roles. Then discuss: How did it feel to receive an unexplainable decision?', 'Brainstorm: What minimum level of explanation should be required by law?'] },
    { type: 'discussion', title: 'Transparency vs. Performance', questions: [{ num: 1, text: 'Should we sacrifice some accuracy for interpretability in high-stakes decisions? Where is the line?' }, { num: 2, text: 'Companies argue that revealing their algorithms would expose trade secrets. Is this a valid reason for opacity?' }, { num: 3, text: 'If an AI makes a decision that harms someone, who is responsible when nobody can explain why it decided that way?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📦', label: 'Black boxes are risky', text: 'Complex models often cannot explain their reasoning, creating accountability gaps' }, { icon: '⚖️', label: 'Accuracy vs. transparency', text: 'There is a real trade-off — simpler models explain better but may perform worse' }, { icon: '📜', label: 'Regulation is coming', text: 'Laws like the EU AI Act increasingly require explainability for high-stakes AI' }] }
  ],

  5: [
    { type: 'hook', title: 'Bias In, Bias Out', body: 'In 2015, Google Photos tagged photos of Black people as "gorillas." In 2019, a study found that a healthcare algorithm used across US hospitals systematically directed less care to Black patients — affecting millions. In 2020, the UK A-Level grading algorithm downgraded students from disadvantaged postcodes. These are not glitches. They are the predictable result of biased training data producing biased outputs. The principle is simple: bias in, bias out.' },
    { type: 'concept', title: 'Sources of Data Bias', body: 'Bias can enter an AI system at multiple points in the data pipeline. Understanding these sources is the first step to mitigation.', bullets: ['Historical bias: Training data reflects past discrimination (e.g. hiring data from decades when women were excluded)', 'Representation bias: Certain groups are underrepresented in datasets (e.g. medical data skewed toward white male patients)', 'Measurement bias: The way data is collected systematically distorts reality (e.g. crime data reflects policing patterns, not actual crime)', 'Label bias: Human annotators bring their own prejudices when labelling data', 'Selection bias: The data collected is not representative of the population the model will serve'], callout: 'A model trained on biased data does not just reflect bias — it amplifies and automates it at scale.' },
    { type: 'concept', title: 'Real-World Case Studies', body: 'Examining specific cases reveals how bias manifests in deployed AI systems and the real harm it causes.', bullets: ['Amazon hiring tool (2018): Trained on 10 years of CVs — mostly male. Learned to penalise the word "women\'s"', 'COMPAS criminal justice (2016): ProPublica investigation found Black defendants were twice as likely to be falsely flagged as high-risk', 'UK A-Level algorithm (2020): Used school historical data, penalising students at schools with less exam history', 'Facial recognition (2018): MIT study found error rates of 0.8% for light-skinned men but 34.7% for dark-skinned women', 'Healthcare allocation (2019): Algorithm used cost as a proxy for health need — but unequal access to healthcare meant Black patients had lower costs despite being sicker'], callout: 'In every case, the bias was predictable in hindsight. The question is why it was not caught before deployment.' },
    { type: 'activity', title: 'Bias Detective', instructions: 'Investigate a real dataset or AI system for potential bias. Use the Ethics Audit Checklist from Resources to guide your analysis.', steps: ['Choose one case study from above or find your own', 'Identify the specific type of bias (historical, representation, measurement, label, or selection)', 'Trace the bias back to its source — where in the pipeline did it enter?', 'Assess the harm: who was affected and how severely?', 'Propose at least two mitigation strategies that could have prevented the bias', 'Write a brief recommendation (3-4 sentences) for how the organisation should respond'] },
    { type: 'discussion', title: 'Fairness and Responsibility', questions: [{ num: 1, text: 'If a biased AI system causes harm, who should be held responsible — the developers, the company, or the data providers?' }, { num: 2, text: 'Is it possible to create a truly unbiased AI system, or is some bias inevitable? How much bias is acceptable?' }, { num: 3, text: 'Should AI systems that affect people\'s lives (hiring, healthcare, justice) be required to pass bias audits before deployment?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔄', label: 'Bias amplification', text: 'AI does not just reflect bias — it automates and scales it, affecting millions of decisions' }, { icon: '🔍', label: 'Multiple entry points', text: 'Bias can enter through historical data, representation gaps, measurement methods, labels, and selection' }, { icon: '🛡️', label: 'Mitigation is possible', text: 'Diverse datasets, bias audits, and inclusive development teams can significantly reduce harm' }] }
  ],

  6: [
    { type: 'hook', title: 'The Data Harvest', body: 'Every minute, the world generates 500 hours of YouTube video, 6 million Google searches, 500,000 tweets, and 200 million emails. Behind each interaction, data is collected, stored, and sold. In 2023, the global data broker industry was worth over $300 billion. Your browsing history, location data, purchase records, and even your typing patterns are commodities traded on a vast marketplace — and most of this data is used to train AI models you interact with every day.' },
    { type: 'concept', title: 'The Data Supply Chain', body: 'Personal data flows through a complex supply chain from collection to AI training. Understanding this chain reveals who profits and who bears the risk.', bullets: ['Collection: Apps, websites, IoT devices, and public records gather raw data', 'Aggregation: Data brokers combine data from multiple sources to build detailed profiles', 'Processing: Data is cleaned, labelled, and formatted for machine learning', 'Training: AI companies use this processed data to build and refine models', 'Deployment: The trained model makes predictions using patterns learned from your data'], callout: 'You are not the customer — you are the product. If a service is free, your data is the payment.' },
    { type: 'concept', title: 'Privacy and Consent', body: 'The gap between legal consent and informed consent is vast. Most people technically agree to data collection but have no real understanding of what they are consenting to.', bullets: ['The average privacy policy is 4,000 words long — reading all of them would take 76 work days per year', 'GDPR (EU) requires explicit, informed consent and the right to be forgotten', 'CCPA (California) gives residents the right to know what data is collected and to opt out of its sale', 'Many apps use dark patterns — design tricks that make it harder to protect your privacy', 'Children and young people are especially vulnerable as they generate data from an early age'], callout: 'Clicking "I agree" is not meaningful consent if you cannot reasonably understand what you are agreeing to.' },
    { type: 'activity', title: 'Data Audit Your Phone', instructions: 'Investigate exactly what data your most-used apps collect about you and where it goes.', steps: ['Pick your 3 most-used apps (e.g. Instagram, TikTok, Snapchat)', 'Go to Settings > Privacy on your phone and check what permissions each app has', 'Find each app\'s privacy policy (search "[app name] privacy policy")', 'For each app, list: What data is collected? Is it shared with third parties? Can you delete it?', 'Check if any app sells your data to data brokers', 'Write a one-paragraph summary: Are you comfortable with what you found?'] },
    { type: 'discussion', title: 'Data Rights and Power', questions: [{ num: 1, text: 'Should you own the data you generate, or does it belong to the platforms that collect it?' }, { num: 2, text: 'Is it ethical for AI companies to train models on personal data without explicitly telling people their data was used?' }, { num: 3, text: 'If you could see every piece of data collected about you since birth, what do you think would surprise you most?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🌐', label: 'Data is the new oil', text: 'Personal data fuels a $300 billion industry and powers the AI systems you use daily' }, { icon: '📋', label: 'Consent is broken', text: 'Privacy policies are unreadable and dark patterns undermine genuine informed consent' }, { icon: '🔒', label: 'Rights are emerging', text: 'GDPR and CCPA represent a shift toward data rights, but enforcement remains a challenge' }] }
  ],

  7: [
    { type: 'hook', title: 'The Trolley Problem Goes Digital', body: 'A self-driving car is travelling at 60mph when a group of pedestrians steps into the road. It can swerve left (hitting one pedestrian), swerve right (hitting a wall, likely killing the passenger), or brake (probably hitting the group). This is not a philosophy thought experiment — it is a real engineering decision that autonomous vehicle companies must programme into their systems. The classic trolley problem has gone digital, and someone has to write the code.' },
    { type: 'concept', title: 'Ethical Frameworks for AI', body: 'Two major ethical traditions offer contrasting approaches to AI decision-making. Understanding both is essential for evaluating how AI should behave in moral dilemmas.', bullets: ['Utilitarianism: Choose the action that produces the greatest good for the greatest number', 'Deontology: Follow moral rules regardless of consequences (e.g. "never deliberately harm an innocent person")', 'Virtue ethics: Ask what a virtuous agent would do — focusing on character rather than rules or outcomes', 'In AI, utilitarian logic is easier to code (maximise a metric) but raises uncomfortable questions', 'Deontological constraints are harder to formalise but may better protect individual rights'], callout: 'The MIT Moral Machine experiment collected 40 million responses from 233 countries. Moral preferences varied dramatically by culture — there is no universal answer.' },
    { type: 'concept', title: 'Moral Agency and Machines', body: 'Can a machine be morally responsible? This question sits at the heart of AI ethics and has profound implications for law, insurance, and society.', bullets: ['Moral agency traditionally requires: consciousness, intention, and understanding of consequences', 'AI has none of these — it follows optimisation functions, not moral reasoning', 'Yet AI makes decisions with moral consequences: who gets a loan, who gets paroled, who gets medical treatment', 'The responsibility gap: When an AI causes harm, who is to blame? The developer? The company? The user?', 'Some propose "meaningful human control" — humans must remain responsible for AI decisions'], callout: 'A trolley switch is binary. Real-world AI decisions involve uncertainty, incomplete data, and consequences we cannot fully predict.' },
    { type: 'activity', title: 'Programme the Ethics', instructions: 'Your team is programming the ethical decision engine for a self-driving car. You must define the rules it follows in emergency scenarios.', steps: ['As a group, list 5 emergency scenarios a self-driving car might face', 'For each scenario, write the rule your car should follow (e.g. "minimise total harm" or "always protect the passenger")', 'Test your rules against each other — do any conflict?', 'Consider: Would your rules change if the pedestrian was a child? An elderly person? A group vs. an individual?', 'Present your ethical framework to another group and defend your choices', 'Vote as a class: Which framework would you trust with your life?'] },
    { type: 'discussion', title: 'Who Decides the Code?', questions: [{ num: 1, text: 'Should AI ethics be decided by engineers, ethicists, governments, or public vote? Why?' }, { num: 2, text: 'The Moral Machine experiment showed huge cultural differences in ethical preferences. Should self-driving cars behave differently in different countries?' }, { num: 3, text: 'If an autonomous vehicle kills someone, should the manufacturer face criminal charges? What about the programmer who wrote the decision algorithm?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '⚖️', label: 'No easy answers', text: 'Utilitarian, deontological, and virtue ethics each have strengths and weaknesses when applied to AI' }, { icon: '🤖', label: 'Machines lack moral agency', text: 'AI makes decisions with moral consequences but cannot bear moral responsibility' }, { icon: '🌍', label: 'Culture shapes ethics', text: 'There is no universal moral code — AI ethics must grapple with cultural variation' }] }
  ],

  8: [
    { type: 'hook', title: 'Human in the Loop', body: 'In 2020, a radiologist using an AI diagnostic tool ignored the algorithm\'s recommendation and ordered further tests on a patient the AI had cleared. The additional tests revealed early-stage cancer. The AI had been wrong. In the same year, a different doctor blindly followed an AI drug recommendation that turned out to be dangerously inappropriate for the patient. Both cases illustrate the critical question: When should humans override AI, and when should they trust it?' },
    { type: 'concept', title: 'Three Levels of Human Oversight', body: 'The relationship between humans and AI in decision-making exists on a spectrum, from full human control to full automation.', bullets: ['Human-in-the-loop: AI makes recommendations but a human makes the final decision (e.g. AI flags suspicious transactions, human investigator reviews)', 'Human-on-the-loop: AI acts autonomously but a human monitors and can intervene (e.g. autonomous vehicle with human override capability)', 'Human-out-of-the-loop: AI operates fully autonomously with no human oversight (e.g. high-frequency trading algorithms, autonomous weapons)', 'The appropriate level depends on: stakes of the decision, reliability of the AI, reversibility of errors, and speed requirements', 'Most experts advocate for human-in-the-loop for any decision affecting individual rights or safety'], callout: 'Automation bias is real — studies show humans tend to defer to AI recommendations even when they have good reason to disagree.' },
    { type: 'concept', title: 'Domain-Specific Oversight', body: 'Different domains require different levels of human oversight based on risk, reversibility, and the consequences of error.', bullets: ['Healthcare: Human-in-the-loop is essential — AI assists diagnosis but doctors decide treatment', 'Criminal justice: High stakes demand human oversight, yet judges increasingly rely on algorithmic risk scores', 'Content moderation: Scale makes human-in-the-loop impractical — platforms use AI with human review of appeals', 'Military: Autonomous weapons raise the most urgent questions — the "killer robot" debate centres on human-out-of-the-loop', 'Finance: High-frequency trading already operates human-out-of-the-loop, sometimes with catastrophic flash crashes'], callout: 'The 2010 Flash Crash saw the Dow Jones drop 1,000 points in minutes due to autonomous trading algorithms — human-out-of-the-loop at its most dangerous.' },
    { type: 'activity', title: 'Design the Oversight Model', instructions: 'For each scenario, decide the appropriate level of human oversight and design the human-AI collaboration model.', steps: ['Read each scenario: (a) AI grading student essays, (b) AI diagnosing skin cancer from photos, (c) AI approving small business loans, (d) AI moderating social media content', 'For each, choose: human-in-the-loop, human-on-the-loop, or human-out-of-the-loop', 'Justify your choice with at least two reasons', 'Design the workflow: What does the AI do? When does the human step in? What information does the human see?', 'Identify the risks of automation bias in your design — how do you prevent humans from rubber-stamping AI decisions?', 'Present your best design to the class'] },
    { type: 'discussion', title: 'Trust and Autonomy', questions: [{ num: 1, text: 'As AI becomes more accurate than humans in specific tasks, at what point should we let it operate without human oversight?' }, { num: 2, text: 'How can we prevent automation bias — the tendency for humans to defer to AI even when they should not?' }, { num: 3, text: 'Should autonomous weapons (AI that can kill without human approval) be banned under international law? Why or why not?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '👤', label: 'Three levels', text: 'Human-in-the-loop, on-the-loop, and out-of-the-loop represent increasing AI autonomy' }, { icon: '⚠️', label: 'Automation bias', text: 'Humans tend to over-trust AI — designing against this is crucial' }, { icon: '🏥', label: 'Context matters', text: 'The right level of oversight depends on stakes, reversibility, and reliability' }] }
  ],

  9: [
    { type: 'hook', title: 'Prompt Architecture', body: 'Two students ask ChatGPT the same question: "Tell me about climate change." One gets a rambling, generic essay. The other gets a concise, A-Level-appropriate analysis with Harvard references, structured as an essay plan with counter-arguments. The difference? The second student used the PTFC framework. Prompt engineering is the single most important skill for getting useful output from AI — and it is a skill you can learn in one lesson.' },
    { type: 'concept', title: 'The PTFC Framework', body: 'PTFC stands for Persona, Task, Format, and Constraints. This four-part framework transforms vague prompts into precise instructions that produce high-quality AI output.', bullets: ['Persona: Tell the AI who to be — "You are an experienced A-Level economics examiner"', 'Task: State exactly what to do — "Analyse the impact of quantitative easing on inflation"', 'Format: Specify the output structure — "Present as a 5-paragraph essay with introduction, 3 body paragraphs, and conclusion"', 'Constraints: Set boundaries — "Maximum 500 words, use UK English, include at least 2 counter-arguments, cite real economists"', 'A weak prompt: "Write about QE." A strong PTFC prompt produces output you can actually use.'], callout: 'Prompt engineering is not about tricking AI — it is about communicating clearly. The same skills that make you a good brief-writer make you a good prompt engineer.' },
    { type: 'concept', title: 'Iterating for Quality', body: 'The first output from any prompt is rarely the best. Systematic iteration — refining your prompt based on what the AI returns — is where the real skill lies.', bullets: ['Evaluate the first output: What is good? What is missing? What is wrong?', 'Refine one element at a time so you can see what changes improve the output', 'Add specificity: Vague instructions produce vague results', 'Use follow-up prompts: "Now make the tone more formal" or "Add a counter-argument to paragraph 2"', 'Keep a prompt log (see the Prompt Iteration Log resource) to track what works'], callout: 'Expert prompt engineers typically iterate 3-5 times before accepting output. Beginners often accept the first response.' },
    { type: 'activity', title: 'PTFC Challenge', instructions: 'Build three prompts using the PTFC framework, test them, and iterate for quality. Use the PTFC Framework Reference Card from Resources.', steps: ['Write a PTFC prompt for: "Help me revise for my biology exam on photosynthesis"', 'Write a PTFC prompt for: "Create a debate argument about social media regulation"', 'Write a PTFC prompt for: "Explain machine learning to a 10-year-old"', 'Test all three on an AI model and evaluate the outputs', 'Iterate each prompt at least twice, improving based on the output', 'Record your prompts and results in the Prompt Iteration Log'] },
    { type: 'discussion', title: 'The Skill of the Future?', questions: [{ num: 1, text: 'If AI can generate content, is the ability to write good prompts more valuable than the ability to write good essays?' }, { num: 2, text: 'Should prompt engineering be taught as a core skill in schools alongside reading, writing, and maths?' }, { num: 3, text: 'How might the PTFC framework apply beyond AI — in writing emails, briefs, or instructions for humans?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🏗️', label: 'PTFC framework', text: 'Persona, Task, Format, Constraints — four elements that transform weak prompts into powerful ones' }, { icon: '🔄', label: 'Iteration is key', text: 'Expert prompt engineers refine 3-5 times — never accept the first output' }, { icon: '📝', label: 'Transferable skill', text: 'Clear communication with AI is the same skill as clear communication with humans' }] }
  ],

  10: [
    { type: 'hook', title: 'Synthetic Creativity & Copyright', body: 'In 2022, an AI-generated artwork called "Theatre D\'Opera Spatial" won first prize at the Colorado State Fair art competition. The artist, Jason Allen, used Midjourney to generate the image. Traditional artists were outraged. Getty Images sued Stability AI for training on millions of copyrighted photos without permission. The New York Times sued OpenAI for training on its articles. The question tearing the creative world apart: Can AI be creative, and who owns what it produces?' },
    { type: 'concept', title: 'AI and Creativity', body: 'Whether AI can be truly creative depends on how you define creativity. This is not just a philosophical debate — it has real legal and economic consequences.', bullets: ['Computational creativity: AI can produce novel, surprising, and valuable outputs — a functional definition of creativity', 'But AI has no intention, emotion, or lived experience — it combines patterns from training data', 'Remixing vs. creating: All human creativity builds on prior work too — is AI fundamentally different?', 'The "1000 monkeys" argument: With enough random generation, something valuable will emerge — is that creativity?', 'Generative AI can now produce art, music, code, poetry, and scientific hypotheses'], callout: 'Margaret Boden identifies three types of creativity: combinational (mixing ideas), exploratory (working within a style), and transformational (breaking rules). AI excels at the first two but arguably cannot do the third.' },
    { type: 'concept', title: 'Copyright and Ownership', body: 'Current copyright law was not designed for AI-generated content. Courts around the world are racing to answer fundamental questions about ownership and fair use.', bullets: ['US Copyright Office ruled (2023): AI-generated content cannot be copyrighted — only human-authored work qualifies', 'Training data lawsuits: NYT v. OpenAI, Getty v. Stability AI, authors v. Meta — all argue training on copyrighted work is infringement', 'Fair use defence: AI companies argue training is transformative use, similar to how humans learn from reading', 'The artist\'s role: If a human writes the prompt, selects, and curates the output — is that enough human authorship?', 'Economic impact: Stock photo, illustration, and copywriting industries are already seeing revenue decline'], callout: 'If AI-generated content cannot be copyrighted, anyone can copy and sell it. This creates a strange incentive: why pay for AI art if no one owns it?' },
    { type: 'activity', title: 'The Copyright Court', instructions: 'Stage a mock trial to decide whether AI-generated art should be copyrightable. Assign roles and argue the case.', steps: ['Assign roles: Judge, Artist (human painter), AI Artist (prompt engineer), AI Company lawyer, Copyright Office representative', 'The prompt engineer presents their AI artwork and argues it deserves copyright protection', 'The human painter argues that AI art devalues human creativity and should not be protected', 'The AI Company argues that training on copyrighted data is fair use', 'The Copyright Office presents current legal standards', 'The Judge (and class jury) deliver a verdict with reasoning'] },
    { type: 'discussion', title: 'The Future of Creative Work', questions: [{ num: 1, text: 'If AI can produce art indistinguishable from human art, does it matter whether a human or machine created it?' }, { num: 2, text: 'Should artists whose work was used to train AI models be compensated? How would that work in practice?' }, { num: 3, text: 'Will AI replace creative professionals, augment them, or create entirely new creative roles?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎨', label: 'Creativity is contested', text: 'AI can produce novel valuable outputs but lacks intention and lived experience' }, { icon: '⚖️', label: 'Copyright is unsettled', text: 'Courts worldwide are wrestling with who owns AI-generated content and whether training on copyrighted data is fair use' }, { icon: '💼', label: 'Economic disruption', text: 'Creative industries are already being transformed — adaptation is essential' }] }
  ],

  11: [
    { type: 'hook', title: 'Deep Research & Career Disruption', body: 'Goldman Sachs estimates that AI could automate 300 million full-time jobs globally. McKinsey predicts 12 million Americans will need to switch occupations by 2030. Yet the World Economic Forum also projects AI will create 97 million new roles. The truth is nuanced: AI is not simply destroying jobs — it is reshaping them. Today, you will use AI research tools to investigate how your future career might be transformed.' },
    { type: 'concept', title: 'AI-Assisted Deep Research', body: 'Deep research means going beyond surface-level searches to find, synthesise, and critically evaluate information from multiple sources. AI tools can accelerate this process dramatically.', bullets: ['AI search tools (Perplexity, Consensus) can synthesise findings across thousands of papers', 'But they can also hallucinate sources, misrepresent findings, and reflect search biases', 'Critical evaluation remains a human skill: check sources, verify claims, assess methodology', 'Triangulation: Use at least three independent sources to confirm any AI-generated claim', 'AI is best used as a research assistant, not a research replacement'], callout: 'An AI research tool told a student that a famous study had been replicated 14 times. The study had actually failed to replicate. Always verify.' },
    { type: 'concept', title: 'Career Disruption Patterns', body: 'AI disrupts careers in predictable patterns. Understanding these patterns helps you prepare for a workforce that looks very different from today.', bullets: ['Routine cognitive tasks (data entry, basic analysis, bookkeeping) are most at risk', 'Creative, interpersonal, and strategic roles are harder to automate but not immune', 'New roles emerge: AI trainers, prompt engineers, AI ethicists, human-AI interaction designers', 'The "centaur" model: Humans and AI working together outperform either alone', 'Skills that remain valuable: critical thinking, emotional intelligence, complex problem-solving, ethical reasoning'], callout: 'The careers most disrupted are not always the ones you expect. Radiologists were predicted to be replaced by 2020 — they have not been, because the job is more than reading scans.' },
    { type: 'activity', title: 'Research Your Future Career', instructions: 'Use AI research tools to investigate how AI will impact a career you are interested in.', steps: ['Choose a career you are considering or curious about', 'Use an AI search tool to find: What tasks in this career can AI already do?', 'Research: What new skills will this career require in 5-10 years?', 'Find at least one example of AI already being used in this field', 'Verify your AI-generated findings against at least two traditional sources', 'Write a 200-word briefing: How should someone entering this field prepare?'] },
    { type: 'discussion', title: 'The Future of Work', questions: [{ num: 1, text: 'Is it your responsibility to "AI-proof" your career, or should governments and employers protect workers from disruption?' }, { num: 2, text: 'If AI can do a job cheaper and faster than a human, is there still value in having a human do it? In which cases?' }, { num: 3, text: 'How should education change to prepare students for a workforce where AI is a colleague, not just a tool?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📊', label: 'Disruption is real', text: 'AI will automate 300 million jobs but also create 97 million new roles — the net effect depends on preparation' }, { icon: '🔍', label: 'Research critically', text: 'AI research tools accelerate discovery but require human verification and critical evaluation' }, { icon: '🧠', label: 'Future-proof skills', text: 'Critical thinking, emotional intelligence, and ethical reasoning remain uniquely human advantages' }] }
  ],

  12: [
    { type: 'hook', title: 'The Revision Loop', body: 'A university study found that students who iteratively refined AI-generated essay drafts produced work rated 40% higher than students who accepted the first output. Another study showed that students who used AI without iteration actually performed worse than those who wrote without AI at all. The lesson is clear: AI is a powerful revision partner, but only if you treat it as the start of the process, not the end.' },
    { type: 'concept', title: 'The Iteration Mindset', body: 'Treating AI output as a first draft rather than a final product fundamentally changes the quality of work you produce. The revision loop is a systematic approach to iterative improvement.', bullets: ['Generate: Use a well-crafted PTFC prompt to produce a first draft', 'Evaluate: Read critically — what is accurate? What is weak? What is missing?', 'Refine: Give the AI specific feedback — "Make paragraph 2 more analytical" or "Add a counter-argument"', 'Verify: Check all facts, quotes, and references against reliable sources', 'Polish: Make final edits in your own voice — the output should sound like you, not like AI'], callout: 'The revision loop is not just for AI. This generate-evaluate-refine cycle is the same process expert writers have always used.' },
    { type: 'concept', title: 'AI as a Revision Partner', body: 'AI excels at specific revision tasks when prompted correctly. Knowing what to ask for turns a generic chatbot into a powerful editing tool.', bullets: ['Structural feedback: "Analyse the argument structure of this essay and suggest improvements"', 'Counter-arguments: "What are the strongest counter-arguments to my thesis?"', 'Clarity check: "Rewrite this paragraph for a Year 12 audience without losing technical accuracy"', 'Evidence gaps: "What claims in this essay need additional supporting evidence?"', 'Tone adjustment: "Make this more formal/academic/persuasive while keeping the same arguments"'], callout: 'The best revision prompts are specific about what to change and what to keep. "Make it better" is a weak prompt. "Strengthen the evidence in paragraph 3 while maintaining the conversational tone" is a strong one.' },
    { type: 'activity', title: 'The Three-Draft Challenge', instructions: 'Take a piece of your own work and run it through three iterations with AI, tracking improvements using the Prompt Iteration Log.', steps: ['Choose a paragraph or short essay you have written for another subject', 'Draft 1: Paste it into an AI tool and ask for structural feedback using a PTFC prompt', 'Record the AI feedback and make changes — save as Draft 2', 'Draft 2: Ask the AI to identify weak arguments and suggest counter-arguments', 'Record feedback, make changes — save as Draft 3', 'Compare Draft 1 and Draft 3 side by side: What improved? What is your voice vs. the AI?'] },
    { type: 'discussion', title: 'Authenticity and AI', questions: [{ num: 1, text: 'After three rounds of AI-assisted revision, is the essay still yours? Where is the line between AI-assisted and AI-generated?' }, { num: 2, text: 'Should students be required to disclose when they have used AI as a revision tool? Why or why not?' }, { num: 3, text: 'How can you use AI to improve your writing without becoming dependent on it?' }] },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔄', label: 'Iterate, don\'t accept', text: 'Students who refine AI output produce 40% better work than those who accept the first draft' }, { icon: '🎯', label: 'Specific prompts win', text: 'The best revision prompts target specific weaknesses rather than asking for generic improvement' }, { icon: '✍️', label: 'Keep your voice', text: 'AI is a revision partner, not a ghostwriter — the final product should sound like you' }] }
  ]

};
