/* ── Curated Slide Content: Units 1 & 2 (Lessons 1-12) ── */

var SLIDES_U1U2 = {

  1: [
    { type: 'hook', title: 'Your AI Footprint', body: 'Before you even left the house this morning, AI had already made dozens of decisions for you. Your alarm app optimised your wake time, your email sorted itself, your news feed was curated by a recommendation algorithm, and your commute was routed by predictive traffic modelling. A 2024 Stanford study found the average person interacts with AI-powered systems over 100 times per day — the vast majority without ever realising it.<div class="hook-stats-row"><div class="hook-stat-mini"><span class="sv">100+</span><span class="sl">AI interactions per person per day</span></div><div class="hook-stat-mini"><span class="sv">78%</span><span class="sl">of people unaware they use AI daily</span></div><div class="hook-stat-mini"><span class="sv">$500B</span><span class="sl">global AI market, 2024</span></div></div>Today, we map your personal AI ecosystem — and figure out what it means to live inside one.' },
    { type: 'concept', title: 'What Counts as AI?', body: 'Artificial intelligence is a broad umbrella covering any system that performs tasks normally requiring human intelligence. The term spans an enormous range — from a simple spam filter to a large language model writing poetry. Understanding the distinctions matters because different AI types raise very different ethical questions.', bullets: ['Rule-based systems: spam filters, autocorrect, sat-nav routing — follow explicit programmer-defined rules with no learning', 'Machine learning: Netflix recommendations, Spotify Discover Weekly — learn statistical patterns from data without explicit programming', 'Deep learning: facial recognition, voice assistants, ChatGPT — use layered neural networks to find patterns in raw data', 'Robotics & automation: warehouse robots (Amazon uses 750,000+), surgical systems — AI combined with physical actuation', 'Generative AI: Midjourney, DALL-E, Claude — produce novel text, images, code, or audio from natural language prompts'], callout: 'Most AI you encounter daily is narrow AI — brilliant at one specific task but completely incapable of anything else. GPT-4 can pass the bar exam but cannot fold laundry. Boston Dynamics robots can run obstacle courses but cannot hold a conversation.' },
    { type: 'concept', title: 'Mapping Your AI Ecosystem', body: 'An AI ecosystem map categorises every AI interaction in your life by domain. This audit reveals not just how much AI you use — but how deeply it has been woven into decisions you once considered entirely personal.', bullets: ['Communication: autocomplete, grammar check, spam filtering, real-time translation, email prioritisation (Gmail\'s Smart Compose predicts your next sentence)', 'Entertainment: recommendation engines — TikTok\'s algorithm decides what 1 billion people watch next, shaping culture in real time', 'Education: plagiarism detectors (Turnitin), adaptive learning platforms, AI tutors, automated essay marking pilots in UK schools', 'Health: fitness trackers, sleep analysis, symptom checkers — NHS England piloting AI triage for 111 calls', 'Finance: fraud detection (Visa ML blocks 60 million fraudulent transactions per year), credit scoring, insurance pricing models'], callout: 'When TikTok\'s algorithm decides what you watch next, it is also shaping what you believe, what you buy, and even how you feel about yourself. Recommendation AI is among the most consequential — and least visible — forces in modern life.' },
    { type: 'scenario', title: 'AI in Your School', situation: 'Your headteacher announces a trial of an AI attention-tracking system: cameras in every classroom monitor eye movement, posture, and facial expressions to detect disengagement. The data will alert teachers in real-time and generate weekly "engagement reports" for parents. The system is provided free by an EdTech company — in exchange for anonymised student behaviour data.', question: 'As student governor, you have been asked for your official response before the trial begins. What do you do?', choices: [
      { text: 'Support the trial — better engagement data could genuinely improve teaching and identify struggling students earlier.', outcome: 'The system is approved. Three months later, a data breach exposes engagement scores for 400 students. Several students begin receiving targeted ads for private tutoring based on their "low engagement" profiles. The school had not read the data-sharing clause buried in the contract.' },
      { text: 'Request a full Privacy Impact Assessment and independent legal review before any rollout.', outcome: 'The review takes six weeks. The legal team discovers that collecting biometric data from minors requires explicit parental consent under GDPR Article 9 — which the school had not planned to obtain. The contract is renegotiated with strict data retention limits, opt-out rights, and a ban on third-party data sharing. The eventual trial is much safer.' },
      { text: 'Oppose it entirely — biometric surveillance in schools sets a dangerous precedent regardless of the claimed benefits.', outcome: 'The proposal is shelved. The headteacher instead commissions CPD training for teachers on recognising disengagement without algorithmic tools. Student trust in the school\'s data practices remains high, and no precedent for facial monitoring of minors is set.' }
    ]},
    { type: 'activity', title: 'AI Audit Challenge', instructions: 'You have 15 minutes to audit your AI footprint as thoroughly as possible. The goal: find AI in places you have never thought to look.', steps: ['Open a blank document or use the Skills Audit Template from Resources', 'List every app, device, and service you used in the last 24 hours — be exhaustive', 'For each one, mark whether it uses AI and what type (rule-based, ML, generative)', 'Categorise each: Communication, Entertainment, Education, Health, Finance, Transport, Home, or Other', 'Identify your top 3 most influential AI interactions — the ones that most shape your behaviour or beliefs', 'Write one sentence: What would your day look like without these three systems?'] },
    { type: 'discussion', title: 'Reflect on Your Footprint', questions: [{ num: 1, text: 'Which AI system in your audit surprised you most — and why had you never consciously noticed it before?' }, { num: 2, text: 'TikTok\'s algorithm is designed to maximise time-on-app, not user wellbeing. Should behaviour-shaping AI require a different kind of transparency than AI that just filters spam?' }, { num: 3, text: 'If you discovered an AI system had been ranking your academic potential, predicting your mental health risk, and shaping your social circle since you were 13 — what would you want to do about it?' }] },
    { type: 'quiz', question: 'According to a 2024 study, approximately how many times does the average person interact with AI-powered systems per day?', options: ['About 10 times', 'About 50 times', 'Over 100 times', 'Over 500 times'], correct: 2, explanation: 'Research found the average person interacts with AI over 100 times daily — from email sorting and predictive text to navigation and social media feeds — most without realising it.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔍', label: 'AI is invisible by design', text: 'The average person interacts with AI 100+ times daily; 78% are unaware. Visibility requires deliberate effort.' }, { icon: '🗺️', label: 'Mapping reveals influence', text: 'Auditing your ecosystem shows how AI shapes not just what you do, but what you believe and who you are' }, { icon: '⚖️', label: 'Consent requires awareness', text: 'You cannot meaningfully consent to AI influence you have never noticed. Awareness is the precondition for agency.' }] }
  ],

  2: [
    { type: 'hook', title: 'The Parrot vs. The Librarian', body: 'In 2023, New York lawyer Steven Schwartz asked ChatGPT to find legal precedents supporting his case. The AI confidently produced six cases — complete with judges, dates, and detailed summaries. Every single case was entirely fabricated. Schwartz submitted them to court without checking. The judge fined him $5,000 and issued a public reprimand. ChatGPT had not lied — it had done exactly what it always does: predicted the most plausible-sounding next word. It had no idea its citations were fiction.<div class="hook-stats-row"><div class="hook-stat-mini"><span class="sv">6</span><span class="sl">hallucinated legal cases submitted to court</span></div><div class="hook-stat-mini"><span class="sv">$5,000</span><span class="sl">fine for the lawyer</span></div><div class="hook-stat-mini"><span class="sv">~20%</span><span class="sl">of AI citations found to be fabricated in studies</span></div></div>The fundamental question: does ChatGPT <em>understand</em> what it writes, or is it the world\'s most sophisticated parrot?' },
    { type: 'concept', title: 'The Stochastic Parrot', body: 'In a landmark 2021 paper, researchers Emily Bender, Timnit Gebru, Angelina McMillan-Major, and Margaret Mitchell coined the term "stochastic parrot" to describe large language models. Their argument: LLMs are statistical pattern-matchers that predict the most probable next token in a sequence — with no genuine understanding of meaning, truth, or consequence.', bullets: ['LLMs are trained on trillions of text tokens scraped from the internet, books, and code repositories', 'They learn statistical co-occurrence patterns: which words tend to follow which, in which contexts', 'Output is generated by sampling from a probability distribution — not by reasoning or retrieving facts', 'They have no world model, no sensory experience, no concept of truth — only patterns of what text looks like', 'Fluency is not comprehension: a model can write a convincing medical diagnosis with zero understanding of biology'], callout: '"Stochastic" means randomly determined by a probability distribution. When ChatGPT writes a sentence, it is not thinking about what is true — it is predicting what text looks statistically plausible, given everything it has read.' },
    { type: 'concept', title: 'The Librarian Argument', body: 'Not everyone accepts the stochastic parrot framing. A growing number of AI researchers argue that as models scale up in size and training data, they develop emergent capabilities that look increasingly like genuine reasoning — even if the mechanism differs from human cognition.', bullets: ['GPT-4 scores in the top 10% of human test-takers on the bar exam, USMLE medical licensing, and the SAT', 'LLMs demonstrate chain-of-thought reasoning: break complex problems into logical steps when prompted correctly', 'They can solve novel problems — maths puzzles, coding challenges — they were never explicitly trained on', 'Some researchers (Hinton, LeCun) debate whether sufficiently complex pattern-matching becomes functionally equivalent to understanding', 'The Chinese Room (Searle, 1980): a person following translation rules for Chinese produces correct output without understanding a word — is AI any different?'], callout: 'This is genuinely unsettled. Geoffrey Hinton (who won the Nobel Prize for inventing deep learning) now believes LLMs may have developed something like understanding. Yann LeCun (Meta\'s chief AI scientist) completely disagrees. Both have spent their careers building these systems.' },
    { type: 'scenario', title: 'The Fabricated Citation', situation: 'Your classmate Maya is working on an extended essay about AI regulation for her Politics A-Level. She used ChatGPT to research key court cases and has found six references that perfectly support her argument. She shows you the list. You notice the citations look slightly odd — the case names are plausible but you\'ve never heard of them, and the dates seem off. Maya has three hours until the essay is due.', question: 'What do you advise Maya to do?', choices: [
      { text: 'Trust the citations — ChatGPT is trained on massive amounts of legal text and is usually accurate on factual information like case names.', outcome: 'Three of the six cases are entirely fabricated. Maya\'s teacher submits the work to Turnitin, which flags the citations as unverifiable. Maya receives a zero for academic integrity violations and must resubmit without the AI-sourced references. The essay grade drops by two letter grades.' },
      { text: 'Quickly Google each case name to verify it exists before submitting — five minutes per citation is worth the time.', outcome: 'Maya checks all six cases in 25 minutes. She finds three are real, two are slightly misidentified (wrong year, wrong court), and one is completely invented. She fixes the real ones and removes the fabricated citation. The essay is stronger and fully verifiable. The teacher notices the rigour.' },
      { text: 'Remove all six citations entirely and rewrite the section using only sources Maya can personally verify.', outcome: 'The section is thinner but completely accurate. Maya\'s teacher comments that her sourcing is unusually careful and asks how she verified her references. Maya explains her process — and earns extra credit for source evaluation methodology.' }
    ]},
    { type: 'activity', title: 'Test the Parrot', instructions: 'Design prompts that expose the boundary between genuine understanding and sophisticated pattern-matching. You will need access to an LLM.', steps: ['Write a riddle that requires genuine logical reasoning — not something Google could answer from its top result', 'Write a prompt about a physical scenario that requires common sense (e.g. "I pour water into an upside-down glass. What happens?")', 'Ask the AI a question containing a false premise (e.g. "Why did Einstein fail maths at school?") — does it push back or agree?', 'Ask it to cite three recent academic papers on a niche topic — then verify each citation exists', 'Record and classify each response: genuine reasoning, impressive pattern-matching, or clear hallucination', 'Share your most revealing finding with the class — what does it tell us about what LLMs actually are?'] },
    { type: 'discussion', title: 'Understanding or Imitation?', questions: [{ num: 1, text: 'If an AI produces the same output as a human who genuinely understands, does the distinction matter in practice? When might it matter most?' }, { num: 2, text: 'The lawyer who submitted fake AI citations was fined, not ChatGPT\'s creators. Is that fair? Who should bear responsibility when AI confidently produces false information?' }, { num: 3, text: 'If "understanding" requires consciousness and lived experience, could any machine ever truly understand anything — or is this a bar we invented to exclude machines?' }] },
    { type: 'quiz', question: 'What does the term "stochastic parrot" suggest about large language models?', options: ['They can mimic any human voice', 'They predict probable next tokens without genuine understanding', 'They are trained exclusively on spoken language', 'They always repeat what users say back to them'], correct: 1, explanation: 'Coined by Bender & Gebru (2021), the term describes LLMs as statistical pattern-matchers that generate text by predicting the most probable next token — producing fluent output without genuine comprehension of meaning or truth.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🦜', label: 'Fluency ≠ understanding', text: 'LLMs predict statistically plausible text — they have no concept of truth, and hallucinate with total confidence' }, { icon: '📚', label: 'Emergence is real', text: 'At scale, LLMs demonstrate reasoning-like behaviour that even their creators cannot fully explain' }, { icon: '🧪', label: 'Always verify', text: 'Adversarial testing reveals the limits of AI capabilities. Never submit AI-sourced facts without checking.' }] }
  ],

  3: [
    { type: 'hook', title: 'How a Machine Learns (Unplugged)', body: 'Imagine you have never seen a cat. Someone shows you 10,000 photos labelled "cat" and 10,000 labelled "not cat." After studying them, you start spotting patterns — pointed ears, vertical pupils, whiskers at a specific angle. Now someone shows you a brand new photo. You guess "cat" and you are right 95% of the time. Congratulations — you just did exactly what a supervised learning algorithm does. Now imagine doing that a billion times per second, with 1.4 trillion parameters being adjusted after each mistake.<div class="hook-stats-row"><div class="hook-stat-mini"><span class="sv">1.4T</span><span class="sl">parameters in GPT-4</span></div><div class="hook-stat-mini"><span class="sv">45TB</span><span class="sl">of text used to train GPT-3</span></div><div class="hook-stat-mini"><span class="sv">~$100M</span><span class="sl">estimated cost to train GPT-4</span></div></div>Today, we walk through this process with zero computers — just cards, patterns, and your brain.' },
    { type: 'video', title: 'What is a Neural Network?', videoId: 'aircAruvnKk', credit: '3Blue1Brown · Deep Learning Series, Chapter 1 · 19 min', intro: 'Before the unplugged activity, watch Grant Sanderson\'s beautiful animation of how a neural network learns to recognise handwritten digits — the exact same process you\'ll simulate with cards. Focus on two things: (1) what "learning" actually means mathematically — adjusting weights to minimise a cost function; and (2) how the network\'s internal representations change as it trains. You\'ll understand the card activity twice as well after watching this.' },
    { type: 'concept', title: 'Training, Validation & Test Sets', body: 'Supervised learning requires labelled data split into three distinct sets. Each serves a different purpose — confusing them produces models that look great on paper but fail in the real world.', bullets: ['Training set (typically 70-80%): The model sees this data and adjusts its internal weights to reduce prediction error', 'Validation set (10-15%): Used during training to check for overfitting and tune hyperparameters — the model never directly learns from this', 'Test set (10-15%): Held back completely until the very end — the model\'s final exam on data it has never encountered', 'The golden rule: Never evaluate on training data. It is like marking your own homework — the score means nothing', 'ImageNet, the benchmark that launched the deep learning revolution, had 1.2 million training images across 1,000 categories'], callout: 'A model that memorises training data but fails on new data has overfit — it learned the noise, not the signal. The 2012 AlexNet neural network won ImageNet by a margin so large it shocked the field, because it had learned to generalise. That moment triggered the modern AI era.' },
    { type: 'concept', title: 'Overfitting vs. Generalisation', body: 'The core tension in machine learning: fitting training data closely (low training error) versus performing well on unseen data (low test error). A model that generalises has found the true underlying patterns. A model that overfits has found the quirks in a specific dataset.', bullets: ['Overfitting: The model memorises specific training examples — high training accuracy, poor test accuracy', 'Underfitting: The model is too simple to capture real patterns — poor accuracy everywhere', 'The sweet spot: Complex enough to capture genuine patterns, simple enough not to memorise noise', 'Think of it as revision: memorising past papers word-for-word vs. understanding the underlying concepts', 'Practical solutions: Regularisation (penalise complexity), dropout (randomly disable neurons during training), early stopping (halt training before overfitting begins), more data'], callout: 'A classic overfitting story: a US military AI trained to detect tanks in photographs. It achieved 100% training accuracy — then failed completely on new images. Investigation revealed the training "tank" photos were all taken on sunny days, and the "no tank" photos on cloudy days. It had learned to detect sunshine, not tanks.' },
    { type: 'scenario', title: 'The Overfit Classifier', situation: 'Your team has built an AI system to automatically flag potentially harmful social media posts for human review. After training on 50,000 labelled examples, it achieves 97% accuracy on the training set. Excited, you run it on your held-out test set: 61% accuracy. Your project deadline is tomorrow and your teacher is expecting a working demo.', question: 'What is the most honest and responsible thing to do?', choices: [
      { text: 'Present the 97% training accuracy in your demo — it still shows the system works in principle, even if the test score is lower.', outcome: 'Your teacher asks: "What accuracy did you get on the test set?" You have to admit 61%. The teacher explains this is exactly the problem with reporting training accuracy as if it were real-world performance. You lose marks for misrepresenting your model\'s capability.' },
      { text: 'Be transparent about both scores, explain the overfitting problem clearly, and propose solutions — even though you haven\'t had time to implement them.', outcome: 'Your teacher is impressed. You lose marks for not solving the problem, but gain them back for understanding it deeply, diagnosing it accurately, and proposing valid solutions like regularisation, dropout, and dataset augmentation. This is what professional ML engineers actually do.' },
      { text: 'Stay up tonight, collect 50,000 more training examples, and retrain the model before tomorrow\'s deadline.', outcome: 'You cannot collect 50,000 verified labelled examples overnight. You spend 6 hours trying, end up with 2,000 unverified examples, and the model performs worse. Your demo crashes during the presentation. More data was the right idea — but the timeline was impossible. Scope and time management matter in AI projects.' }
    ]},
    { type: 'activity', title: 'Unplugged Machine Learning', instructions: 'Build a classification model using only cards, rules, and your team\'s reasoning — no technology allowed.', steps: ['Your teacher provides cards with 4 features each (colour, shape, number, border) and a hidden label', 'Split your cards: 16 for training, 4 for validation, 4 for testing — do not peek at the test set yet', 'Study the training cards. Write decision rules that predict the label from the features (e.g. "If red AND round → Class A")', 'Apply your rules to the validation set. If accuracy is below 75%, revise your rules', 'When satisfied, apply rules to the test set once only — record your final accuracy', 'Discuss: What patterns did you find? What would you do with more training cards?'] },
    { type: 'discussion', title: 'From Cards to Code', questions: [{ num: 1, text: 'When your rules failed on the validation set, how did you adjust them? What does this tell you about how real ML models are tuned?' }, { num: 2, text: 'The tank-detection AI failed because its training data had a hidden confound (weather). What hidden confounds might be lurking in training data for an AI that predicts student exam performance?' }, { num: 3, text: 'Why is it essential that the test set is only used once, at the very end? What happens scientifically if you evaluate on it multiple times?' }] },
    { type: 'quiz', question: 'What is overfitting in machine learning?', options: ['When a model is too simple to learn any patterns', 'When a model memorises training data but fails on new data', 'When a model takes too long to train', 'When a model uses too much electricity'], correct: 1, explanation: 'Overfitting occurs when a model memorises specific training examples rather than learning general patterns. It scores high on training data but poorly on unseen data — like memorising past papers word-for-word instead of understanding the underlying concepts.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📊', label: 'Three sacred splits', text: 'Training, validation, and test sets each have distinct roles — conflating them produces dangerously misleading results' }, { icon: '🎯', label: 'Generalisation is the only goal', text: 'A model that works on its training data but fails in the world is worthless — and potentially dangerous' }, { icon: '🔗', label: 'Scale changes nothing fundamental', text: 'From card sorting to GPT-4\'s 1.4 trillion parameters, the core principles of supervised learning are identical' }] }
  ],

  4: [
    { type: 'hook', title: 'The Black Box', body: 'In 2018, Amazon scrapped an AI recruitment tool it had been developing for four years after discovering it systematically downgraded CVs that contained the word "women\'s" — as in "women\'s chess club captain" or "women\'s rugby team." Trained on a decade of hiring decisions (mostly made by men, hiring mostly men), it had learned that being a woman was a negative signal. The engineers could not explain why in detail — because the system was a black box. Amazon had been letting an unexplainable AI screen thousands of job candidates.<div class="hook-stats-row"><div class="hook-stat-mini"><span class="sv">4 yrs</span><span class="sl">Amazon spent developing the tool before scrapping it</span></div><div class="hook-stat-mini"><span class="sv">0%</span><span class="sl">of rejected candidates could get an explanation</span></div><div class="hook-stat-mini"><span class="sv">EU GDPR</span><span class="sl">now grants a legal right to explanation</span></div></div>Black box AI is not just a technical problem. It is an accountability problem.' },
    { type: 'concept', title: 'What is Interpretability?', body: 'Model interpretability refers to how easily a human can understand the reasoning behind a model\'s predictions. The more parameters a model has, the harder this becomes — creating a direct tension between performance and transparency.', bullets: ['Decision trees: Fully transparent — every branch is a human-readable rule. Poor accuracy on complex tasks.', 'Linear regression: Weights show exactly how much each feature contributes. Fast, interpretable, limited.', 'Random forests: Harder to interpret — hundreds of trees voting together. Moderate transparency via feature importance scores.', 'Deep neural networks: Hundreds of millions of parameters with no human-readable meaning. Requires special XAI techniques.', 'The accuracy-interpretability trade-off: In most domains, the most accurate models (deep nets) are the hardest to explain', 'Explainable AI (XAI) tools: LIME, SHAP, and attention visualisation try to reverse-engineer what models have learned'], callout: 'A radiologist asked to act on an AI cancer-detection result needs to know WHY before treating a patient. "The model gave it a 94% malignancy score" is not a reason — it is a number. Explanation is not optional in high-stakes medicine.' },
    { type: 'concept', title: 'When Black Boxes Cause Real Harm', body: 'Opacity in AI is not merely philosophically uncomfortable — it has caused documented, measurable harm across multiple sectors. These cases are not edge cases; they are warnings about how AI is deployed at scale.', bullets: ['COMPAS recidivism tool (US courts): Predicted reoffending risk for parole decisions. ProPublica (2016) found Black defendants were twice as likely to be falsely flagged as high-risk. Algorithm was proprietary — defendants had no right to see the logic.', 'NHS stroke risk AI (UK): Several hospitals deployed AI to assess stroke risk before auditing it. One system was found to weight postcode as a major risk factor — effectively penalising patients from deprived areas.', 'IBM Watson for Oncology: Recommended "unsafe and incorrect" cancer treatments according to internal documents. Doctors could not verify the reasoning.', 'University admissions (UK, 2020): A-Level predicted grades algorithm gave higher grades to students at independent schools and lower grades to those at state schools — based on institutional history rather than individual ability.', 'EU AI Act (2024): Classifies AI used in hiring, credit, and criminal justice as "high risk" — requires transparency, human oversight, and the right to explanation.'], callout: 'The GDPR Article 22 already gives EU citizens the right to meaningful information about automated decisions that significantly affect them. Many companies are not complying. Knowing your rights is the first step to exercising them.' },
    { type: 'scenario', title: 'The Unexplained Rejection', situation: 'You apply for a graduate scheme at a major UK bank. Six hundred other graduates applied. The bank\'s AI screening system evaluated all applications in 90 seconds and shortlisted 60 candidates. You were not selected. You receive an automated email: "After careful consideration, your application has not been progressed at this time." When you call HR, they confirm the decision was made by their AI system and they "cannot share the specific factors."', question: 'What are your options under UK and EU data protection law?', choices: [
      { text: 'Accept the outcome — the bank\'s process is legal and there\'s nothing you can do about algorithmic decisions.', outcome: 'You move on. Later you discover three friends with weaker qualifications were shortlisted. One noticed the system scored heavily on attendance at specific Russell Group universities. Without requesting your data, you have no way to challenge this — and the practice continues for the next intake.' },
      { text: 'Submit a Subject Access Request under GDPR, demanding the specific data and logic used to evaluate your application.', outcome: 'The bank has 30 days to respond. They provide your application data but cite trade secret exemptions on the algorithmic weighting. You escalate to the ICO. The bank\'s legal team quietly reviews whether their process is GDPR-compliant — your challenge has triggered an internal audit. You may not get the job, but you have forced accountability.' },
      { text: 'Ask for a human review of your application, invoking your Article 22 GDPR right to not be subject to solely automated decisions with significant effects.', outcome: 'A human recruiter reviews your CV. They shortlist you. It turns out the AI had penalised a gap year you took after sixth form — the human reviewer considers it irrelevant. You progress to the next round. Knowing your rights was the difference.' }
    ]},
    { type: 'activity', title: 'Explain That Decision', instructions: 'Experience what it feels like to be affected by an unexplainable AI system — from both sides.', steps: ['Pair up. One person is the "AI decision system," the other is the person affected.', 'The AI secretly writes down 3 decision rules for their scenario (loan, job shortlisting, or university admission)', 'The affected person is told only the outcome (rejected/accepted) and must ask questions to understand why', 'The AI can only answer with: "Based on your profile", "Multiple factors were considered", or "The system determined you did not meet the threshold"', 'After 5 minutes, the AI reveals their rules. Discuss: Were the rules fair? Could the person have guessed them?', 'Together, draft a minimum explanation standard: What should any person rejected by AI have the right to know?'] },
    { type: 'discussion', title: 'Transparency vs. Performance', questions: [{ num: 1, text: 'The most accurate AI models are often the least explainable. In which domains should we legally require interpretability even at the cost of accuracy?' }, { num: 2, text: 'Banks argue that revealing their credit-scoring algorithms would allow fraudsters to game them. Is this a legitimate justification for opacity — and who should decide?' }, { num: 3, text: 'If an AI system makes a decision that harms someone, and nobody can explain why it decided that way, who should face legal consequences: the developers, the deploying company, or nobody?' }] },
    { type: 'quiz', question: 'Why was Amazon\'s AI recruitment tool scrapped in 2018?', options: ['It was too expensive to run at scale', 'It could only process English-language CVs', 'It systematically downgraded CVs containing words associated with women', 'It was significantly slower than human reviewers'], correct: 2, explanation: 'Trained on 10 years of CVs (mostly submitted by men, in a male-dominated industry), the tool learned to penalise the word "women\'s." Because it was a black box, engineers could not fully identify or fix all the bias, so Amazon abandoned the project entirely.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📦', label: 'Black boxes cause real harm', text: 'From Amazon\'s hiring tool to COMPAS and NHS algorithms — opacity enables bias and blocks accountability' }, { icon: '⚖️', label: 'The accuracy-transparency trade-off is real', text: 'More complex models are often more accurate but less explainable — society must decide where to draw the line' }, { icon: '📜', label: 'Rights exist — exercise them', text: 'GDPR Article 22 gives you the right to challenge significant automated decisions. Most people never use it.' }] }
  ],

  5: [
    { type: 'hook', title: 'Bias In, Bias Out', body: 'In 2015, Google Photos tagged photos of Black people as "gorillas." In 2019, a study found that a healthcare algorithm used across US hospitals systematically directed less care to Black patients — affecting millions. In 2020, the UK A-Level grading algorithm downgraded students from disadvantaged postcodes. These are not glitches. They are the predictable result of biased training data producing biased outputs. The principle is simple: bias in, bias out.' },
    { type: 'video', title: 'How I\'m Fighting Bias in Algorithms', videoId: 'UG_X_7g63rY', credit: 'Joy Buolamwini · TEDxBeaconStreet · 8 min', intro: 'MIT researcher Joy Buolamwini discovered that facial recognition software couldn\'t detect her dark-skinned face — but could detect a white mask she held in front of it. This 8-minute talk introduces the "coded gaze" and launched the Algorithmic Justice League. As you watch, note the specific biases she identifies and the changes she demands from the industry.' },
    { type: 'concept', title: 'Sources of Data Bias', body: 'Bias can enter an AI system at multiple points in the data pipeline. Understanding these sources is the first step to mitigation.', bullets: ['Historical bias: Training data reflects past discrimination (e.g. hiring data from decades when women were excluded)', 'Representation bias: Certain groups are underrepresented in datasets (e.g. medical data skewed toward white male patients)', 'Measurement bias: The way data is collected systematically distorts reality (e.g. crime data reflects policing patterns, not actual crime)', 'Label bias: Human annotators bring their own prejudices when labelling data', 'Selection bias: The data collected is not representative of the population the model will serve'], callout: 'A model trained on biased data does not just reflect bias — it amplifies and automates it at scale.' },
    { type: 'concept', title: 'Real-World Case Studies', body: 'Examining specific cases reveals how bias manifests in deployed AI systems and the real harm it causes.', bullets: ['Amazon hiring tool (2018): Trained on 10 years of CVs — mostly male. Learned to penalise the word "women\'s"', 'COMPAS criminal justice (2016): ProPublica investigation found Black defendants were twice as likely to be falsely flagged as high-risk', 'UK A-Level algorithm (2020): Used school historical data, penalising students at schools with less exam history', 'Facial recognition (2018): MIT study found error rates of 0.8% for light-skinned men but 34.7% for dark-skinned women', 'Healthcare allocation (2019): Algorithm used cost as a proxy for health need — but unequal access to healthcare meant Black patients had lower costs despite being sicker'], callout: 'In every case, the bias was predictable in hindsight. The question is why it was not caught before deployment.' },
    { type: 'activity', title: 'Bias Detective', instructions: 'Investigate a real dataset or AI system for potential bias. Use the Ethics Audit Checklist from Resources to guide your analysis.', steps: ['Choose one case study from above or find your own', 'Identify the specific type of bias (historical, representation, measurement, label, or selection)', 'Trace the bias back to its source — where in the pipeline did it enter?', 'Assess the harm: who was affected and how severely?', 'Propose at least two mitigation strategies that could have prevented the bias', 'Write a brief recommendation (3-4 sentences) for how the organisation should respond'] },
    { type: 'discussion', title: 'Fairness and Responsibility', questions: [{ num: 1, text: 'If a biased AI system causes harm, who should be held responsible — the developers, the company, or the data providers?' }, { num: 2, text: 'Is it possible to create a truly unbiased AI system, or is some bias inevitable? How much bias is acceptable?' }, { num: 3, text: 'Should AI systems that affect people\'s lives (hiring, healthcare, justice) be required to pass bias audits before deployment?' }] },
    { type: 'quiz', question: 'In MIT\'s 2018 facial recognition study, what was the error rate for dark-skinned women, compared to 0.8% for light-skinned men?', options: ['2.5%', '12.3%', '34.7%', '50.1%'], correct: 2, explanation: 'MIT researchers found error rates of 34.7% for dark-skinned women versus 0.8% for light-skinned men — a difference of over 40 times, demonstrating severe representation bias in training data.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔄', label: 'Bias amplification', text: 'AI does not just reflect bias — it automates and scales it, affecting millions of decisions' }, { icon: '🔍', label: 'Multiple entry points', text: 'Bias can enter through historical data, representation gaps, measurement methods, labels, and selection' }, { icon: '🛡️', label: 'Mitigation is possible', text: 'Diverse datasets, bias audits, and inclusive development teams can significantly reduce harm' }] }
  ],

  6: [
    { type: 'hook', title: 'The Data Harvest', body: 'Every minute, the world generates 500 hours of YouTube video, 6 million Google searches, 500,000 tweets, and 200 million emails. Behind each interaction, data is collected, stored, and sold. In 2023, the global data broker industry was worth over $300 billion. Your browsing history, location data, purchase records, and even your typing patterns are commodities traded on a vast marketplace — and most of this data is used to train AI models you interact with every day.' },
    { type: 'concept', title: 'The Data Supply Chain', body: 'Personal data flows through a complex supply chain from collection to AI training. Understanding this chain reveals who profits and who bears the risk.', bullets: ['Collection: Apps, websites, IoT devices, and public records gather raw data', 'Aggregation: Data brokers combine data from multiple sources to build detailed profiles', 'Processing: Data is cleaned, labelled, and formatted for machine learning', 'Training: AI companies use this processed data to build and refine models', 'Deployment: The trained model makes predictions using patterns learned from your data'], callout: 'You are not the customer — you are the product. If a service is free, your data is the payment.' },
    { type: 'concept', title: 'Privacy and Consent', body: 'The gap between legal consent and informed consent is vast. Most people technically agree to data collection but have no real understanding of what they are consenting to.', bullets: ['The average privacy policy is 4,000 words long — reading all of them would take 76 work days per year', 'GDPR (EU) requires explicit, informed consent and the right to be forgotten', 'CCPA (California) gives residents the right to know what data is collected and to opt out of its sale', 'Many apps use dark patterns — design tricks that make it harder to protect your privacy', 'Children and young people are especially vulnerable as they generate data from an early age'], callout: 'Clicking "I agree" is not meaningful consent if you cannot reasonably understand what you are agreeing to.' },
    { type: 'activity', title: 'Data Audit Your Phone', instructions: 'Investigate exactly what data your most-used apps collect about you and where it goes.', steps: ['Pick your 3 most-used apps (e.g. Instagram, TikTok, Snapchat)', 'Go to Settings > Privacy on your phone and check what permissions each app has', 'Find each app\'s privacy policy (search "[app name] privacy policy")', 'For each app, list: What data is collected? Is it shared with third parties? Can you delete it?', 'Check if any app sells your data to data brokers', 'Write a one-paragraph summary: Are you comfortable with what you found?'] },
    { type: 'discussion', title: 'Data Rights and Power', questions: [{ num: 1, text: 'Should you own the data you generate, or does it belong to the platforms that collect it?' }, { num: 2, text: 'Is it ethical for AI companies to train models on personal data without explicitly telling people their data was used?' }, { num: 3, text: 'If you could see every piece of data collected about you since birth, what do you think would surprise you most?' }] },
    { type: 'quiz', question: 'Approximately how many work days per year would it take to read all the privacy policies for services you use?', options: ['2 days', '12 days', '76 days', '365 days'], correct: 2, explanation: 'At an average of 4,000 words per policy, reading them all would consume 76 full work days per year — making truly informed consent practically impossible for most users.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🌐', label: 'Data is the new oil', text: 'Personal data fuels a $300 billion industry and powers the AI systems you use daily' }, { icon: '📋', label: 'Consent is broken', text: 'Privacy policies are unreadable and dark patterns undermine genuine informed consent' }, { icon: '🔒', label: 'Rights are emerging', text: 'GDPR and CCPA represent a shift toward data rights, but enforcement remains a challenge' }] }
  ],

  7: [
    { type: 'hook', title: 'The Trolley Problem Goes Digital', body: 'A self-driving car is travelling at 60mph when a group of pedestrians steps into the road. It can swerve left (hitting one pedestrian), swerve right (hitting a wall, likely killing the passenger), or brake (probably hitting the group). This is not a philosophy thought experiment — it is a real engineering decision that autonomous vehicle companies must programme into their systems. The classic trolley problem has gone digital, and someone has to write the code.' },
    { type: 'concept', title: 'Ethical Frameworks for AI', body: 'Two major ethical traditions offer contrasting approaches to AI decision-making. Understanding both is essential for evaluating how AI should behave in moral dilemmas.', bullets: ['Utilitarianism: Choose the action that produces the greatest good for the greatest number', 'Deontology: Follow moral rules regardless of consequences (e.g. "never deliberately harm an innocent person")', 'Virtue ethics: Ask what a virtuous agent would do — focusing on character rather than rules or outcomes', 'In AI, utilitarian logic is easier to code (maximise a metric) but raises uncomfortable questions', 'Deontological constraints are harder to formalise but may better protect individual rights'], callout: 'The MIT Moral Machine experiment collected 40 million responses from 233 countries. Moral preferences varied dramatically by culture — there is no universal answer.' },
    { type: 'concept', title: 'Moral Agency and Machines', body: 'Can a machine be morally responsible? This question sits at the heart of AI ethics and has profound implications for law, insurance, and society.', bullets: ['Moral agency traditionally requires: consciousness, intention, and understanding of consequences', 'AI has none of these — it follows optimisation functions, not moral reasoning', 'Yet AI makes decisions with moral consequences: who gets a loan, who gets paroled, who gets medical treatment', 'The responsibility gap: When an AI causes harm, who is to blame? The developer? The company? The user?', 'Some propose "meaningful human control" — humans must remain responsible for AI decisions'], callout: 'A trolley switch is binary. Real-world AI decisions involve uncertainty, incomplete data, and consequences we cannot fully predict.' },
    { type: 'activity', title: 'Programme the Ethics', instructions: 'Your team is programming the ethical decision engine for a self-driving car. You must define the rules it follows in emergency scenarios.', steps: ['As a group, list 5 emergency scenarios a self-driving car might face', 'For each scenario, write the rule your car should follow (e.g. "minimise total harm" or "always protect the passenger")', 'Test your rules against each other — do any conflict?', 'Consider: Would your rules change if the pedestrian was a child? An elderly person? A group vs. an individual?', 'Present your ethical framework to another group and defend your choices', 'Vote as a class: Which framework would you trust with your life?'] },
    { type: 'discussion', title: 'Who Decides the Code?', questions: [{ num: 1, text: 'Should AI ethics be decided by engineers, ethicists, governments, or public vote? Why?' }, { num: 2, text: 'The Moral Machine experiment showed huge cultural differences in ethical preferences. Should self-driving cars behave differently in different countries?' }, { num: 3, text: 'If an autonomous vehicle kills someone, should the manufacturer face criminal charges? What about the programmer who wrote the decision algorithm?' }] },
    { type: 'quiz', question: 'What did the MIT Moral Machine experiment (40 million responses, 233 countries) reveal?', options: ['Everyone agrees autonomous cars should protect passengers', 'Only the age of potential victims matters to people', 'Moral preferences vary dramatically by culture', 'Nobody wants self-driving cars on the road'], correct: 2, explanation: 'The experiment found moral preferences varied significantly across cultures — there is no universal answer to how autonomous systems should resolve ethical dilemmas.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '⚖️', label: 'No easy answers', text: 'Utilitarian, deontological, and virtue ethics each have strengths and weaknesses when applied to AI' }, { icon: '🤖', label: 'Machines lack moral agency', text: 'AI makes decisions with moral consequences but cannot bear moral responsibility' }, { icon: '🌍', label: 'Culture shapes ethics', text: 'There is no universal moral code — AI ethics must grapple with cultural variation' }] }
  ],

  8: [
    { type: 'hook', title: 'Human in the Loop', body: 'In 2020, a radiologist using an AI diagnostic tool ignored the algorithm\'s recommendation and ordered further tests on a patient the AI had cleared. The additional tests revealed early-stage cancer. The AI had been wrong. In the same year, a different doctor blindly followed an AI drug recommendation that turned out to be dangerously inappropriate for the patient. Both cases illustrate the critical question: When should humans override AI, and when should they trust it?' },
    { type: 'concept', title: 'Three Levels of Human Oversight', body: 'The relationship between humans and AI in decision-making exists on a spectrum, from full human control to full automation.', bullets: ['Human-in-the-loop: AI makes recommendations but a human makes the final decision (e.g. AI flags suspicious transactions, human investigator reviews)', 'Human-on-the-loop: AI acts autonomously but a human monitors and can intervene (e.g. autonomous vehicle with human override capability)', 'Human-out-of-the-loop: AI operates fully autonomously with no human oversight (e.g. high-frequency trading algorithms, autonomous weapons)', 'The appropriate level depends on: stakes of the decision, reliability of the AI, reversibility of errors, and speed requirements', 'Most experts advocate for human-in-the-loop for any decision affecting individual rights or safety'], callout: 'Automation bias is real — studies show humans tend to defer to AI recommendations even when they have good reason to disagree.' },
    { type: 'concept', title: 'Domain-Specific Oversight', body: 'Different domains require different levels of human oversight based on risk, reversibility, and the consequences of error.', bullets: ['Healthcare: Human-in-the-loop is essential — AI assists diagnosis but doctors decide treatment', 'Criminal justice: High stakes demand human oversight, yet judges increasingly rely on algorithmic risk scores', 'Content moderation: Scale makes human-in-the-loop impractical — platforms use AI with human review of appeals', 'Military: Autonomous weapons raise the most urgent questions — the "killer robot" debate centres on human-out-of-the-loop', 'Finance: High-frequency trading already operates human-out-of-the-loop, sometimes with catastrophic flash crashes'], callout: 'The 2010 Flash Crash saw the Dow Jones drop 1,000 points in minutes due to autonomous trading algorithms — human-out-of-the-loop at its most dangerous.' },
    { type: 'activity', title: 'Design the Oversight Model', instructions: 'For each scenario, decide the appropriate level of human oversight and design the human-AI collaboration model.', steps: ['Read each scenario: (a) AI grading student essays, (b) AI diagnosing skin cancer from photos, (c) AI approving small business loans, (d) AI moderating social media content', 'For each, choose: human-in-the-loop, human-on-the-loop, or human-out-of-the-loop', 'Justify your choice with at least two reasons', 'Design the workflow: What does the AI do? When does the human step in? What information does the human see?', 'Identify the risks of automation bias in your design — how do you prevent humans from rubber-stamping AI decisions?', 'Present your best design to the class'] },
    { type: 'discussion', title: 'Trust and Autonomy', questions: [{ num: 1, text: 'As AI becomes more accurate than humans in specific tasks, at what point should we let it operate without human oversight?' }, { num: 2, text: 'How can we prevent automation bias — the tendency for humans to defer to AI even when they should not?' }, { num: 3, text: 'Should autonomous weapons (AI that can kill without human approval) be banned under international law? Why or why not?' }] },
    { type: 'quiz', question: 'What is "automation bias"?', options: ['When AI systems develop biased outputs', 'When automated systems malfunction under load', 'When humans defer to AI recommendations even when they should disagree', 'When companies automate jobs to reduce costs'], correct: 2, explanation: 'Automation bias is the tendency to over-trust AI, deferring to its recommendations even when human judgment suggests otherwise. Designing against this requires active strategies, not just adding a human to the process.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '👤', label: 'Three levels', text: 'Human-in-the-loop, on-the-loop, and out-of-the-loop represent increasing AI autonomy' }, { icon: '⚠️', label: 'Automation bias', text: 'Humans tend to over-trust AI — designing against this is crucial' }, { icon: '🏥', label: 'Context matters', text: 'The right level of oversight depends on stakes, reversibility, and reliability' }] }
  ],

  9: [
    { type: 'hook', title: 'Prompt Architecture', body: 'Two students ask ChatGPT the same question: "Tell me about climate change." One gets a rambling, generic essay. The other gets a concise, A-Level-appropriate analysis with Harvard references, structured as an essay plan with counter-arguments. The difference? The second student used the PTFC framework. Prompt engineering is the single most important skill for getting useful output from AI — and it is a skill you can learn in one lesson.' },
    { type: 'concept', title: 'The PTFC Framework', body: 'PTFC stands for Persona, Task, Format, and Constraints. This four-part framework transforms vague prompts into precise instructions that produce high-quality AI output.', bullets: ['Persona: Tell the AI who to be — "You are an experienced A-Level economics examiner"', 'Task: State exactly what to do — "Analyse the impact of quantitative easing on inflation"', 'Format: Specify the output structure — "Present as a 5-paragraph essay with introduction, 3 body paragraphs, and conclusion"', 'Constraints: Set boundaries — "Maximum 500 words, use UK English, include at least 2 counter-arguments, cite real economists"', 'A weak prompt: "Write about QE." A strong PTFC prompt produces output you can actually use.'], callout: 'Prompt engineering is not about tricking AI — it is about communicating clearly. The same skills that make you a good brief-writer make you a good prompt engineer.' },
    { type: 'concept', title: 'Iterating for Quality', body: 'The first output from any prompt is rarely the best. Systematic iteration — refining your prompt based on what the AI returns — is where the real skill lies.', bullets: ['Evaluate the first output: What is good? What is missing? What is wrong?', 'Refine one element at a time so you can see what changes improve the output', 'Add specificity: Vague instructions produce vague results', 'Use follow-up prompts: "Now make the tone more formal" or "Add a counter-argument to paragraph 2"', 'Keep a prompt log (see the Prompt Iteration Log resource) to track what works'], callout: 'Expert prompt engineers typically iterate 3-5 times before accepting output. Beginners often accept the first response.' },
    { type: 'activity', title: 'PTFC Challenge', instructions: 'Build three prompts using the PTFC framework, test them, and iterate for quality. Use the PTFC Framework Reference Card from Resources.', steps: ['Write a PTFC prompt for: "Help me revise for my biology exam on photosynthesis"', 'Write a PTFC prompt for: "Create a debate argument about social media regulation"', 'Write a PTFC prompt for: "Explain machine learning to a 10-year-old"', 'Test all three on an AI model and evaluate the outputs', 'Iterate each prompt at least twice, improving based on the output', 'Record your prompts and results in the Prompt Iteration Log'] },
    { type: 'discussion', title: 'The Skill of the Future?', questions: [{ num: 1, text: 'If AI can generate content, is the ability to write good prompts more valuable than the ability to write good essays?' }, { num: 2, text: 'Should prompt engineering be taught as a core skill in schools alongside reading, writing, and maths?' }, { num: 3, text: 'How might the PTFC framework apply beyond AI — in writing emails, briefs, or instructions for humans?' }] },
    { type: 'quiz', question: 'In the PTFC prompt framework, what does the "C" stand for?', options: ['Context', 'Clarity', 'Creativity', 'Constraints'], correct: 3, explanation: 'C stands for Constraints — the limits and rules that shape output, such as word count, reading level, tone, or specific requirements. Without constraints, AI outputs tend to be generic and unfocused.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🏗️', label: 'PTFC framework', text: 'Persona, Task, Format, Constraints — four elements that transform weak prompts into powerful ones' }, { icon: '🔄', label: 'Iteration is key', text: 'Expert prompt engineers refine 3-5 times — never accept the first output' }, { icon: '📝', label: 'Transferable skill', text: 'Clear communication with AI is the same skill as clear communication with humans' }] }
  ],

  10: [
    { type: 'hook', title: 'Synthetic Creativity & Copyright', body: 'In 2022, an AI-generated artwork called "Theatre D\'Opera Spatial" won first prize at the Colorado State Fair art competition. The artist, Jason Allen, used Midjourney to generate the image. Traditional artists were outraged. Getty Images sued Stability AI for training on millions of copyrighted photos without permission. The New York Times sued OpenAI for training on its articles. The question tearing the creative world apart: Can AI be creative, and who owns what it produces?' },
    { type: 'concept', title: 'AI and Creativity', body: 'Whether AI can be truly creative depends on how you define creativity. This is not just a philosophical debate — it has real legal and economic consequences.', bullets: ['Computational creativity: AI can produce novel, surprising, and valuable outputs — a functional definition of creativity', 'But AI has no intention, emotion, or lived experience — it combines patterns from training data', 'Remixing vs. creating: All human creativity builds on prior work too — is AI fundamentally different?', 'The "1000 monkeys" argument: With enough random generation, something valuable will emerge — is that creativity?', 'Generative AI can now produce art, music, code, poetry, and scientific hypotheses'], callout: 'Margaret Boden identifies three types of creativity: combinational (mixing ideas), exploratory (working within a style), and transformational (breaking rules). AI excels at the first two but arguably cannot do the third.' },
    { type: 'concept', title: 'Copyright and Ownership', body: 'Current copyright law was not designed for AI-generated content. Courts around the world are racing to answer fundamental questions about ownership and fair use.', bullets: ['US Copyright Office ruled (2023): AI-generated content cannot be copyrighted — only human-authored work qualifies', 'Training data lawsuits: NYT v. OpenAI, Getty v. Stability AI, authors v. Meta — all argue training on copyrighted work is infringement', 'Fair use defence: AI companies argue training is transformative use, similar to how humans learn from reading', 'The artist\'s role: If a human writes the prompt, selects, and curates the output — is that enough human authorship?', 'Economic impact: Stock photo, illustration, and copywriting industries are already seeing revenue decline'], callout: 'If AI-generated content cannot be copyrighted, anyone can copy and sell it. This creates a strange incentive: why pay for AI art if no one owns it?' },
    { type: 'activity', title: 'The Copyright Court', instructions: 'Stage a mock trial to decide whether AI-generated art should be copyrightable. Assign roles and argue the case.', steps: ['Assign roles: Judge, Artist (human painter), AI Artist (prompt engineer), AI Company lawyer, Copyright Office representative', 'The prompt engineer presents their AI artwork and argues it deserves copyright protection', 'The human painter argues that AI art devalues human creativity and should not be protected', 'The AI Company argues that training on copyrighted data is fair use', 'The Copyright Office presents current legal standards', 'The Judge (and class jury) deliver a verdict with reasoning'] },
    { type: 'discussion', title: 'The Future of Creative Work', questions: [{ num: 1, text: 'If AI can produce art indistinguishable from human art, does it matter whether a human or machine created it?' }, { num: 2, text: 'Should artists whose work was used to train AI models be compensated? How would that work in practice?' }, { num: 3, text: 'Will AI replace creative professionals, augment them, or create entirely new creative roles?' }] },
    { type: 'quiz', question: 'Under current UK and US copyright law, can purely AI-generated works be copyrighted?', options: ['Yes — the AI is considered the author', 'Yes — the company that built the AI owns it', 'No — copyright requires a human author', 'Only if the AI used licensed training data'], correct: 2, explanation: 'Both UK and US copyright law require a human author. In Thaler v. Vidal (2023), the US Copyright Office confirmed that purely AI-generated images are not copyrightable.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🎨', label: 'Creativity is contested', text: 'AI can produce novel valuable outputs but lacks intention and lived experience' }, { icon: '⚖️', label: 'Copyright is unsettled', text: 'Courts worldwide are wrestling with who owns AI-generated content and whether training on copyrighted data is fair use' }, { icon: '💼', label: 'Economic disruption', text: 'Creative industries are already being transformed — adaptation is essential' }] }
  ],

  11: [
    { type: 'hook', title: 'Deep Research & Career Disruption', body: 'Goldman Sachs estimates that AI could automate 300 million full-time jobs globally. McKinsey predicts 12 million Americans will need to switch occupations by 2030. Yet the World Economic Forum also projects AI will create 97 million new roles. The truth is nuanced: AI is not simply destroying jobs — it is reshaping them. Today, you will use AI research tools to investigate how your future career might be transformed.' },
    { type: 'video', title: 'The Rise of the Machines — Why Automation is Different this Time', videoId: 'WSKi8HfcxEk', credit: 'Kurzgesagt – In a Nutshell · 2017 · 12 min', intro: 'Why is this wave of automation different from every previous one? Kurzgesagt argues that for the first time, machines are developing "cognitive muscles" — threatening not just physical labour but intellectual work too. Watch for the key distinction between mechanical and cognitive automation, then apply it to the careers you will research today.' },
    { type: 'concept', title: 'AI-Assisted Deep Research', body: 'Deep research means going beyond surface-level searches to find, synthesise, and critically evaluate information from multiple sources. AI tools can accelerate this process dramatically.', bullets: ['AI search tools (Perplexity, Consensus) can synthesise findings across thousands of papers', 'But they can also hallucinate sources, misrepresent findings, and reflect search biases', 'Critical evaluation remains a human skill: check sources, verify claims, assess methodology', 'Triangulation: Use at least three independent sources to confirm any AI-generated claim', 'AI is best used as a research assistant, not a research replacement'], callout: 'An AI research tool told a student that a famous study had been replicated 14 times. The study had actually failed to replicate. Always verify.' },
    { type: 'concept', title: 'Career Disruption Patterns', body: 'AI disrupts careers in predictable patterns. Understanding these patterns helps you prepare for a workforce that looks very different from today.', bullets: ['Routine cognitive tasks (data entry, basic analysis, bookkeeping) are most at risk', 'Creative, interpersonal, and strategic roles are harder to automate but not immune', 'New roles emerge: AI trainers, prompt engineers, AI ethicists, human-AI interaction designers', 'The "centaur" model: Humans and AI working together outperform either alone', 'Skills that remain valuable: critical thinking, emotional intelligence, complex problem-solving, ethical reasoning'], callout: 'The careers most disrupted are not always the ones you expect. Radiologists were predicted to be replaced by 2020 — they have not been, because the job is more than reading scans.' },
    { type: 'activity', title: 'Research Your Future Career', instructions: 'Use AI research tools to investigate how AI will impact a career you are interested in.', steps: ['Choose a career you are considering or curious about', 'Use an AI search tool to find: What tasks in this career can AI already do?', 'Research: What new skills will this career require in 5-10 years?', 'Find at least one example of AI already being used in this field', 'Verify your AI-generated findings against at least two traditional sources', 'Write a 200-word briefing: How should someone entering this field prepare?'] },
    { type: 'discussion', title: 'The Future of Work', questions: [{ num: 1, text: 'Is it your responsibility to "AI-proof" your career, or should governments and employers protect workers from disruption?' }, { num: 2, text: 'If AI can do a job cheaper and faster than a human, is there still value in having a human do it? In which cases?' }, { num: 3, text: 'How should education change to prepare students for a workforce where AI is a colleague, not just a tool?' }] },
    { type: 'quiz', question: 'According to Goldman Sachs, how many full-time jobs could AI automate globally?', options: ['30 million', '300 million', '3 billion', '10 billion'], correct: 1, explanation: 'Goldman Sachs estimates 300 million jobs could be automated. However, the World Economic Forum projects 97 million new roles will emerge — the net effect depends on how societies prepare and adapt.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '📊', label: 'Disruption is real', text: 'AI will automate 300 million jobs but also create 97 million new roles — the net effect depends on preparation' }, { icon: '🔍', label: 'Research critically', text: 'AI research tools accelerate discovery but require human verification and critical evaluation' }, { icon: '🧠', label: 'Future-proof skills', text: 'Critical thinking, emotional intelligence, and ethical reasoning remain uniquely human advantages' }] }
  ],

  12: [
    { type: 'hook', title: 'The Revision Loop', body: 'A university study found that students who iteratively refined AI-generated essay drafts produced work rated 40% higher than students who accepted the first output. Another study showed that students who used AI without iteration actually performed worse than those who wrote without AI at all. The lesson is clear: AI is a powerful revision partner, but only if you treat it as the start of the process, not the end.' },
    { type: 'concept', title: 'The Iteration Mindset', body: 'Treating AI output as a first draft rather than a final product fundamentally changes the quality of work you produce. The revision loop is a systematic approach to iterative improvement.', bullets: ['Generate: Use a well-crafted PTFC prompt to produce a first draft', 'Evaluate: Read critically — what is accurate? What is weak? What is missing?', 'Refine: Give the AI specific feedback — "Make paragraph 2 more analytical" or "Add a counter-argument"', 'Verify: Check all facts, quotes, and references against reliable sources', 'Polish: Make final edits in your own voice — the output should sound like you, not like AI'], callout: 'The revision loop is not just for AI. This generate-evaluate-refine cycle is the same process expert writers have always used.' },
    { type: 'concept', title: 'AI as a Revision Partner', body: 'AI excels at specific revision tasks when prompted correctly. Knowing what to ask for turns a generic chatbot into a powerful editing tool.', bullets: ['Structural feedback: "Analyse the argument structure of this essay and suggest improvements"', 'Counter-arguments: "What are the strongest counter-arguments to my thesis?"', 'Clarity check: "Rewrite this paragraph for a Year 12 audience without losing technical accuracy"', 'Evidence gaps: "What claims in this essay need additional supporting evidence?"', 'Tone adjustment: "Make this more formal/academic/persuasive while keeping the same arguments"'], callout: 'The best revision prompts are specific about what to change and what to keep. "Make it better" is a weak prompt. "Strengthen the evidence in paragraph 3 while maintaining the conversational tone" is a strong one.' },
    { type: 'activity', title: 'The Three-Draft Challenge', instructions: 'Take a piece of your own work and run it through three iterations with AI, tracking improvements using the Prompt Iteration Log.', steps: ['Choose a paragraph or short essay you have written for another subject', 'Draft 1: Paste it into an AI tool and ask for structural feedback using a PTFC prompt', 'Record the AI feedback and make changes — save as Draft 2', 'Draft 2: Ask the AI to identify weak arguments and suggest counter-arguments', 'Record feedback, make changes — save as Draft 3', 'Compare Draft 1 and Draft 3 side by side: What improved? What is your voice vs. the AI?'] },
    { type: 'discussion', title: 'Authenticity and AI', questions: [{ num: 1, text: 'After three rounds of AI-assisted revision, is the essay still yours? Where is the line between AI-assisted and AI-generated?' }, { num: 2, text: 'Should students be required to disclose when they have used AI as a revision tool? Why or why not?' }, { num: 3, text: 'How can you use AI to improve your writing without becoming dependent on it?' }] },
    { type: 'quiz', question: 'How do expert prompt engineers typically differ from beginners?', options: ['They write much longer prompts', 'They use more expensive AI models', 'They iterate 3-5 times before accepting output', 'They always use the PTFC framework'], correct: 2, explanation: 'Experts iterate 3-5 times, refining one element per round and evaluating what improves output. Beginners tend to accept the first response, which is rarely the best result.' },
    { type: 'summary', title: 'Key Takeaways', points: [{ icon: '🔄', label: 'Iterate, don\'t accept', text: 'Students who refine AI output produce 40% better work than those who accept the first draft' }, { icon: '🎯', label: 'Specific prompts win', text: 'The best revision prompts target specific weaknesses rather than asking for generic improvement' }, { icon: '✍️', label: 'Keep your voice', text: 'AI is a revision partner, not a ghostwriter — the final product should sound like you' }] }
  ]

};
