#!/usr/bin/env node
/* Update AI news — fetches a handful of AI RSS/Atom feeds, picks the
   most recent AI-relevant stories, and regenerates js/news-live.js.
   Run weekly by .github/workflows/update-news.yml (and by hand:
   `node scripts/update-news.mjs`). No dependencies — Node 18+.

   The generated file defines AI_NEWS_LIVE, which app.js merges into
   the curated AI_NEWS list at load (deduped by headline). Teacher
   picks added via the Admin Dashboard (Supabase) still appear too. */

import { writeFileSync } from 'node:fs';

const FEEDS = [
  { url: 'https://feeds.bbci.co.uk/news/technology/rss.xml', source: 'BBC News', aiOnly: true },
  { url: 'https://www.theverge.com/ai-artificial-intelligence/rss/index.xml', source: 'The Verge' },
  { url: 'https://www.technologyreview.com/topic/artificial-intelligence/feed/', source: 'MIT Technology Review' },
  { url: 'https://openai.com/blog/rss.xml', source: 'OpenAI' },
  { url: 'https://blog.google/technology/ai/rss/', source: 'Google' },
];

const AI_WORDS = /\b(AI|artificial intelligence|machine learning|neural|LLM|chatbot|ChatGPT|OpenAI|DeepMind|Anthropic|Claude|Gemini|Copilot|deepfake|algorithm)\b/i;
const MAX_ITEMS = 12;
const MAX_PER_SOURCE = 4;
const MAX_AGE_DAYS = 45;
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

function decode(s) {
  return (s || '')
    .replace(/<!\[CDATA\[(.*?)\]\]>/gs, '$1')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#0?39;/g, "'").replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(n))
    .replace(/&amp;/g, '&')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function pick(block, tag) {
  const m = block.match(new RegExp('<' + tag + '[^>]*>([\\s\\S]*?)</' + tag + '>', 'i'));
  return m ? m[1] : '';
}

function parseFeed(xml, source) {
  const items = [];
  // RSS <item> and Atom <entry>
  const blocks = xml.match(/<item[\s>][\s\S]*?<\/item>|<entry[\s>][\s\S]*?<\/entry>/gi) || [];
  for (const b of blocks) {
    const headline = decode(pick(b, 'title'));
    let url = decode(pick(b, 'link'));
    if (!url) {
      const href = b.match(/<link[^>]*href="([^"]+)"/i);
      url = href ? href[1] : '';
    }
    const dateRaw = decode(pick(b, 'pubDate')) || decode(pick(b, 'updated')) || decode(pick(b, 'published')) || decode(pick(b, 'dc:date'));
    const when = dateRaw ? new Date(dateRaw) : null;
    if (!headline || !when || isNaN(when)) continue;
    items.push({ headline, url, when, source });
  }
  return items;
}

function tagFor(headline) {
  const h = headline.toLowerCase();
  if (/(regulat|law|act\b|government|policy|parliament|congress|white house|ban\b|rules)/.test(h)) return 'policy';
  if (/(study|research|paper|breakthrough|scientist|discover|nobel)/.test(h)) return 'research';
  if (/(nhs|health|medical|cancer|diagnos|patient)/.test(h)) return 'health';
  if (/(deepfake|scam|bias|privacy|surveillance|misinformation|safety)/.test(h)) return 'ethics';
  if (/(launch|release|unveil|model|app\b|feature|tool|update|free)/.test(h)) return 'tools';
  return 'industry';
}

const all = [];
for (const f of FEEDS) {
  try {
    const res = await fetch(f.url, {
      headers: { 'user-agent': 'digital-innovations-news-bot/1.0', accept: 'application/rss+xml, application/atom+xml, application/xml, text/xml' },
      signal: AbortSignal.timeout(20000),
    });
    if (!res.ok) { console.error('skip', f.source, res.status); continue; }
    let items = parseFeed(await res.text(), f.source);
    if (f.aiOnly) items = items.filter(i => AI_WORDS.test(i.headline));
    items.sort((a, b) => b.when - a.when);
    all.push(...items.slice(0, MAX_PER_SOURCE));
    console.log('ok  ', f.source, items.length, 'items');
  } catch (e) {
    console.error('skip', f.source, e.message);
  }
}

const cutoff = Date.now() - MAX_AGE_DAYS * 86400000;
const fresh = all
  .filter(i => i.when.getTime() > cutoff)
  .sort((a, b) => b.when - a.when)
  .slice(0, MAX_ITEMS)
  .map(i => ({
    headline: i.headline.slice(0, 160),
    source: i.source,
    date: MONTHS[i.when.getMonth()] + ' ' + i.when.getFullYear(),
    tag: tagFor(i.headline),
    url: i.url,
  }));

if (fresh.length < 3) {
  console.error('Only ' + fresh.length + ' fresh items fetched — keeping the existing news-live.js');
  process.exit(0); // don't clobber a good file with a bad run
}

const out = '/* AUTO-GENERATED by scripts/update-news.mjs — do not edit by hand.\n' +
  '   Refreshed weekly by the update-news GitHub Action.\n' +
  '   Last update: ' + new Date().toISOString().slice(0, 10) + ' */\n' +
  'var AI_NEWS_LIVE = ' + JSON.stringify(fresh, null, 2) + ';\n';

writeFileSync(new URL('../js/news-live.js', import.meta.url), out);
console.log('wrote js/news-live.js with ' + fresh.length + ' items');
